"""Form 1 Computer Science — chapters 1 to 4."""
from helpers import *

GENERATIONS = svg(440, 120, ''.join([
    box(5, 10, 80, 64, '1st', 'Vacuum tubes', 'v-box'), arrow(85, 42, 93, 42),
    box(93, 10, 80, 64, '2nd', 'Transistors', 'v-box2'), arrow(173, 42, 181, 42),
    box(181, 10, 80, 64, '3rd', 'ICs (chips)', 'v-box3'), arrow(261, 42, 269, 42),
    box(269, 10, 80, 64, '4th', 'Micro-', 'v-box'), arrow(349, 42, 357, 42),
    box(357, 10, 80, 64, '5th', 'AI', 'v-box2'),
    '<text x="309" y="90" text-anchor="middle" class="v-s">processors</text>',
    '<text x="220" y="112" text-anchor="middle" class="v-s">Each generation: smaller, faster, cheaper</text>',
]), 'Five generations of computers')

IPO = flow([('Input', 'data goes in'), ('Process', 'the CPU works'), ('Output', 'result comes out')])

AI_LOOP = flow([('Data', 'many examples'), ('Learn', 'find patterns'), ('Decide', 'answer / predict')])

LAB = svg(420, 230, ''.join([
    '<rect x="10" y="10" width="400" height="210" rx="12" class="v-line"/>',
    box(30, 30, 80, 40, 'PC', '', 'v-box'), box(130, 30, 80, 40, 'PC', '', 'v-box'), box(230, 30, 80, 40, 'PC', '', 'v-box'),
    box(30, 150, 80, 40, 'PC', '', 'v-box'), box(130, 150, 80, 40, 'PC', '', 'v-box'), box(230, 150, 80, 40, 'PC', '', 'v-box'),
    box(330, 90, 70, 50, "Teacher", '', 'v-box2'),
    box(330, 160, 70, 40, 'Printer', '', 'v-box3'),
    '<rect x="330" y="20" width="70" height="40" rx="8" class="v-box3"/><text x="365" y="45" text-anchor="middle" class="v-t">Fire ext.</text>',
    marker(110, 30, 1), marker(330, 90, 2), marker(330, 160, 3), marker(330, 20, 4),
]), 'Computer laboratory plan')

LESSONS = {
    1: L('Computer Science is the study of computers and how we use them to solve problems.',
         [('What is a computer?',
           '<p>A computer is an <b>electronic machine</b> that takes in <b>data</b>, <b>processes</b> it and gives out <b>information</b>.</p>' + IPO +
           '<p class="wt-key">Input → Process → Output</p>'),
          ('What is Computer Science?',
           '<p>Computer Science is the study of computers: how they work, how we give them instructions (programs) and how we use them to solve problems.</p>'),
          ('Data and information',
           '<div class="two-col"><div><b>Data</b>raw facts: 12, 15, 9</div><div><b>Information</b>processed data with meaning: "The average mark is 12"</div></div>'
           '<p class="wt-key">The computer turns data into information.</p>'),
          ('Why study it?',
           '<ul><li>Computers are used in schools, hospitals, banks and shops</li><li>You learn to solve problems step by step</li><li>Many jobs need computer skills</li></ul>')],
         [mcq('A computer is…', ['an electronic machine that processes data', 'a television with a keyboard', 'a machine that only plays games'], 'an electronic machine that processes data', 'A computer takes data, processes it and gives information.'),
          order('Put the stages of computing in order.', ['Input', 'Process', 'Output'], 'Data goes in (input), the computer works on it (process), and the result comes out (output).'),
          sort('Is it data or information?', ['Data', 'Information'], [('15, 12, 18', 'Data'), ('"Paul came first in class"', 'Information'), ('Mon, Tue, 32°C', 'Data'), ('"It will be hot on Tuesday"', 'Information')], 'Data is raw facts. Information has meaning.'),
          tf('Computer Science is only about repairing computers.', False, 'It is the study of how computers work and how we use them to solve problems.'),
          fill('Complete the sentence.', 'A computer accepts {0}, processes it and produces {1}.', [['data'], ['information']], 'Data goes in, information comes out.')]),

    2: L('Computers took a long journey: from counting tools to the smartphone in your pocket.',
         [('Before electronic computers',
           '<ul><li><b>Abacus</b>: counting with beads (thousands of years ago)</li><li><b>Pascal\'s calculator</b> (1642): adding machine</li><li><b>Charles Babbage</b> (1830s): designed the Analytical Engine — the "father of the computer"</li><li><b>Ada Lovelace</b>: wrote the first program</li></ul>'),
          ('Five generations', GENERATIONS + '<p class="wt-key">Each new generation is smaller, faster and cheaper.</p>'),
          ('Generations in short',
           '<ul><li>1st: vacuum tubes, very big (ENIAC)</li><li>2nd: transistors</li><li>3rd: integrated circuits (chips)</li><li>4th: microprocessors → personal computers</li><li>5th: artificial intelligence</li></ul>')],
         [match('Match each person or tool to what it is known for.', [('Abacus', 'Counting with beads'), ('Charles Babbage', 'Father of the computer'), ('Ada Lovelace', 'First computer program'), ('Blaise Pascal', 'Early adding machine')]),
          order('Put the generations in order, from oldest to newest.', ['Vacuum tubes', 'Transistors', 'Integrated circuits', 'Microprocessors', 'Artificial intelligence'], 'Each generation replaced the technology of the one before.'),
          mcq('Which generation is known for artificial intelligence?', ['First', 'Third', 'Fifth'], 'Fifth', 'The fifth generation focuses on AI.'),
          tf('Computers of the first generation were small and cheap.', False, 'They used vacuum tubes and filled whole rooms.'),
          mcq('What happened to computers from one generation to the next?', ['They became smaller, faster and cheaper', 'They became bigger and slower', 'Nothing changed'], 'They became smaller, faster and cheaper')]),

    3: L('Computers can be grouped by their size, by the type of data they use, and by their purpose.',
         [('By size',
           '<ul><li><b>Supercomputer</b>: the fastest, for weather forecasts and science</li><li><b>Mainframe</b>: big organisations (banks) with many users</li><li><b>Minicomputer</b>: medium businesses</li><li><b>Microcomputer</b>: personal computers — desktops, laptops, tablets, phones</li></ul>'),
          ('By type of data',
           '<ul><li><b>Digital</b>: works with numbers (0 and 1) — your PC</li><li><b>Analog</b>: works with continuous values — a thermometer, a speedometer</li><li><b>Hybrid</b>: both — e.g. hospital machines</li></ul>'),
          ('By purpose',
           '<div class="two-col"><div><b>General purpose</b>does many jobs: a PC</div><div><b>Special purpose</b>does one job: an ATM, a calculator</div></div>')],
         [order('Put these computers from biggest to smallest.', ['Supercomputer', 'Mainframe', 'Minicomputer', 'Microcomputer'], 'Supercomputers are the biggest and fastest; microcomputers are personal computers.'),
          sort('Sort by type of data.', ['Digital', 'Analog', 'Hybrid'], [('Laptop', 'Digital'), ('Mercury thermometer', 'Analog'), ('Car speedometer (needle)', 'Analog'), ('Smartphone', 'Digital'), ('Hospital ECG machine', 'Hybrid')]),
          sort('General or special purpose?', ['General purpose', 'Special purpose'], [('Desktop computer', 'General purpose'), ('ATM (cash machine)', 'Special purpose'), ('Laptop', 'General purpose'), ('Pocket calculator', 'Special purpose')]),
          mcq('Which computer would forecast the weather for the whole country?', ['Supercomputer', 'Microcomputer', 'Calculator'], 'Supercomputer', 'Weather forecasting needs huge calculations, so it uses supercomputers.'),
          tf('A smartphone is a microcomputer.', True, 'Phones, tablets, laptops and desktops are all microcomputers.')]),

    4: L('Artificial Intelligence (AI) is when a computer does things that normally need human intelligence.',
         [('What is AI?',
           '<p>AI lets computers <b>learn</b>, <b>recognise</b> and <b>decide</b> — like recognising a face or understanding speech.</p>' + AI_LOOP),
          ('AI around you',
           '<div class="chips"><span>Voice assistants</span><span>Face unlock</span><span>Google Translate</span><span>Chatbots</span><span>Video recommendations</span></div>'),
          ('How does AI learn?',
           '<p>It looks at <b>many examples</b> (data) and finds patterns. Show it thousands of cat photos, and it learns what a cat looks like.</p>'
           '<p class="wt-key">More good data → better AI.</p>')],
         [mcq('AI is…', ['a computer doing tasks that normally need human intelligence', 'a new type of keyboard', 'a computer virus'], 'a computer doing tasks that normally need human intelligence'),
          sort('Does it use AI?', ['Uses AI', 'No AI'], [('Face unlock on a phone', 'Uses AI'), ('A light switch', 'No AI'), ('Google Translate', 'Uses AI'), ('A ruler', 'No AI'), ('Chatbot answering questions', 'Uses AI')]),
          order('How does an AI learn? Put in order.', ['Collect many examples (data)', 'Find patterns in the data', 'Use the patterns to decide or predict'], 'AI learns from data, then uses what it learned.'),
          tf('AI learns by looking at many examples.', True, 'This is called learning from data.'),
          fill('Complete the sentence.', 'AI stands for {0} {1}.', [['artificial'], ['intelligence']])]),

    5: L('AI helps in many areas, but it must be used fairly and safely.',
         [('Where AI helps',
           '<ul><li><b>Health</b>: reading X-rays</li><li><b>Farming</b>: detecting plant diseases from photos</li><li><b>Transport</b>: maps finding the fastest road</li><li><b>Education</b>: tutoring apps</li></ul>'),
          ('Ethics: using AI the right way',
           '<ul><li><b>Privacy</b>: protect people\'s personal data</li><li><b>Fairness</b>: AI must not treat people unfairly</li><li><b>Honesty</b>: don\'t present AI work as your own</li><li><b>Safety</b>: humans must check important decisions</li></ul>'),
          ('Remember',
           '<p class="wt-key">AI can make mistakes. Always check what it says.</p>')],
         [match('Match the area to how AI helps.', [('Health', 'Reading X-rays'), ('Farming', 'Spotting plant diseases'), ('Transport', 'Finding the fastest road'), ('Education', 'Tutoring apps')]),
          sort('Good or bad use of AI?', ['Good use', 'Bad use'], [('Using AI to explain a hard topic', 'Good use'), ('Copying an AI essay as your homework', 'Bad use'), ('Sharing a friend\'s photo with an AI app without asking', 'Bad use'), ('Checking AI answers in your textbook', 'Good use')]),
          mcq('An AI app gives you an answer for your homework. What should you do?', ['Check it with your notes or textbook', 'Copy it without reading', 'Share it as your own work'], 'Check it with your notes or textbook', 'AI can be wrong, and you must not present its work as your own.'),
          tf('AI never makes mistakes.', False, 'AI can be wrong. A human should always check important results.'),
          mcq('Which is an ethical rule for AI?', ['Protect people\'s privacy', 'Use any data you find', 'Hide how decisions are made'], 'Protect people\'s privacy')]),

    6: L('A prompt is the instruction you give an AI tool. Better prompts give better answers.',
         [('What is a prompt?',
           '<p>A prompt is what you type (or say) to an AI tool like a chatbot.</p><p>Example: <i>"Explain what a CPU is to a Form 1 student in 3 sentences."</i></p>'),
          ('A good prompt is clear',
           '<ul><li>Say <b>what</b> you want (explain, list, summarise)</li><li>Give the <b>topic</b></li><li>Say <b>who</b> it is for (Form 1 student)</li><li>Give the <b>format</b> (3 sentences, a table)</li></ul>'),
          ('Bad vs good',
           '<div class="two-col"><div><b>Weak</b>"computer"</div><div><b>Strong</b>"List 4 parts of a computer with one sentence each."</div></div>'),
          ('Stay safe',
           '<p class="wt-key">Never type passwords or private information into an AI tool.</p>')],
         [mcq('Which prompt is best?', ['"computer"', '"tell me stuff"', '"Explain what RAM is to a Form 1 student in 3 short sentences."'], '"Explain what RAM is to a Form 1 student in 3 short sentences."', 'It says what to do, the topic, who it is for and the length.'),
          sort('Good prompt or weak prompt?', ['Good prompt', 'Weak prompt'], [('"Give 5 tips to keep a laptop safe, as a list."', 'Good prompt'), ('"laptop"', 'Weak prompt'), ('"Summarise the history of computers in one paragraph."', 'Good prompt'), ('"help"', 'Weak prompt')]),
          match('Match each part of a prompt to an example.', [('Task', 'Explain'), ('Topic', 'the mouse'), ('Audience', 'for a Form 1 student'), ('Format', 'in 3 sentences')]),
          tf('It is safe to give your password to an AI chatbot.', False, 'Never share passwords or private information.'),
          mcq('The AI answer is too hard to understand. What should you do?', ['Ask again: "Explain it more simply, with an example"', 'Give up', 'Copy it anyway'], 'Ask again: "Explain it more simply, with an example"', 'You can improve the answer by improving your prompt.')]),

    8: L('Decomposition means breaking a big problem into smaller parts that are easier to solve.',
         [('Break it down',
           '<p>Big problem: <b>Organise a class party</b></p>' + flow(['Food', 'Music', 'Decorations']) +
           '<p class="wt-key">Solve each small part, and the big problem is solved.</p>'),
          ('Why decompose?',
           '<ul><li>Small parts are easier to understand</li><li>Different people can work on different parts</li><li>You don\'t forget anything</li></ul>'),
          ('In computing',
           '<p>A game is broken into parts: the player, the score, the levels, the sound. Programmers build each part separately.</p>')],
         [mcq('Decomposition means…', ['breaking a problem into smaller parts', 'deleting a problem', 'making a problem bigger'], 'breaking a problem into smaller parts'),
          sort('Which are sub-tasks of "Prepare for an exam"?', ['Sub-task', 'Not related'], [('Make a revision timetable', 'Sub-task'), ('Revise one chapter each day', 'Sub-task'), ('Do past questions', 'Sub-task'), ('Watch a football match', 'Not related')]),
          sort('A school website is decomposed. Which parts belong to it?', ['Part of the website', 'Not part'], [('Home page', 'Part of the website'), ('Contact form', 'Part of the website'), ('News page', 'Part of the website'), ('The school bus', 'Not part')]),
          tf('Decomposition makes problems harder to solve.', False, 'Smaller parts are easier to solve.'),
          mcq('Why is decomposition useful in a team?', ['Each person can work on a different part', 'Everyone must do everything', 'Only one person can work'], 'Each person can work on a different part')]),

    9: L('Pattern recognition means spotting things that are the same or that repeat.',
         [('What is a pattern?',
           '<p>A pattern is something that repeats or is similar.</p><div class="chips"><span>2, 4, 6, 8, …</span><span>🔴🔵🔴🔵…</span><span>Mon → Tue → Wed</span></div>'),
          ('Why look for patterns?',
           '<p>If problems are similar, you can solve them the <b>same way</b>. You don\'t start from zero each time.</p>'),
          ('Example',
           '<p>Every cat drawing has: eyes, ears, whiskers, a tail. Once you see the pattern, you can draw any cat.</p>')],
         [fill('What comes next?', '3, 6, 9, 12, {0}', [['15']], 'The pattern adds 3 each time.'),
          fill('What comes next?', '1, 2, 4, 8, {0}', [['16']], 'Each number is doubled.'),
          mcq('What do all of these have in common: car, bus, motorbike?', ['They are vehicles with wheels', 'They can fly', 'They are animals'], 'They are vehicles with wheels', 'Spotting what is the same is pattern recognition.'),
          tf('Pattern recognition helps us reuse a solution for similar problems.', True),
          mcq('A teacher marks 40 scripts. She notices many students make the same mistake. This is…', ['pattern recognition', 'decomposition', 'a virus'], 'pattern recognition')]),

    10: L('Abstraction means keeping only the important details and ignoring the rest.',
          [('Keep what matters',
            '<p>A <b>map</b> shows roads and towns, not every tree and house. It keeps only what you need to travel.</p>'
            '<p class="wt-key">Abstraction = remove unnecessary details.</p>'),
           ('Example',
            '<p>To make a game of football you need: players, ball, goals, score.</p><p>You don\'t need: the colour of the referee\'s socks.</p>'),
           ('In computing',
            '<p>When you press "Save", you don\'t need to know how the hard disk stores the file. The details are hidden.</p>')],
          [mcq('Abstraction means…', ['keeping important details and hiding the rest', 'adding as many details as possible', 'breaking a problem into parts'], 'keeping important details and hiding the rest', 'Breaking into parts is decomposition.'),
           sort('You design a bus timetable app. Which details are important?', ['Important', 'Not needed'], [('Departure time', 'Important'), ('Bus stop names', 'Important'), ('Colour of the driver\'s shirt', 'Not needed'), ('Bus number', 'Important'), ('The radio station playing on the bus', 'Not needed')]),
           match('Match the thinking skill to its meaning.', [('Decomposition', 'Break into smaller parts'), ('Pattern recognition', 'Find what is similar'), ('Abstraction', 'Keep only important details'), ('Algorithm', 'Steps to solve the problem')]),
           tf('A map is an example of abstraction.', True, 'It shows only what you need, not every detail.')]),

    13: L('A computing environment is everything that works together so we can use computers.',
          [('Parts of a computing environment',
            '<ul><li><b>Hardware</b>: the parts you can touch</li><li><b>Software</b>: the programs</li><li><b>Data</b>: what is processed</li><li><b>People</b>: the users</li><li><b>Procedures</b>: the rules and steps</li><li><b>Network</b>: connections between computers</li></ul>'),
           ('Each part has a role',
            '<p>Hardware does the work, software gives the instructions, people use it, data is processed, procedures say how, and networks connect.</p>'
            '<p class="wt-key">If one part is missing, the system does not work well.</p>')],
          [match('Match each part to its role.', [('Hardware', 'Physical parts you can touch'), ('Software', 'Programs that give instructions'), ('People', 'Use and manage the computer'), ('Data', 'Facts that are processed'), ('Procedures', 'Rules and steps to follow')]),
           sort('Hardware or software?', ['Hardware', 'Software'], [('Keyboard', 'Hardware'), ('Microsoft Word', 'Software'), ('Monitor', 'Hardware'), ('Windows', 'Software'), ('Printer', 'Hardware')]),
           tf('Software can be touched.', False, 'Software is programs. You can touch the disk it is stored on, not the program itself.'),
           mcq('The rules for using the school lab are part of…', ['procedures', 'hardware', 'data'], 'procedures')]),

    14: L('Many people use computers, and they all work with data and information.',
          [('Types of users',
            '<ul><li><b>End users</b>: use programs (students, secretaries)</li><li><b>Programmers</b>: write programs</li><li><b>System administrators</b>: manage computers and networks</li><li><b>Technicians</b>: repair and maintain</li></ul>'),
           ('Data vs information',
            '<div class="two-col"><div><b>Data</b>raw facts: names and marks</div><div><b>Information</b>processed and useful: the class ranking</div></div>'),
           ('Good information is…',
            '<ul><li>Accurate (correct)</li><li>Up to date</li><li>Complete</li><li>Relevant (useful for the task)</li></ul>')],
          [match('Match the user to the job.', [('End user', 'Types a letter in Word'), ('Programmer', 'Writes a new app'), ('Technician', 'Repairs a broken computer'), ('System administrator', 'Manages the school network')]),
           sort('Data or information?', ['Data', 'Information'], [('List of all marks', 'Data'), ('"The class average is 13/20"', 'Information'), ('Temperatures for each day', 'Data'), ('"This week was hotter than last week"', 'Information')]),
           mcq('Which is NOT a quality of good information?', ['Out of date', 'Accurate', 'Complete'], 'Out of date', 'Good information must be up to date.'),
           tf('Information is data that has been processed.', True)]),

    16: L('A computer laboratory has equipment for working and devices that keep people and computers safe.',
          [('Main equipment',
            '<div class="chips"><span>Computers</span><span>Printer</span><span>Projector</span><span>Network switch</span><span>Tables & chairs</span></div>'),
           ('Safety devices',
            '<ul><li><b>Fire extinguisher</b>: puts out fires (CO₂ type for electrical fires)</li><li><b>UPS</b>: gives power for a short time when the light goes</li><li><b>Stabiliser</b>: keeps the voltage steady</li><li><b>Air conditioner / fans</b>: keep the room cool</li></ul>'),
           ('Remember',
            '<p class="wt-key">Never use water on an electrical fire.</p>')],
          [match('Match the device to its use.', [('UPS', 'Power for a short time during a power cut'), ('Stabiliser', 'Keeps the voltage steady'), ('Fire extinguisher', 'Puts out fires'), ('Air conditioner', 'Keeps the room cool')]),
           sort('Working equipment or safety device?', ['Working equipment', 'Safety device'], [('Printer', 'Working equipment'), ('Fire extinguisher', 'Safety device'), ('Projector', 'Working equipment'), ('UPS', 'Safety device'), ('Stabiliser', 'Safety device')]),
           tf('Water is the best way to put out an electrical fire.', False, 'Water conducts electricity. Use a CO₂ extinguisher.'),
           mcq('The light goes off while you are typing. Which device lets you save your work?', ['UPS', 'Projector', 'Scanner'], 'UPS')]),

    17: L('A good lab layout makes it safe, comfortable and easy for the teacher to see everyone.',
          [('Common designs',
            '<ul><li><b>Rows</b>: like a classroom, all facing the board</li><li><b>U-shape</b>: computers around the walls, teacher in the middle</li><li><b>Islands / clusters</b>: groups of computers for teamwork</li></ul>'),
           ('A lab plan', LAB + '<p>Teacher can see all screens; safety equipment near the door.</p>'),
           ('A good design has',
            '<ul><li>Space to move between tables</li><li>Cables hidden, not on the floor</li><li>Good light and air</li><li>Easy access to the fire extinguisher and exit</li></ul>')],
          [label('Label the lab plan.', LAB, ['Student computer', 'Teacher\'s desk', 'Printer', 'Fire extinguisher'], 'Safety equipment should be easy to reach.'),
           match('Match the layout to its best use.', [('Rows', 'Everyone watches the board'), ('U-shape', 'Teacher sees all screens easily'), ('Clusters', 'Group work')]),
           sort('Good or bad for a lab?', ['Good', 'Bad'], [('Cables taped down or hidden', 'Good'), ('Bags in the walkway', 'Bad'), ('Good ventilation', 'Good'), ('Exit blocked by a cupboard', 'Bad')]),
           tf('In a U-shape lab, the teacher can easily see every screen.', True)]),

    18: L('Good behaviour in the lab protects you, other students and the computers.',
          [('Do',
            '<ul><li>Enter only with permission</li><li>Keep hands clean and dry</li><li>Shut down properly at the end</li><li>Report any problem to the teacher</li></ul>'),
           ('Don\'t',
            '<ul><li>Eat or drink near computers</li><li>Run or play in the lab</li><li>Touch cables or sockets</li><li>Install programs or change settings without permission</li></ul>'),
           ('Why?', '<p class="wt-key">Water and food damage computers. Electricity can hurt you.</p>')],
          [sort('Allowed or not allowed in the lab?', ['Allowed', 'Not allowed'], [('Drinking a soda at the keyboard', 'Not allowed'), ('Reporting a broken mouse', 'Allowed'), ('Running between tables', 'Not allowed'), ('Shutting down properly', 'Allowed'), ('Installing a game without permission', 'Not allowed')]),
           mcq('You see sparks from a socket. What do you do?', ['Tell the teacher immediately and stay away', 'Touch it to check', 'Pour water on it'], 'Tell the teacher immediately and stay away'),
           tf('It is fine to eat biscuits over the keyboard.', False, 'Crumbs and liquids damage keyboards.'),
           order('Put the end-of-lesson steps in order.', ['Save your work', 'Close all programs', 'Shut down the computer', 'Push in your chair and leave quietly'])]),
}
