"""Form 2 Computer Science: internet, assistive technology, block programming, digital identity, cloud, IoT."""
from helpers import *
from f2_cs_part1 import table

CONNECT = flow([('Device', 'phone, PC'), ('Router / modem', 'or SIM'), ('ISP', 'MTN, Orange…'), ('Internet', 'websites')], )

BROWSER = svg(440, 150, ''.join([
    '<rect x="5" y="5" width="430" height="140" rx="10" class="v-line"/>',
    '<rect x="15" y="12" width="120" height="22" rx="6" class="v-box2"/><text x="75" y="28" text-anchor="middle" class="v-s">My tab ×</text>',
    '<rect x="15" y="42" width="70" height="24" rx="6" class="v-box3"/><text x="50" y="59" text-anchor="middle" class="v-s">← → ⟳</text>',
    '<rect x="95" y="42" width="300" height="24" rx="12" class="v-box"/><text x="105" y="59" class="v-s">🔒 https://www.asghinlabs.com</text>',
    '<text x="415" y="60" text-anchor="middle" class="v-t">☆</text>',
    '<rect x="15" y="76" width="410" height="60" rx="6" class="v-line"/><text x="220" y="110" text-anchor="middle" class="v-s">web page</text>',
    marker(15, 12, 1), marker(15, 42, 2), marker(100, 42, 3), marker(415, 46, 4),
]), 'Parts of a browser window')

URL = svg(440, 90, ''.join([
    box(5, 10, 80, 40, 'https://', '', 'v-box2'), box(90, 10, 200, 40, 'www.asghinlabs.com', '', 'v-box'), box(295, 10, 140, 40, '/academy', '', 'v-box3'),
    '<text x="45" y="75" text-anchor="middle" class="v-s">protocol</text>',
    '<text x="190" y="75" text-anchor="middle" class="v-s">domain name</text>',
    '<text x="365" y="75" text-anchor="middle" class="v-s">path (page)</text>',
]), 'Parts of a web address')

SQUARE = svg(160, 160, '<rect x="30" y="30" width="100" height="100" class="v-line"/><text x="80" y="85" text-anchor="middle" class="v-s">100 steps</text>', 'A square')

IOT = flow([('Sensor', 'senses'), ('Microcontroller', 'decides'), ('Actuator', 'acts')])

CLOUD = svg(440, 160, ''.join([
    '<ellipse cx="220" cy="55" rx="120" ry="45" class="v-box2"/><text x="220" y="52" text-anchor="middle" class="v-t">The cloud</text><text x="220" y="70" text-anchor="middle" class="v-s">servers in data centres</text>',
    box(10, 115, 110, 40, 'Phone', '', 'v-box'), box(165, 115, 110, 40, 'Laptop', '', 'v-box'), box(320, 115, 110, 40, 'School PC', '', 'v-box'),
    arrow(65, 115, 140, 85), arrow(220, 115, 220, 100), arrow(375, 115, 300, 85),
]), 'Devices using the cloud')

LESSONS = {
    21: L('To use the internet you need a device, a connection and an Internet Service Provider (ISP).',
          [('What is the internet?',
            '<p>The <b>internet</b> is a worldwide network of networks. It connects billions of computers and phones.</p>'),
           ('What you need', CONNECT +
            '<ul><li>A <b>device</b>: phone, computer, tablet</li><li>A <b>connection device</b>: modem, router, or a SIM card</li><li>An <b>ISP</b> (Internet Service Provider) and a subscription or data bundle</li><li>A <b>browser</b> or app</li></ul>'),
           ('Types of connection',
            table(['Connection', 'Example'], [['Mobile data', '3G, 4G, 5G on a phone'], ['Wi-Fi', 'wireless, from a router or hotspot'], ['Fibre / cable', 'fast fixed line at home or office'], ['Satellite', 'remote areas']])),
           ('Speed and data',
            '<p>Speed is measured in <b>Mbps</b> (megabits per second). Data bundles are counted in <b>MB</b> and <b>GB</b>. Videos use much more data than text.</p>'
            '<p class="wt-key">Sharing your phone connection = mobile hotspot.</p>')],
          [order('Put the path of your connection in order.', ['Your device', 'Router / modem or SIM', 'ISP', 'The internet'], 'Your data goes through your ISP to reach the internet.'),
           mcq('An ISP is…', ['a company that gives you internet access', 'a type of virus', 'a web page'], 'a company that gives you internet access', 'In Cameroon, mobile operators are ISPs.'),
           match('Match the connection to its description.', [('4G', 'Mobile data on a phone'), ('Wi-Fi', 'Wireless connection from a router'), ('Fibre', 'Very fast fixed line'), ('Satellite', 'Used in very remote areas')]),
           mcq('What uses the most data?', ['Watching a 1-hour video', 'Sending 10 text messages', 'Reading an email'], 'Watching a 1-hour video'),
           tf('A mobile hotspot lets other devices use your phone\'s internet.', True),
           mcq('Internet speed is measured in…', ['Mbps', 'kg', 'GHz'], 'Mbps')]),

    22: L('A browser opens web pages. A search engine helps you find them.',
          [('Browser or search engine?',
            '<div class="two-col"><div><b>Browser</b>the program: Chrome, Firefox, Edge, Safari</div><div><b>Search engine</b>a website that finds pages: Google, Bing</div></div>'),
           ('Parts of the browser', BROWSER +
            '<ol><li><b>Tab</b>: one open page</li><li><b>Back, forward, refresh</b></li><li><b>Address bar</b>: type the web address (URL)</li><li><b>Bookmark</b> (☆): save a page for later</li></ol>'),
           ('A web address (URL)', URL + '<p class="wt-key">🔒 https = secure connection. Never type passwords on a site without it.</p>'),
           ('Search smarter',
            '<ul><li>Use <b>key words</b>: <i>causes of malaria</i></li><li>Exact phrase in quotes: <i>"Reunification of Cameroon"</i></li><li>Remove a word with minus: <i>jaguar -car</i></li></ul>'),
           ('Other tools',
            '<p><b>History</b>: pages you visited. <b>Downloads</b>: files you saved. <b>Private / incognito</b> window: does not keep history on that device.</p>')],
          [sort('Browser or search engine?', ['Browser', 'Search engine'], [('Google Chrome', 'Browser'), ('Google Search', 'Search engine'), ('Mozilla Firefox', 'Browser'), ('Bing', 'Search engine'), ('Microsoft Edge', 'Browser')]),
           label('Name the parts of the browser.', BROWSER, ['Tab', 'Back / forward / refresh', 'Address bar', 'Bookmark']),
           match('Match each part of the URL https://www.asghinlabs.com/academy', [('https://', 'Protocol'), ('www.asghinlabs.com', 'Domain name'), ('/academy', 'Path (page)')]),
           mcq('Which search finds pages with the exact phrase?', ['"first world war causes"', 'first world war causes', 'first -world war'], '"first world war causes"', 'Quotes search for the exact phrase.'),
           tf('A page with 🔒 https uses a secure connection.', True),
           mcq('You want to find a useful page again tomorrow. What do you do?', ['Bookmark it', 'Close the browser', 'Open an incognito window'], 'Bookmark it')]),

    24: L('Assistive technologies help people with disabilities use computers.',
          [('Visual impairment',
            '<ul><li><b>Screen reader</b>: reads the screen aloud</li><li><b>Screen magnifier</b>: makes things bigger</li><li><b>Braille display</b>: shows text as raised dots</li><li><b>High contrast</b> colours</li></ul>'),
           ('Hearing impairment',
            '<ul><li><b>Captions / subtitles</b> on videos</li><li><b>Visual alerts</b>: the screen flashes instead of a sound</li><li><b>Speech-to-text</b>: speech is written on screen</li></ul>'),
           ('Physical (motor) impairment',
            '<ul><li><b>Voice control</b>: use the computer by speaking</li><li><b>Eye-tracking</b>: move the pointer with your eyes</li><li><b>Adapted keyboards</b>, trackball, foot mouse</li><li><b>Sticky keys</b>: press keys one at a time instead of together</li></ul>'),
           ('Learning difficulties',
            '<p><b>Text-to-speech</b>, <b>word prediction</b> and dyslexia-friendly fonts help reading and writing.</p><p class="wt-key">Technology should be usable by everyone.</p>')],
          [match('Match the technology to the person it helps most.', [('Screen reader', 'A blind student'), ('Captions', 'A deaf student'), ('Eye-tracking', 'A person who cannot move their hands'), ('Word prediction', 'A student with dyslexia')]),
           sort('Which impairment does it help?', ['Visual', 'Hearing', 'Motor'], [('Braille display', 'Visual'), ('Screen magnifier', 'Visual'), ('Visual alerts', 'Hearing'), ('Voice control', 'Motor'), ('Sticky keys', 'Motor'), ('Subtitles', 'Hearing')]),
           mcq('A student cannot press Ctrl and C at the same time. Which feature helps?', ['Sticky keys', 'Screen magnifier', 'Captions'], 'Sticky keys', 'Sticky keys let you press one key after the other.'),
           tf('A screen reader turns text on the screen into speech.', True),
           mcq('What is a Braille display?', ['A device that shows text as raised dots', 'A very big screen', 'A printer for photos'], 'A device that shows text as raised dots')]),

    26: L('In block programming (like Scratch) you build programs by joining blocks, like a puzzle.',
          [('The Scratch window',
            '<ul><li><b>Stage</b>: where the action happens</li><li><b>Sprite</b>: a character you program (the cat)</li><li><b>Block palette</b>: all the blocks</li><li><b>Script area</b>: where you join blocks</li></ul>'),
           ('Block categories',
            table(['Category', 'Example block'], [['Events', 'when green flag clicked'], ['Motion', 'move 10 steps, turn 90°'], ['Looks', 'say Hello! for 2 seconds'], ['Sound', 'play sound Meow'], ['Control', 'repeat 10, wait 1 second']])),
           ('A first program',
            '<p><code>when green flag clicked<br>say "Hello!" for 2 seconds<br>move 100 steps<br>play sound Meow</code></p><p class="wt-key">Blocks run from top to bottom: this is a sequence.</p>'),
           ('Draw a square', SQUARE + '<p><code>pen down<br>move 100 steps, turn 90°<br>move 100 steps, turn 90°<br>move 100 steps, turn 90°<br>move 100 steps, turn 90°</code></p>')],
          [match('Match the block to its category.', [('when green flag clicked', 'Events'), ('move 10 steps', 'Motion'), ('say Hello!', 'Looks'), ('play sound Meow', 'Sound'), ('wait 1 second', 'Control')]),
           match('Match the part of Scratch to its meaning.', [('Sprite', 'A character you program'), ('Stage', 'Where the action is shown'), ('Script area', 'Where you join blocks')]),
           order('Put the blocks in order: the cat starts, greets you, then walks.', ['when green flag clicked', 'say "Hi!" for 2 seconds', 'move 100 steps']),
           mcq('To draw a square, how many times must the sprite "move 100, turn 90°"?', ['4', '3', '90'], '4', 'A square has 4 sides and 4 corners of 90°.', visual=SQUARE),
           fill('To draw a triangle with equal sides, the sprite turns 3 times by…', '{0} degrees', [['120']], '360 ÷ 3 = 120.'),
           tf('Blocks in a script run from top to bottom.', True)]),

    27: L('Loops repeat, conditions decide, and variables remember. They make programs smart.',
          [('Loops', '<ul><li><b>repeat 4</b>: do it 4 times</li><li><b>forever</b>: never stops</li></ul><p>Square with a loop:</p><p><code>repeat 4<br>&nbsp;&nbsp;move 100 steps<br>&nbsp;&nbsp;turn 90°</code></p>'),
           ('Conditions', '<p><code>if touching edge? then<br>&nbsp;&nbsp;turn 180°<br>else<br>&nbsp;&nbsp;move 10 steps</code></p><p>The program chooses what to do.</p>'),
           ('Variables', '<p>A <b>variable</b> is a named box that stores a value, like <b>score</b>.</p><p><code>set score to 0<br>when sprite clicked: change score by 1</code></p>'),
           ('Asking the user', '<p><code>ask "What is your name?" and wait<br>say join "Hello " answer</code></p><p class="wt-key">Loop = repeat · If = decide · Variable = remember</p>')],
          [mcq('Which block draws a square in the fewest blocks?', ['repeat 4 (move 100, turn 90°)', 'forever (move 100)', 'move 400 steps'], 'repeat 4 (move 100, turn 90°)'),
           fill('A score starts at 0. The player clicks the sprite 5 times (change score by 1). What is the score?', 'score = {0}', [['5']]),
           fill('A score starts at 10. "repeat 3: change score by 2". What is the score?', 'score = {0}', [['16']], '10 + 2 + 2 + 2 = 16'),
           sort('Loop, condition or variable?', ['Loop', 'Condition', 'Variable'], [('repeat 10', 'Loop'), ('if touching edge? then', 'Condition'), ('set lives to 3', 'Variable'), ('forever', 'Loop'), ('if score > 100 then', 'Condition')]),
           mcq('A game must check all the time if the cat touches the ball. Which block holds the "if"?', ['forever', 'repeat 1', 'when green flag clicked only'], 'forever', 'A forever loop keeps checking while the game runs.'),
           tf('A variable can store a value that changes, like a score.', True)]),

    29: L('Your digital identity is all the information that identifies you online.',
          [('What is a digital identity?',
            '<p>It is who you are on the internet: your <b>usernames</b>, <b>email</b>, <b>profile photo</b>, <b>phone number</b>, accounts and what you post.</p>'),
           ('How we prove who we are',
            '<ul><li>Something you <b>know</b>: password, PIN</li><li>Something you <b>have</b>: phone (SMS code)</li><li>Something you <b>are</b>: fingerprint, face</li></ul>'),
           ('Identity theft',
            '<p>A criminal uses your identity: steals your account, sends messages in your name, or asks your contacts for money.</p>'),
           ('Protect your identity',
            '<ul><li>Strong, different passwords</li><li>Turn on <b>two-step verification</b></li><li>Never share codes received by SMS</li><li>Be careful with what you post</li></ul><p class="wt-key">Your identity online is as valuable as your ID card.</p>')],
          [sort('Is it part of your digital identity?', ['Yes', 'No'], [('Your email address', 'Yes'), ('Your WhatsApp profile photo', 'Yes'), ('Your username', 'Yes'), ('The colour of your school bag', 'No')]),
           match('Match each proof to its type.', [('Password', 'Something you know'), ('Code sent to your phone', 'Something you have'), ('Fingerprint', 'Something you are')]),
           mcq('Someone calls: "I sent you a code by mistake, please give it to me." What do you do?', ['Refuse: it may be to steal my account', 'Give the code quickly', 'Post the code on WhatsApp'], 'Refuse: it may be to steal my account'),
           tf('Using the same password everywhere is safe.', False, 'If one site is hacked, all your accounts are in danger.'),
           mcq('Which is the strongest password?', ['M@ngo-Rain-2026!', '123456', 'password'], 'M@ngo-Rain-2026!', 'Long, with letters, numbers and symbols.')]),

    30: L('A digital footprint is the trail of data you leave online. Some you leave on purpose, some without knowing.',
          [('What is a digital footprint?', '<p>Everything you do online leaves a trace: posts, likes, searches, photos, locations.</p>'),
           ('Active footprint',
            '<p>Data you share <b>on purpose</b>: posts, comments, photos, messages, filling a form.</p>'),
           ('Passive footprint',
            '<p>Data collected <b>without you noticing</b>: cookies, search history, your location, your IP address, which ads you click.</p>'),
           ('It lasts',
            '<p class="wt-key">What goes online can stay online, even after you delete it (screenshots, copies).</p>')],
          [sort('Active or passive footprint?', ['Active', 'Passive'], [('Posting a photo', 'Active'), ('A website saving cookies', 'Passive'), ('Commenting on a video', 'Active'), ('Your phone recording your location', 'Passive'), ('Filling an online form', 'Active'), ('Your search history', 'Passive')]),
           mcq('A digital footprint is…', ['the trail of data you leave online', 'a footprint on your keyboard', 'a type of virus'], 'the trail of data you leave online'),
           tf('If you delete a post, it is gone forever and nobody can see it.', False, 'Others may have copied or screenshotted it.'),
           mcq('Which is a passive footprint?', ['Ads chosen from the pages you visited', 'A status you posted', 'A comment you wrote'], 'Ads chosen from the pages you visited')]),

    31: L('You can manage your footprint: think before you post and control your settings.',
          [('Think before you post', '<p>Ask: <b>Is it true? Is it kind? Would I be happy if my parents or a future employer saw it?</b></p>'),
           ('Control your settings',
            '<ul><li>Set accounts to <b>private</b></li><li>Choose who sees your status and photo</li><li>Turn off <b>location</b> when not needed</li><li>Refuse unnecessary cookies</li></ul>'),
           ('Check and clean',
            '<ul><li>Search your own name online</li><li>Delete old posts and accounts you no longer use</li><li>Untag yourself from embarrassing photos</li></ul>'),
           ('Build a positive footprint',
            '<p>Share your projects, achievements and helpful posts. Schools and employers do look.</p><p class="wt-key">Your footprint can help you or harm you: manage it.</p>')],
          [sort('Good or bad for your footprint?', ['Good', 'Bad'], [('Sharing your science project', 'Good'), ('Posting insults about a teacher', 'Bad'), ('Setting your account to private', 'Good'), ('Sharing your home location publicly', 'Bad'), ('Deleting an old unused account', 'Good')]),
           order('Put the steps to check your footprint in order.', ['Search your name online', 'Look at what appears', 'Delete or hide what you do not want', 'Change your privacy settings']),
           mcq('Before posting, which question should you ask?', ['Would I be happy if a future employer saw this?', 'Will it get many likes?', 'Is my battery full?'], 'Would I be happy if a future employer saw this?'),
           tf('Turning off location when you do not need it reduces your passive footprint.', True)]),

    32: L('Cloud computing means using storage and programs on internet servers instead of your own device.',
          [('What is the cloud?', CLOUD + '<p>Your files and apps live on <b>servers</b> in big data centres. You reach them through the internet.</p>'),
           ('Examples', '<div class="chips"><span>Google Drive</span><span>OneDrive</span><span>Gmail</span><span>Google Docs</span><span>YouTube</span><span>WhatsApp backup</span></div>'),
           ('Types of cloud service',
            table(['Service', 'You get', 'Example'], [['SaaS', 'ready apps', 'Gmail, Google Docs'], ['PaaS', 'a platform to build apps', 'Google App Engine'], ['IaaS', 'servers and storage', 'Amazon Web Services']])),
           ('Advantages and disadvantages',
            '<div class="two-col"><div><b>➕</b>access anywhere · automatic backup · easy sharing · no installation</div><div><b>➖</b>needs internet · uses data · privacy risks · may cost money</div></div>')],
          [mcq('Cloud computing means…', ['using storage and programs on internet servers', 'computing when the weather is cloudy', 'storing files only on a flash drive'], 'using storage and programs on internet servers'),
           sort('Cloud service or not?', ['Cloud', 'Not cloud'], [('Google Drive', 'Cloud'), ('A file saved on your flash drive', 'Not cloud'), ('Gmail', 'Cloud'), ('Calculator app with no internet', 'Not cloud')]),
           match('Match the service type to its meaning.', [('SaaS', 'Ready-to-use apps'), ('PaaS', 'A platform to build apps'), ('IaaS', 'Servers and storage to rent')]),
           sort('Advantage or disadvantage?', ['Advantage', 'Disadvantage'], [('Open your files from any device', 'Advantage'), ('Needs an internet connection', 'Disadvantage'), ('Files are backed up if your phone is lost', 'Advantage'), ('Uses your data bundle', 'Disadvantage')]),
           tf('If your phone is stolen, photos backed up to the cloud can be recovered.', True)]),

    33: L('A sensor measures something in the environment and turns it into a signal for a computer.',
          [('What is a sensor?', '<p>A sensor <b>detects</b> a physical quantity (heat, light, movement) and sends it as data.</p>'),
           ('Common sensors',
            table(['Sensor', 'Measures', 'Used in'], [['Temperature', 'heat', 'thermostat, incubator'], ['Light', 'brightness', 'street lights, phone screen'], ['Motion (PIR)', 'movement', 'alarms, automatic doors'], ['Humidity / moisture', 'water', 'smart farming'], ['Pressure', 'force', 'weighing scale, touchscreen'], ['Smoke / gas', 'smoke, gas', 'fire alarm'], ['GPS', 'position', 'maps, tracking']])),
           ('Analog to digital',
            '<p>Most sensors give an <b>analog</b> signal (continuous). An <b>ADC</b> (analogue-to-digital converter) turns it into numbers the computer can use.</p>')],
          [match('Match the sensor to what it measures.', [('Temperature sensor', 'Heat'), ('Light sensor', 'Brightness'), ('Motion sensor', 'Movement'), ('Moisture sensor', 'Water in soil'), ('GPS', 'Position')]),
           match('Which sensor is used here?', [('Street lights that switch on at night', 'Light sensor'), ('Automatic door at a supermarket', 'Motion sensor'), ('Fire alarm', 'Smoke sensor'), ('Egg incubator', 'Temperature sensor')]),
           mcq('A farmer wants water pumps to start when the soil is dry. Which sensor?', ['Soil moisture sensor', 'Light sensor', 'GPS'], 'Soil moisture sensor'),
           tf('An ADC turns an analog signal into digital data.', True),
           mcq('Your phone screen gets brighter in the sun. Which sensor does that?', ['Light sensor', 'Gas sensor', 'Pressure sensor'], 'Light sensor')]),

    34: L('An embedded system is a small computer inside a device. IoT connects such devices to the internet.',
          [('Embedded systems',
            '<p>A small computer (a <b>microcontroller</b>) built into a device to do <b>one job</b>.</p><div class="chips"><span>Washing machine</span><span>Microwave</span><span>Traffic lights</span><span>Car airbags</span><span>Digital watch</span></div>'),
           ('How they work', IOT + '<p>Example: an automatic irrigation system: moisture sensor → microcontroller decides "soil is dry" → pump (actuator) waters the plants.</p>'),
           ('Internet of Things (IoT)',
            '<p>Everyday objects connected to the internet, so they can send data and be controlled remotely: smart watch, smart bulb, smart meter, smart door lock, connected camera.</p>'),
           ('Pros and cons',
            '<div class="two-col"><div><b>➕</b>automatic, saves time and energy, remote control</div><div><b>➖</b>hacking risk, privacy, needs internet and power</div></div>')],
          [sort('Embedded system or general-purpose computer?', ['Embedded system', 'General-purpose computer'], [('Microwave oven', 'Embedded system'), ('Laptop', 'General-purpose computer'), ('Traffic lights controller', 'Embedded system'), ('Desktop PC', 'General-purpose computer'), ('Washing machine', 'Embedded system')]),
           order('Put the parts of an automatic irrigation system in order.', ['Moisture sensor measures the soil', 'Microcontroller decides the soil is dry', 'Pump starts watering'], 'Sense → decide → act'),
           match('Match the part to its role.', [('Sensor', 'Measures'), ('Microcontroller', 'Decides'), ('Actuator', 'Acts (motor, pump, light)')]),
           mcq('Which is an IoT device?', ['A smart bulb you switch on from your phone', 'A pencil', 'A paper book'], 'A smart bulb you switch on from your phone'),
           tf('IoT devices can be hacked if they are not protected.', True)]),
}
