"""Form 2 Computer Science: office software, security, communication, maintenance, credibility (lessons 36-54)."""
from helpers import *
from f2_cs_part1 import table


def _cell(x, y, w, h, t, cls='v-line'):
    return f'<rect x="{x}" y="{y}" width="{w}" height="{h}" class="{cls}"/><text x="{x + w / 2}" y="{y + h / 2 + 5}" text-anchor="middle" class="v-s">{t}</text>'


SHEET = svg(440, 190, ''.join([
    '<rect x="5" y="5" width="140" height="24" rx="4" class="v-box3"/><text x="75" y="22" text-anchor="middle" class="v-s">fx =B2*C2</text>',
    _cell(5, 38, 40, 26, ''), _cell(45, 38, 130, 26, 'A', 'v-box'), _cell(175, 38, 90, 26, 'B', 'v-box'), _cell(265, 38, 90, 26, 'C', 'v-box'), _cell(355, 38, 80, 26, 'D', 'v-box'),
    _cell(5, 64, 40, 26, '1', 'v-box'), _cell(45, 64, 130, 26, 'Item'), _cell(175, 64, 90, 26, 'Price'), _cell(265, 64, 90, 26, 'Qty'), _cell(355, 64, 80, 26, 'Total'),
    _cell(5, 90, 40, 26, '2', 'v-box'), _cell(45, 90, 130, 26, 'Pen'), _cell(175, 90, 90, 26, '100'), _cell(265, 90, 90, 26, '3'), _cell(355, 90, 80, 26, '300', 'v-box2'),
    _cell(5, 116, 40, 26, '3', 'v-box'), _cell(45, 116, 130, 26, 'Book'), _cell(175, 116, 90, 26, '500'), _cell(265, 116, 90, 26, '2'), _cell(355, 116, 80, 26, '1000'),
    '<rect x="345" y="152" width="90" height="26" rx="4" class="v-box3"/><text x="390" y="169" text-anchor="middle" class="v-s">Sheet1</text>',
    marker(10, 10, 1), marker(160, 51, 2), marker(14, 98, 3), marker(430, 98, 4), marker(340, 158, 5),
]), 'Spreadsheet window')

MARKS = table(['', 'A', 'B'], [['1', 'Name', 'Mark'], ['2', 'Awa', '12'], ['3', 'Paul', '8'], ['4', 'Ngum', '15'], ['5', 'Eric', '9']])

BACKUP321 = svg(440, 120, ''.join([
    box(5, 10, 135, 70, '3', 'copies of data', 'v-box'),
    box(152, 10, 135, 70, '2', 'different media', 'v-box2'),
    box(299, 10, 135, 70, '1', 'copy off-site', 'v-box3'),
    '<text x="220" y="108" text-anchor="middle" class="v-s">e.g. laptop + flash drive + cloud</text>',
]), 'The 3-2-1 backup rule')

EMAIL = svg(440, 200, ''.join([
    '<rect x="5" y="5" width="430" height="190" rx="10" class="v-line"/>',
    '<text x="20" y="32" class="v-s">To: teacher@school.cm</text>', marker(415, 26, 1),
    '<text x="20" y="58" class="v-s">Cc: parent@gmail.com</text>', marker(415, 52, 2),
    '<text x="20" y="84" class="v-s">Subject: Form 2 project – Awa N.</text>', marker(415, 78, 3),
    '<text x="20" y="114" class="v-s">Good morning Sir, please find my project attached…</text>', marker(415, 108, 4),
    '<rect x="20" y="150" width="150" height="30" rx="6" class="v-box3"/><text x="95" y="170" text-anchor="middle" class="v-s">📎 project.pdf</text>', marker(185, 165, 5),
]), 'Parts of an email')

LESSONS = {
    36: L('A spreadsheet is a grid of cells used to store numbers and calculate automatically.',
          [('Examples', '<div class="chips"><span>Microsoft Excel</span><span>LibreOffice Calc</span><span>Google Sheets</span></div><p>Used for marks, budgets, sales, statistics.</p>'),
           ('The window', SHEET +
            '<ol><li><b>Formula bar</b>: shows what is in the cell</li><li><b>Column</b> (letters A, B, C…)</li><li><b>Row</b> (numbers 1, 2, 3…)</li><li><b>Cell</b>: where a column and row meet → <b>D2</b></li><li><b>Sheet tab</b>: a file (workbook) can have many sheets</li></ol>'),
           ('Key words',
            '<ul><li><b>Cell address</b>: column + row, e.g. <b>B3</b></li><li><b>Range</b>: a block of cells, e.g. <b>B2:B5</b></li><li><b>Workbook</b>: the file; <b>worksheet</b>: one page</li></ul>'),
           ('Types of data',
            '<ul><li><b>Label</b> (text): Name, Pen</li><li><b>Value</b> (number): 100, 3</li><li><b>Formula</b>: starts with <b>=</b>, e.g. <b>=B2*C2</b></li></ul><p class="wt-key">A formula always starts with =</p>')],
          [label('Name the parts of the spreadsheet.', SHEET, ['Formula bar', 'Column', 'Row', 'Cell', 'Sheet tab']),
           fill('In the picture, "Book" is in column A, row 3. Its address is…', '{0}', [['A3']], visual=SHEET),
           fill('In the picture, what is the address of the cell containing 500?', '{0}', [['B3']]),
           sort('Label, value or formula?', ['Label', 'Value', 'Formula'], [('Price', 'Label'), ('250', 'Value'), ('=B2*C2', 'Formula'), ('Total', 'Label'), ('=SUM(D2:D3)', 'Formula'), ('12', 'Value')]),
           mcq('How many cells are in the range A1:A4?', ['4', '1', '5'], '4', 'A1, A2, A3, A4.'),
           tf('A formula in a spreadsheet must start with =', True)]),

    37: L('Spreadsheets solve problems with formulas and functions that recalculate automatically.',
          [('Formulas', '<p>Use cell addresses, not numbers: <b>=B2*C2</b>. If the price changes, the total updates by itself.</p>'
            '<p>Operators: <b>+ − * /</b> (× is * and ÷ is /)</p>'),
           ('Functions', MARKS + table(['Function', 'Result'], [['=SUM(B2:B5)', '44'], ['=AVERAGE(B2:B5)', '11'], ['=MAX(B2:B5)', '15'], ['=MIN(B2:B5)', '8'], ['=COUNT(B2:B5)', '4']])),
           ('Copy a formula',
            '<p>Drag the <b>fill handle</b> (small square at the corner of the cell) down: <b>=B2*C2</b> becomes <b>=B3*C3</b>, <b>=B4*C4</b>…</p>'),
           ('More tools', '<ul><li><b>Sort</b>: put marks from highest to lowest</li><li><b>Chart</b>: show data as a bar or pie chart</li><li><b>IF</b>: <code>=IF(B2&gt;=10,"Pass","Fail")</code></li></ul>')],
          [fill('Use the marks table. What does =SUM(B2:B3) give?', '{0}', [['20']], '12 + 8 = 20', visual=MARKS),
           fill('What does =MAX(B2:B5) give?', '{0}', [['15']]),
           fill('What does =AVERAGE(B3:B4) give?', '{0}', [['11.5', '11,5']], '(8 + 15) ÷ 2 = 11.5'),
           mcq('Which formula multiplies the price in B2 by the quantity in C2?', ['=B2*C2', '=B2xC2', 'B2*C2'], '=B2*C2', 'Use * to multiply, and start with =.'),
           match('Match the task to the function.', [('Total of all marks', 'SUM'), ('Mean mark', 'AVERAGE'), ('Highest mark', 'MAX'), ('Number of marks', 'COUNT')]),
           mcq('=IF(B3>=10,"Pass","Fail") with B3 = 8 shows…', ['Fail', 'Pass', '8'], 'Fail'),
           mcq('You copy =B2*C2 from D2 down to D3. What does D3 contain?', ['=B3*C3', '=B2*C2', '=B3*C2'], '=B3*C3', 'Relative references move with the formula.')]),

    38: L('Presentation software makes slide shows. Desktop publishing (DTP) software makes printed documents like flyers.',
          [('Presentation software',
            '<div class="chips"><span>PowerPoint</span><span>LibreOffice Impress</span><span>Google Slides</span></div><ul><li><b>Slide</b>: one page of a presentation</li><li><b>Layout</b>: where title, text and pictures go</li><li><b>Transition</b>: effect between slides</li><li><b>Animation</b>: effect on an object on a slide</li></ul>'),
           ('Desktop publishing',
            '<div class="chips"><span>Microsoft Publisher</span><span>Scribus</span><span>Canva</span></div><p>Used for <b>flyers, posters, newsletters, certificates, invitation cards</b>.</p><ul><li><b>Text box / frame</b>: holds text, you can move it anywhere</li><li><b>Template</b>: a ready-made design</li><li><b>Columns</b>, <b>master page</b> for repeated items</li></ul>'),
           ('Which one?',
            '<div class="two-col"><div><b>Presentation</b>to show on a screen while you speak</div><div><b>DTP</b>to print or share a designed page</div></div>')],
          [sort('Presentation or DTP software?', ['Presentation', 'DTP'], [('PowerPoint', 'Presentation'), ('Microsoft Publisher', 'DTP'), ('Google Slides', 'Presentation'), ('Scribus', 'DTP'), ('LibreOffice Impress', 'Presentation')]),
           match('Match the word to its meaning.', [('Slide', 'One page of a presentation'), ('Transition', 'Effect when moving to the next slide'), ('Animation', 'Effect on one object on a slide'), ('Template', 'A ready-made design')]),
           sort('Which software is best for the job?', ['Presentation', 'DTP'], [('A talk about your project in front of the class', 'Presentation'), ('A poster for the school fair', 'DTP'), ('A class newsletter', 'DTP'), ('Showing results at a meeting', 'Presentation')]),
           tf('A transition and an animation are the same thing.', False, 'A transition is between slides; an animation is on an object.')]),

    39: L('A good presentation is short, clear and easy to read from the back of the room.',
          [('Steps', '<ol><li>Plan: topic, audience, main points</li><li>Choose a simple theme</li><li>One idea per slide</li><li>Add pictures or charts</li><li>Rehearse with Slide Show (F5)</li></ol>'),
           ('The 6 × 6 rule', '<p>About <b>6 lines per slide</b> and <b>6 words per line</b>. Key words, not paragraphs.</p>'),
           ('Readable slides', '<ul><li>Font size ≥ 24</li><li>Dark text on light background (or the reverse)</li><li>Few animations</li><li>Title on every slide</li></ul><p class="wt-key">Slides support your talk: they do not replace it.</p>'),
           ('Useful views', '<ul><li><b>Normal</b>: edit</li><li><b>Slide sorter</b>: reorder slides</li><li><b>Notes</b>: what you will say</li><li><b>Slide show</b>: present</li></ul>')],
          [order('Put the steps in order.', ['Plan the topic and main points', 'Choose a theme', 'Create the slides', 'Add pictures and charts', 'Rehearse in slide show'], 'Plan first, rehearse last.'),
           sort('Good practice or bad practice?', ['Good', 'Bad'], [('One idea per slide', 'Good'), ('A full paragraph on each slide', 'Bad'), ('Font size 12', 'Bad'), ('Yellow text on white background', 'Bad'), ('A title on every slide', 'Good')]),
           mcq('Which view lets you drag slides into a new order?', ['Slide sorter', 'Slide show', 'Notes'], 'Slide sorter'),
           mcq('Which key starts the slide show in PowerPoint?', ['F5', 'F1', 'Esc'], 'F5'),
           tf('You should read every word on your slides to the audience.', False, 'Use slides as key points and speak in your own words.')]),

    40: L('With DTP software you design pages like flyers by placing text boxes and pictures freely.',
          [('Making a flyer', '<ol><li>Choose page size and orientation (A4, A5)</li><li>Pick a template or a blank page</li><li>Insert <b>text boxes</b>: title, details, contact</li><li>Insert pictures and the logo</li><li>Arrange, align, choose colours</li><li>Check spelling, then print or export as PDF</li></ol>'),
           ('Design rules', '<ul><li><b>Hierarchy</b>: big title, smaller details</li><li><b>Alignment</b>: line elements up</li><li><b>Contrast</b>: readable colours</li><li><b>White space</b>: do not fill every corner</li><li>2 fonts maximum</li></ul>'),
           ('What a flyer needs', '<p><b>What?</b> (event) · <b>When?</b> (date, time) · <b>Where?</b> (place) · <b>Contact</b></p><p class="wt-key">If a reader can\'t find the date in 3 seconds, the design needs work.</p>')],
          [order('Put the steps to make a flyer in order.', ['Choose page size', 'Pick a template', 'Insert text boxes and pictures', 'Arrange and align', 'Check spelling', 'Print or export as PDF']),
           sort('A flyer for a school fair: needed or not?', ['Needed', 'Not needed'], [('Date and time', 'Needed'), ('Place', 'Needed'), ('Name of the event', 'Needed'), ('Your password', 'Not needed'), ('Contact number', 'Needed')]),
           match('Match the design rule to its meaning.', [('Hierarchy', 'Most important text is biggest'), ('Alignment', 'Elements are lined up'), ('Contrast', 'Text stands out from the background'), ('White space', 'Empty space so the page can breathe')]),
           mcq('In DTP software, text is placed in…', ['text boxes (frames)', 'cells', 'slides'], 'text boxes (frames)'),
           tf('Using 6 different fonts makes a flyer look more professional.', False, 'Use 2 fonts maximum.')]),

    42: L('Authentication means proving you are really who you say you are before you get access.',
          [('Authentication factors',
            table(['Factor', 'Examples'], [['Something you know', 'password, PIN, pattern'], ['Something you have', 'phone (SMS code), bank card'], ['Something you are', 'fingerprint, face, voice']])),
           ('Two-factor authentication (2FA)', '<p>Uses <b>two different factors</b>: a password + a code sent to your phone. A thief who has your password still cannot enter.</p>'),
           ('Authentication vs authorisation', '<div class="two-col"><div><b>Authentication</b>Who are you? (login)</div><div><b>Authorisation</b>What can you do? (permissions)</div></div>'),
           ('Strong passwords', '<ul><li>At least 12 characters</li><li>Mix letters, numbers, symbols</li><li>A different password for each account</li><li>A passphrase is easy to remember: <i>Mango-Rain-Drum-27!</i></li></ul>')],
          [sort('Which factor is it?', ['Know', 'Have', 'Are'], [('PIN code', 'Know'), ('Fingerprint', 'Are'), ('Code sent by SMS', 'Have'), ('Face recognition', 'Are'), ('Password', 'Know'), ('Bank card', 'Have')]),
           mcq('Which is two-factor authentication?', ['Password + code sent to your phone', 'Password + another password', 'Username only'], 'Password + code sent to your phone', 'Two different types of factor.'),
           match('Authentication or authorisation?', [('Typing your password to log in', 'Authentication'), ('A student account cannot delete teacher files', 'Authorisation')]),
           mcq('Which password is strongest?', ['Drum-Mango-Rain-27!', 'awa2010', 'qwerty'], 'Drum-Mango-Rain-27!'),
           tf('Using fingerprint to unlock a phone is authentication by "something you are".', True)]),

    43: L('A backup is a copy of your data that you keep safe, so you can restore it if the original is lost.',
          [('Why back up?', '<p>Data can be lost by: <b>hardware failure</b>, <b>theft</b>, <b>virus / ransomware</b>, <b>accidental deletion</b>, <b>fire or water</b>.</p>'),
           ('Where to back up', '<ul><li>External hard disk or flash drive</li><li>Cloud storage (Google Drive, OneDrive)</li><li>Another computer</li></ul>'),
           ('Types of backup', table(['Type', 'Copies'], [['Full', 'everything, every time'], ['Incremental', 'only what changed since the last backup'], ['Differential', 'what changed since the last full backup']])),
           ('The 3-2-1 rule', BACKUP321 + '<p class="wt-key">A backup only helps if you can <b>restore</b> it: test it sometimes.</p>')],
          [sort('Can it cause data loss?', ['Yes', 'No'], [('Hard disk failure', 'Yes'), ('Phone stolen', 'Yes'), ('Ransomware', 'Yes'), ('Changing your wallpaper', 'No'), ('Deleting a file by mistake', 'Yes')]),
           match('Match the backup type to what it copies.', [('Full', 'Everything, every time'), ('Incremental', 'Only changes since the last backup'), ('Differential', 'Changes since the last full backup')]),
           fill('Complete the 3-2-1 rule.', '{0} copies, on {1} different media, {2} copy kept off-site.', [['3', 'three'], ['2', 'two'], ['1', 'one']]),
           mcq('Your laptop is stolen. Which backup saves your work best?', ['A copy in the cloud', 'A copy on the same laptop', 'No backup'], 'A copy in the cloud', 'A backup must be kept somewhere else.'),
           tf('Restoring means getting your data back from a backup.', True)]),

    45: L('Communication tools let us exchange messages. Collaboration tools let us work together on the same thing.',
          [('Communication tools', '<div class="chips"><span>Email</span><span>Chat (WhatsApp, Telegram)</span><span>Video calls (Meet, Zoom)</span><span>SMS</span></div>'),
           ('Collaboration tools', '<ul><li><b>Shared documents</b>: Google Docs, Microsoft 365 — several people edit at once</li><li><b>Shared folders</b>: Google Drive, OneDrive</li><li><b>Shared calendars</b> and task boards</li></ul>'),
           ('Synchronous or asynchronous', '<div class="two-col"><div><b>Synchronous</b>at the same time: video call, live chat</div><div><b>Asynchronous</b>reply later: email, forum, shared doc comments</div></div>'),
           ('Working well together', '<p class="wt-key">Be polite, reply on time, name files clearly and never edit someone else\'s part without asking.</p>')],
          [sort('Communication or collaboration?', ['Communication', 'Collaboration'], [('Sending an email', 'Communication'), ('Five students editing one Google Doc', 'Collaboration'), ('A WhatsApp voice note', 'Communication'), ('A shared Drive folder for a project', 'Collaboration')]),
           sort('Synchronous or asynchronous?', ['Synchronous', 'Asynchronous'], [('Video call', 'Synchronous'), ('Email', 'Asynchronous'), ('Phone call', 'Synchronous'), ('Comment on a shared document', 'Asynchronous')]),
           mcq('Your group must write one report together from different homes. Best tool?', ['A shared online document', 'A printed paper', 'An SMS'], 'A shared online document'),
           tf('In a shared document, several people can edit at the same time.', True)]),

    46: L('Email sends messages and files to an email address. Know its parts and write it politely.',
          [('An email address', '<p><b>awa.ngum</b>@<b>gmail.com</b> → username @ domain</p>'),
           ('Parts of an email', EMAIL +
            '<ol><li><b>To</b>: main receiver</li><li><b>Cc</b>: copy to someone else (everyone sees)</li><li><b>Subject</b>: short title</li><li><b>Body</b>: the message</li><li><b>Attachment</b>: a file sent with it</li></ol><p><b>Bcc</b>: hidden copy (others can\'t see that address).</p>'),
           ('Reply, reply all, forward', '<ul><li><b>Reply</b>: only the sender</li><li><b>Reply all</b>: everyone in the email</li><li><b>Forward</b>: send it to a new person</li></ul>'),
           ('Email etiquette', '<ul><li>Clear subject</li><li>Greeting and polite closing</li><li>No ALL CAPITALS (it means shouting)</li><li>Check before you send</li><li>Don\'t open attachments from strangers (phishing)</li></ul>')],
          [label('Name the parts of the email.', EMAIL, ['To', 'Cc', 'Subject', 'Body', 'Attachment']),
           match('Match the button to what it does.', [('Reply', 'Answers only the sender'), ('Reply all', 'Answers everyone in the email'), ('Forward', 'Sends the email to a new person')]),
           mcq('In paul.mbah@yahoo.com, what is the domain?', ['yahoo.com', 'paul.mbah', '@'], 'yahoo.com'),
           mcq('You want to send a copy to your parent without other receivers seeing their address. Use…', ['Bcc', 'Cc', 'Subject'], 'Bcc'),
           sort('Good or bad email practice?', ['Good', 'Bad'], [('A clear subject line', 'Good'), ('WRITING EVERYTHING IN CAPITALS', 'Bad'), ('Starting with "Good morning Sir"', 'Good'), ('Opening an attachment from an unknown sender', 'Bad')]),
           tf('Bcc stands for "blind carbon copy".', True)]),

    47: L('Chat tools send instant messages, voice notes and files. Use them safely and respectfully.',
          [('Examples and features', '<div class="chips"><span>WhatsApp</span><span>Telegram</span><span>Messenger</span></div><ul><li>Text, voice notes, photos, documents</li><li><b>Groups</b> with admins</li><li><b>Status</b> / stories</li><li>Read receipts (✓✓)</li></ul>'),
           ('Privacy and security', '<ul><li><b>End-to-end encryption</b>: only you and the receiver can read</li><li>Turn on two-step verification</li><li>Never share the 6-digit code you receive</li><li>Choose who can add you to groups</li></ul>'),
           ('Fake news in groups', '<p>Many false messages spread in groups ("Forwarded many times"). <b>Check before you forward.</b></p>'),
           ('Chat etiquette', '<p class="wt-key">Stay on topic in class groups, no insults, respect people\'s time (no messages at midnight), ask before posting someone\'s photo.</p>')],
          [sort('Good or bad in a class WhatsApp group?', ['Good', 'Bad'], [('Sharing the homework instructions', 'Good'), ('Forwarding a scary message without checking', 'Bad'), ('Posting a classmate\'s photo to mock them', 'Bad'), ('Asking a question about the lesson', 'Good')]),
           mcq('End-to-end encryption means…', ['only the sender and receiver can read the message', 'messages are deleted after one day', 'everyone can read the message'], 'only the sender and receiver can read the message'),
           mcq('A message says "Forward to 10 groups or your account will be closed". What do you do?', ['Ignore it: it is fake', 'Forward it quickly', 'Send your code'], 'Ignore it: it is fake'),
           tf('You should share the 6-digit WhatsApp code with anyone who asks.', False, 'That code lets someone take over your account.')]),

    48: L('A videoconference lets people see and hear each other live from different places.',
          [('Tools', '<div class="chips"><span>Google Meet</span><span>Zoom</span><span>Microsoft Teams</span><span>WhatsApp video</span></div>'),
           ('What you need', '<ul><li>A device with <b>camera</b>, <b>microphone</b>, speaker</li><li>A good internet connection</li><li>The <b>meeting link</b> or ID (and passcode)</li></ul>'),
           ('Main controls', table(['Control', 'Use'], [['🎤 Mute', 'turn your microphone off'], ['📷 Camera', 'turn video on / off'], ['🖥 Share screen', 'show your screen'], ['💬 Chat', 'type messages'], ['✋ Raise hand', 'ask to speak'], ['📞 Leave', 'end your participation']])),
           ('Etiquette', '<ul><li>Join on time</li><li>Mute when not speaking</li><li>Quiet place, good light</li><li>Raise your hand to speak</li></ul><p class="wt-key">The <b>host</b> starts the meeting and controls who joins.</p>')],
          [match('Match the control to its use.', [('Mute', 'Turn your microphone off'), ('Share screen', 'Show your screen to others'), ('Raise hand', 'Ask to speak'), ('Chat', 'Type a message during the meeting')]),
           sort('Needed for a video meeting?', ['Needed', 'Not needed'], [('Microphone', 'Needed'), ('Meeting link', 'Needed'), ('Internet connection', 'Needed'), ('A printer', 'Not needed')]),
           mcq('There is noise around you while the teacher speaks. What do you do?', ['Mute your microphone', 'Turn the volume up', 'Share your screen'], 'Mute your microphone'),
           mcq('Who controls who can join the meeting?', ['The host', 'Any participant', 'The internet provider'], 'The host'),
           tf('A videoconference is synchronous communication.', True)]),

    50: L('Maintenance keeps a computer working well. Prevent problems first, repair when needed.',
          [('Two types', '<div class="two-col"><div><b>Preventive</b>stop problems before they happen: cleaning, updates, antivirus</div><div><b>Corrective</b>fix a problem after it happens: replace a part, remove a virus</div></div>'),
           ('Preventive tasks', '<ul><li>Clean dust (blower) and screen (soft cloth)</li><li>Use a surge protector / UPS (power cuts!)</li><li>Update the OS and antivirus</li><li>Disk cleanup, back up data</li><li>Keep food and drinks away</li></ul>'),
           ('Tools', '<div class="chips"><span>Screwdriver set</span><span>Air blower</span><span>Anti-static wrist strap</span><span>Soft cloth</span><span>Multimeter</span></div>'),
           ('Safety first', '<p class="wt-key">Switch off and unplug before opening a computer. Wear an anti-static wrist strap.</p>')],
          [sort('Preventive or corrective?', ['Preventive', 'Corrective'], [('Cleaning dust from the fan', 'Preventive'), ('Replacing a broken keyboard', 'Corrective'), ('Updating the antivirus', 'Preventive'), ('Removing a virus that infected the PC', 'Corrective'), ('Using a UPS', 'Preventive')]),
           match('Match the tool to its use.', [('Air blower', 'Removes dust'), ('Anti-static wrist strap', 'Protects parts from static electricity'), ('Screwdriver', 'Opens the case'), ('UPS', 'Keeps power during a cut')]),
           mcq('What must you do first before opening a computer?', ['Switch off and unplug it', 'Turn the volume up', 'Open a browser'], 'Switch off and unplug it'),
           tf('Drinking near the keyboard is good maintenance practice.', False)]),

    51: L('Most hardware problems have simple causes. Check the easy things first.',
          [('Common problems', table(['Problem', 'Possible cause', 'Fix'], [['No power', 'cable unplugged, faulty socket', 'check cable and socket'], ['No display', 'monitor cable loose, monitor off', 'check cable, switch on'], ['Overheating', 'dust, blocked fan', 'clean fan, free the vents'], ['Keyboard / mouse not working', 'loose cable, flat battery', 'reconnect, change battery'], ['Strange noise', 'failing fan or hard disk', 'back up, replace part']])),
           ('Beep codes', '<p>At start-up, the computer may <b>beep</b> to report a problem (often RAM). Check the manual for the meaning.</p>'),
           ('Troubleshooting steps', flow(['Identify the problem', 'Check simple causes', 'Test a fix', 'Check it works', 'Record it']) +
            '<p class="wt-key">Check the cable before you open the computer!</p>')],
          [match('Match the problem to its likely cause.', [('Computer shuts down when hot', 'Dust in the fan'), ('Nothing happens when you press power', 'Cable not plugged in'), ('Wireless mouse not moving', 'Flat battery'), ('Screen stays black, PC on', 'Monitor cable loose')]),
           order('Put the troubleshooting steps in order.', ['Identify the problem', 'Check the simple causes', 'Try a fix', 'Check that it works', 'Record what you did']),
           mcq('The computer makes repeated beeps at start-up and shows nothing. A common cause is…', ['RAM problem', 'Too many files', 'Wrong wallpaper'], 'RAM problem'),
           mcq('A laptop gets very hot and the fan is loud. What first?', ['Clean the vents and fan', 'Buy a new laptop', 'Install a game'], 'Clean the vents and fan'),
           tf('A strange clicking noise from the hard disk means you should back up your data quickly.', True, 'The disk may be failing.')]),

    52: L('Software problems make the computer slow, freeze or show errors. Most can be fixed without opening it.',
          [('Common problems', table(['Problem', 'Possible cause', 'Fix'], [['Very slow', 'too many programs, full disk, malware', 'close apps, disk cleanup, scan'], ['Program frozen', 'program error', 'Task Manager → End task'], ['Pop-ups, strange behaviour', 'virus / malware', 'run antivirus'], ['Program won\'t open', 'corrupted install', 'reinstall it'], ['Device not working', 'missing driver', 'install / update driver'], ['Blue screen', 'driver or system error', 'restart, update, get help']])),
           ('Task Manager', '<p>Press <b>Ctrl + Shift + Esc</b> (or Ctrl + Alt + Del). See what uses the CPU and memory, and end a frozen program.</p>'),
           ('Golden rules', '<ul><li>Try <b>restarting</b> first</li><li>Keep the system <b>updated</b></li><li>Only install software from trusted sources</li></ul><p class="wt-key">Restart · Update · Scan · Reinstall</p>')],
          [match('Match the problem to the best fix.', [('A program is frozen', 'End it in Task Manager'), ('Many pop-up adverts appear', 'Run the antivirus'), ('New printer not working', 'Install its driver'), ('Disk is full and PC is slow', 'Disk cleanup')]),
           mcq('Which keys open Task Manager in Windows?', ['Ctrl + Shift + Esc', 'Ctrl + C', 'Alt + F4'], 'Ctrl + Shift + Esc'),
           sort('Hardware or software problem?', ['Hardware', 'Software'], [('Broken screen', 'Hardware'), ('Virus', 'Software'), ('Program crashes when opened', 'Software'), ('Fan is not turning', 'Hardware'), ('Missing driver', 'Software')]),
           mcq('What should you usually try first?', ['Restart the computer', 'Format the disk', 'Buy new RAM'], 'Restart the computer'),
           tf('Installing software from unknown websites can bring malware.', True)]),

    54: L('Not everything online is true. Check who wrote it, when, and whether others confirm it.',
          [('Check the source', '<ul><li><b>Who</b> wrote it? Is the author or organisation known and expert?</li><li><b>When</b>? Is it recent?</li><li><b>Where</b>? Official sites (.gov, ministry, university, known newspapers) are more reliable</li></ul>'),
           ('Check the content', '<ul><li>Are there <b>evidence</b> and sources?</li><li>Do <b>other trusted sites</b> say the same?</li><li>Is it trying to make you angry or scared? (clickbait)</li><li>Spelling mistakes, shocking title, "share before it is deleted!"</li></ul>'),
           ('Images can lie', '<p>Photos can be old, edited or AI-made. A <b>reverse image search</b> shows where a picture first appeared.</p>'),
           ('Remember', '<p class="wt-key">Stop · Check · Then share.</p>')],
          [sort('Reliable or suspicious?', ['Reliable', 'Suspicious'], [('A ministry website with the date and author', 'Reliable'), ('"Share before it is deleted!!!"', 'Suspicious'), ('An article confirmed by several newspapers', 'Reliable'), ('A message with no author and many spelling errors', 'Suspicious')]),
           order('Put the steps in order before sharing information.', ['Stop: do not share immediately', 'Check the author and date', 'Compare with other trusted sources', 'Share only if it is true']),
           mcq('You see a shocking photo. How can you find where it first appeared?', ['Reverse image search', 'Make it bigger', 'Forward it to friends'], 'Reverse image search'),
           mcq('Which source is most reliable for school exam dates?', ['The official ministry website', 'A random WhatsApp forward', 'An anonymous TikTok video'], 'The official ministry website'),
           tf('If many people share a message, it must be true.', False, 'False information often spreads faster than the truth.')]),
}
