"""Form 5 Mathematics: Euclidean geometry and solid figures (lessons 27-45)."""
from helpers import *
from f3_maths_part1 import table

PARALLEL = svg(420, 200, ''.join([
    '<line x1="20" y1="60" x2="400" y2="60" class="v-line" style="stroke-width:2"/>',
    '<line x1="20" y1="150" x2="400" y2="150" class="v-line" style="stroke-width:2"/>',
    '<line x1="120" y1="190" x2="300" y2="15" class="v-line" style="stroke-width:2"/>',
    '<text x="250" y="52" class="v-t">a</text><text x="268" y="80" class="v-t">b</text>',
    '<text x="145" y="142" class="v-t">c</text><text x="168" y="172" class="v-t">d</text>',
    '<text x="380" y="52" class="v-s">→</text><text x="380" y="142" class="v-s">→</text>',
]), 'Parallel lines and a transversal')

SEMI = svg(300, 220, ''.join([
    '<circle cx="150" cy="115" r="95" class="v-line" style="fill:none;stroke-width:2"/>',
    '<polygon points="55,115 245,115 110,29" class="v-box" style="fill-opacity:.5"/>',
    '<circle cx="150" cy="115" r="4" class="v-mk"/><text x="150" y="135" text-anchor="middle" class="v-s">O (centre)</text>',
    '<text x="40" y="120" class="v-t">A</text><text x="250" y="120" class="v-t">B</text><text x="100" y="22" class="v-t">C</text>',
    '<text x="114" y="50" class="v-s">90°</text>',
]), 'Right triangle in a semicircle')

QUAD = table(['Quadrilateral', 'Key properties'], [
    ['Parallelogram', 'opposite sides parallel and equal; diagonals bisect each other'],
    ['Rectangle', 'parallelogram + 4 right angles; diagonals equal'],
    ['Rhombus', 'parallelogram + 4 equal sides; diagonals perpendicular'],
    ['Square', 'rectangle + rhombus'],
    ['Trapezium', 'one pair of parallel sides'],
    ['Kite', 'two pairs of adjacent equal sides; diagonals perpendicular']])

LESSONS = {
    27: L('Know the angle facts: triangles, straight lines, and parallel lines cut by a transversal.',
          [('Basic facts', '<ul><li>Angles on a straight line add to 180°</li><li>Angles around a point add to 360°</li><li>Vertically opposite angles are equal</li><li>Angles in a triangle add to 180°</li><li>Exterior angle of a triangle = sum of the two opposite interior angles</li></ul>'),
           ('Parallel lines', PARALLEL + '<ul><li><b>Corresponding</b> angles are equal (a and c)</li><li><b>Alternate</b> angles are equal (b and c)</li><li><b>Co-interior</b> angles (between the lines, on the same side) add to 180°</li></ul>'),
           ('Triangles', '<p>Equilateral (3 equal sides, 60° each) · Isosceles (2 equal sides, 2 equal base angles) · Scalene · Right-angled</p>')],
          [fill('Two angles of a triangle are 50° and 70°.', 'Third angle = {0}°', [['60']]),
           fill('An isosceles triangle has apex angle 40°.', 'Each base angle = {0}°', [['70']]),
           fill('A triangle has interior angles 45° and 65°.', 'The exterior angle at the third vertex = {0}°', [['110']]),
           match('Match the angle pair to its rule.', [('Corresponding angles', 'Equal'), ('Co-interior angles', 'Add to 180°'), ('Angles around a point', 'Add to 360°')]),
           tf('Alternate angles between parallel lines are equal.', True)]),

    28: L('The hypotenuse of a right-angled triangle is a diameter of its circumscribed circle.',
          [('The property', SEMI + '<p class="wt-key">Centre of the circle = midpoint of the hypotenuse · radius = hypotenuse ÷ 2</p>'),
           ('Converse', '<p>Angle in a semicircle: any triangle drawn on a diameter AB with C on the circle has ∠ACB = 90°.</p>'),
           ('Median', '<p>The median from the right angle to the hypotenuse equals half the hypotenuse.</p>')],
          [fill('A right-angled triangle has sides 6, 8, 10.', 'Radius of the circumscribed circle = {0}', [['5']]),
           fill('Legs 5 and 12.', 'Hypotenuse = {0}, radius = {1}', [['13'], ['6.5']]),
           mcq('The centre of the circle through the 3 vertices of a right triangle is…', ['the midpoint of the hypotenuse', 'the right-angle vertex', 'outside the triangle'], 'the midpoint of the hypotenuse'),
           tf('An angle in a semicircle is a right angle.', True)]),

    29: L('Interior angles of an n-sided polygon add up to (n − 2) × 180°. Exterior angles always add up to 360°.',
          [('Formulas', '<p class="wt-key">Sum of interior angles = (n − 2) × 180°</p><p class="wt-key">Sum of exterior angles = 360°</p>'),
           ('Regular polygons', '<p>Each exterior angle = 360° ÷ n · each interior angle = 180° − exterior</p><p>Hexagon: exterior 60°, interior 120°, sum 720°.</p>'),
           ('Finding n', '<p>Exterior angle 24° → n = 360 ÷ 24 = <b>15 sides</b>.</p>')],
          [fill('Sum of interior angles of a pentagon.', '{0}°', [['540']]),
           fill('Regular octagon.', 'Exterior = {0}°, interior = {1}°', [['45'], ['135']]),
           fill('A regular polygon has exterior angles of 30°.', 'n = {0}', [['12']]),
           fill('A regular polygon has interior angles of 140°.', 'n = {0}', [['9']], 'Exterior = 40°, 360 ÷ 40 = 9'),
           tf('The exterior angles of any convex polygon add up to 360°.', True)]),

    30: L('A figure has point symmetry if it looks the same after a half-turn (180°) about its centre.',
          [('Point symmetry', '<p>Every point P has a partner P\' so that the centre O is the midpoint of PP\'.</p>'),
           ('Examples', '<div class="two-col"><div><b>Yes</b>parallelogram, rectangle, rhombus, square, circle, letters S, N, Z, H</div><div><b>No</b>equilateral triangle, kite, isosceles trapezium, letters A, T, E</div></div>'),
           ('Centre', '<p>For a parallelogram, the centre of symmetry is where the diagonals cross.</p>')],
          [sort('Point symmetry?', ['Yes', 'No'], [('Parallelogram', 'Yes'), ('Equilateral triangle', 'No'), ('Letter S', 'Yes'), ('Kite', 'No'), ('Circle', 'Yes'), ('Letter A', 'No')]),
           mcq('The centre of symmetry of a rectangle is…', ['the intersection of its diagonals', 'a vertex', 'the midpoint of one side'], 'the intersection of its diagonals'),
           tf('A figure with point symmetry looks exactly the same after a half-turn about its centre.', True)]),

    31: L('A line of symmetry divides a figure into two mirror images.',
          [('Number of lines', table(['Figure', 'Lines'], [['Square', '4'], ['Rectangle', '2'], ['Rhombus', '2'], ['Equilateral triangle', '3'], ['Isosceles triangle', '1'], ['Kite', '1'], ['Parallelogram', '0'], ['Regular hexagon', '6'], ['Circle', 'infinitely many']])),
           ('Test', '<p>Fold along the line: both halves must match exactly.</p><p class="wt-key">Regular n-gon → n lines of symmetry.</p>')],
          [fill('Lines of symmetry of a square.', '{0}', [['4']]),
           fill('Lines of symmetry of a regular pentagon.', '{0}', [['5']]),
           fill('Lines of symmetry of a parallelogram (not a rectangle or rhombus).', '{0}', [['0']]),
           match('Match the figure to its number of lines of symmetry.', [('Kite', '1'), ('Rectangle', '2'), ('Equilateral triangle', '3'), ('Regular hexagon', '6')])]),

    32: L('Symmetry explains many properties: equal sides, equal angles and perpendicular diagonals.',
          [('Order of rotational symmetry', table(['Figure', 'Order'], [['Square', '4'], ['Rectangle', '2'], ['Equilateral triangle', '3'], ['Parallelogram', '2'], ['Kite', '1'], ['Regular n-gon', 'n']])),
           ('Using symmetry', '<ul><li>Isosceles triangle: its axis bisects the apex angle and is the perpendicular bisector of the base</li><li>Kite: its axis is a diagonal, which bisects the other diagonal at 90°</li><li>Rhombus: both diagonals are axes → they are perpendicular</li></ul>')],
          [fill('Order of rotational symmetry of a square.', '{0}', [['4']]),
           fill('Order of rotational symmetry of a regular octagon.', '{0}', [['8']]),
           mcq('Why are the base angles of an isosceles triangle equal?', ['The axis of symmetry swaps them', 'All triangles have equal angles', 'Because of parallel lines'], 'The axis of symmetry swaps them'),
           tf('A kite has rotational symmetry of order 2.', False, 'Order 1: it only fits after a full turn.')]),

    33: L('Quadrilaterals have 4 sides and angles adding to 360°. Each family has its own properties.',
          [('Families', QUAD),
           ('Angle sum', '<p class="wt-key">Angles of any quadrilateral add up to 360°.</p>')],
          [fill('Three angles of a quadrilateral are 90°, 85° and 100°.', 'Fourth angle = {0}°', [['85']]),
           match('Which quadrilateral?', [('Diagonals equal, all angles 90°, sides not all equal', 'Rectangle'), ('4 equal sides, angles not 90°', 'Rhombus'), ('Only one pair of parallel sides', 'Trapezium'), ('Two pairs of adjacent equal sides', 'Kite')]),
           tf('Every square is a rhombus.', True),
           tf('Every rectangle is a square.', False),
           mcq('In which quadrilateral do the diagonals bisect each other at right angles?', ['Rhombus', 'Rectangle', 'Trapezium'], 'Rhombus')]),

    34: L('Learn the area formula for each quadrilateral.',
          [('Formulas', table(['Shape', 'Area'], [['Rectangle', 'length × width'], ['Square', 'side²'], ['Parallelogram', 'base × perpendicular height'], ['Trapezium', '½ (a + b) × h'], ['Rhombus / kite', '½ × d₁ × d₂']])),
           ('Example', '<p>Trapezium with parallel sides 6 and 10, height 4: ½(6 + 10) × 4 = <b>32</b></p>')],
          [fill('Parallelogram: base 9 cm, height 5 cm.', 'Area = {0} cm²', [['45']]),
           fill('Trapezium: parallel sides 7 and 11, height 6.', 'Area = {0}', [['54']]),
           fill('Rhombus with diagonals 8 and 12.', 'Area = {0}', [['48']]),
           fill('A square has area 49 cm².', 'Side = {0} cm', [['7']]),
           mcq('For a parallelogram, the height is…', ['perpendicular to the base', 'the slanted side', 'the diagonal'], 'perpendicular to the base')]),

    35: L('A net is a flat shape that folds into a solid. A cuboid\'s net has 6 rectangles; a triangular prism\'s has 2 triangles and 3 rectangles.',
          [('Cuboid', '<p>6 rectangular faces in 3 equal pairs. A cube has 6 equal squares (there are 11 different cube nets).</p>'),
           ('Prism', '<p>Two identical end faces (the cross-section) + rectangles joining them. A triangular prism: 2 triangles + 3 rectangles.</p>'),
           ('Faces, edges, vertices', table(['Solid', 'F', 'E', 'V'], [['Cuboid', '6', '12', '8'], ['Triangular prism', '5', '9', '6']]) + '<p class="wt-key">Euler: F + V − E = 2</p>')],
          [fill('Faces of a triangular prism.', '{0}', [['5']]),
           fill('Edges of a cuboid.', '{0}', [['12']]),
           fill('A pentagonal prism has F = 7 and V = 10.', 'E = {0}', [['15']], 'F + V − E = 2 → E = 15'),
           mcq('The net of a triangular prism has…', ['2 triangles and 3 rectangles', '3 triangles and 2 rectangles', '6 squares'], '2 triangles and 3 rectangles')]),

    36: L('Surface area = total area of all faces. Cuboid: 2(lw + lh + wh).',
          [('Cuboid', '<p class="wt-key">SA = 2(lw + lh + wh)</p><p>5 × 4 × 3: 2(20 + 15 + 12) = <b>94</b></p>'),
           ('Prism', '<p>SA = 2 × cross-section + perimeter of cross-section × length</p>'),
           ('Open boxes', '<p>A box without a lid: remove one face (usually l × w).</p>')],
          [fill('Cube of side 3 cm.', 'SA = {0} cm²', [['54']]),
           fill('Cuboid 6 × 4 × 2.', 'SA = {0}', [['88']]),
           fill('Open box (no lid) 10 × 5 × 4 cm.', 'SA = {0} cm²', [['170']], '50 + 2(40) + 2(20) = 170'),
           fill('Triangular prism: right triangle 3, 4, 5; length 8.', 'SA = {0}', [['108']], '2 × 6 + 12 × 8 = 108')]),

    37: L('Volume of a prism = cross-section area × length. Cuboid: l × w × h. 1 litre = 1000 cm³.',
          [('Formulas', '<p class="wt-key">V = A × l · cuboid V = lwh</p>'),
           ('Units', '<p>1 L = 1000 cm³ · 1 m³ = 1000 L</p><p>A tank 2 m × 1 m × 1.5 m holds 3 m³ = <b>3000 L</b>.</p>')],
          [fill('Cuboid 8 × 5 × 3 cm.', 'V = {0} cm³', [['120']]),
           fill('A tank 50 cm × 40 cm × 30 cm.', 'V = {0} cm³ = {1} litres', [['60000'], ['60']]),
           fill('Prism with cross-section 12 cm² and length 9 cm.', 'V = {0} cm³', [['108']]),
           fill('A cube has volume 64 cm³.', 'Side = {0} cm', [['4']])]),

    38: L('A cylinder\'s surface: two circles and a curved rectangle. Total SA = 2πr² + 2πrh.',
          [('Formulas', table(['Part', 'Area'], [['Curved surface', '2πrh'], ['Two ends', '2πr²'], ['Total (closed)', '2πr(r + h)'], ['Open at one end', 'πr² + 2πrh']])),
           ('Example', '<p>r = 7 cm, h = 10 cm, π = 22/7: curved = 2 × 22/7 × 7 × 10 = <b>440 cm²</b></p>')],
          [fill('r = 3, h = 5. In terms of π.', 'Total SA = {0}', [['48π', '48pi']]),
           fill('r = 7, h = 10, π = 22/7.', 'Total SA = {0} cm²', [['748']], '440 + 2 × 154 = 748'),
           fill('An open tin (no lid): r = 5, h = 8. In terms of π.', 'SA = {0}', [['105π', '105pi']], '25π + 80π'),
           mcq('The label around a tin covers the…', ['curved surface 2πrh', 'two ends', 'whole surface'], 'curved surface 2πrh')]),

    39: L('Volume of a cylinder = πr²h.',
          [('Formula', '<p class="wt-key">V = πr²h</p><p>r = 7 cm, h = 10 cm, π = 22/7: V = 22/7 × 49 × 10 = <b>1540 cm³ = 1.54 L</b></p>'),
           ('Problems', '<p>Water in a tank of radius 1 m rises by 0.5 m: volume added = π × 1² × 0.5 ≈ <b>1.57 m³</b>.</p>')],
          [fill('r = 3, h = 4. In terms of π.', 'V = {0}', [['36π', '36pi']]),
           fill('r = 14 cm, h = 5 cm, π = 22/7.', 'V = {0} cm³', [['3080']]),
           fill('V = 100π, r = 5.', 'h = {0}', [['4']]),
           mcq('Doubling the radius (same height) multiplies the volume by…', ['4', '2', '8'], '4')]),

    40: L('Curved surface area of a cone = πrl, where l is the slant height. Total = πr² + πrl.',
          [('Formulas', '<p class="wt-key">l = √(r² + h²) · curved SA = πrl · total = πr(r + l)</p>'),
           ('Example', '<p>r = 5, h = 12 → l = 13 · curved = 65π · total = 25π + 65π = <b>90π</b></p>'),
           ('From a sector', '<p>A sector of radius l folds into a cone: the arc length becomes the base circumference 2πr.</p>')],
          [fill('r = 3, h = 4.', 'l = {0}, curved SA = {1}π', [['5'], ['15']]),
           fill('r = 6, l = 10. In terms of π.', 'Total SA = {0}', [['96π', '96pi']]),
           fill('A sector with arc length 10π makes a cone.', 'Base radius r = {0}', [['5']]),
           tf('The slant height is longer than the vertical height.', True)]),

    41: L('Volume of a cone = (1/3)πr²h: one third of the cylinder with the same base and height.',
          [('Formula', '<p class="wt-key">V = (1/3)πr²h</p><p>r = 3, h = 4: V = (1/3)π × 9 × 4 = <b>12π</b></p>'),
           ('Finding h', '<p>If you are given l, first find h = √(l² − r²).</p>')],
          [fill('r = 6, h = 5. In terms of π.', 'V = {0}', [['60π', '60pi']]),
           fill('r = 5, l = 13.', 'h = {0}, V = {1}π', [['12'], ['100']]),
           fill('A cone and a cylinder have the same base and height. The cylinder holds 3 L.', 'The cone holds {0} L', [['1']]),
           mcq('An ice-cream cone has r = 3 cm, h = 10 cm. Volume (π ≈ 3.14)?', ['94.2 cm³', '282.6 cm³', '31.4 cm³'], '94.2 cm³')]),

    42: L('A frustum of a cone: curved SA = π(R + r)l. Volume = big cone − small cone, or (1/3)πh(R² + Rr + r²).',
          [('Formulas', table(['', 'Formula'], [['Curved area', 'π(R + r)l'], ['Total (closed)', 'π(R + r)l + πR² + πr²'], ['Volume', '(1/3)πh(R² + Rr + r²)']])),
           ('Example', '<p>R = 6, r = 3, h = 4 → l = √(4² + 3²) = 5</p><p>Curved = π × 9 × 5 = 45π · Total = 45π + 36π + 9π = <b>90π</b></p><p>Volume = (1/3)π × 4 × (36 + 18 + 9) = <b>84π</b></p>')],
          [fill('R = 5, r = 2, h = 4.', 'Slant height l = {0}', [['5']], '√(4² + 3²)'),
           fill('R = 5, r = 2, l = 5. In terms of π.', 'Curved SA = {0}', [['35π', '35pi']]),
           fill('R = 5, r = 2, h = 4. In terms of π.', 'V = {0}', [['52π', '52pi']], '(1/3) × 4 × (25 + 10 + 4) = 52'),
           mcq('A bucket is open at the top. Its outside surface is…', ['curved area + small base', 'curved area + both bases', 'curved area only'], 'curved area + small base')]),

    43: L('Pyramid: V = (1/3) × base area × height. Surface area = base + triangular faces.',
          [('Volume', '<p class="wt-key">V = (1/3)Ah</p><p>Rectangular base 6 × 4, h = 9: V = (1/3) × 24 × 9 = <b>72</b></p>'),
           ('Surface area', '<p>Square base 10, height 12 → slant height of a face = √(12² + 5²) = 13 → 4 faces = 4 × ½ × 10 × 13 = 260 → total = 100 + 260 = <b>360</b></p>')],
          [fill('Square base side 6, height 10.', 'V = {0}', [['120']]),
           fill('Square base side 8, height 3.', 'Slant height of a face = {0}', [['5']], '√(3² + 4²)'),
           fill('Then the total surface area.', 'SA = {0}', [['144']], '64 + 4 × ½ × 8 × 5'),
           fill('Base area 45 cm², V = 60 cm³.', 'h = {0} cm', [['4']])]),

    44: L('Frustum of a pyramid: V = (h/3)(A₁ + A₂ + √(A₁A₂)). Surface = two bases + trapezium faces.',
          [('Volume', '<p class="wt-key">V = (h/3)(A₁ + A₂ + √(A₁A₂))</p><p>Squares 6 and 3, h = 4: (4/3)(36 + 9 + 18) = <b>84</b></p>'),
           ('Surface area', '<p>Each side face is a trapezium: area = ½(a + b) × slant height.</p><p>Squares 6 and 3, slant height 5: 4 × ½(6 + 3) × 5 = 90 → total = 90 + 36 + 9 = <b>135</b></p>')],
          [fill('A₁ = 25, A₂ = 4, h = 3.', 'V = {0}', [['39']], '(3/3)(25 + 4 + 10) = 39'),
           fill('Squares 10 and 4, slant height of faces 5.', 'Area of the 4 side faces = {0}', [['140']], '4 × ½ × 14 × 5'),
           mcq('The side faces of a square-pyramid frustum are…', ['trapeziums', 'triangles', 'squares'], 'trapeziums'),
           fill('Big pyramid V = 96, small pyramid removed V = 12.', 'Frustum V = {0}', [['84']])]),

    45: L('Sphere: SA = 4πr², V = (4/3)πr³. A hemisphere is half a sphere.',
          [('Formulas', table(['Solid', 'Surface area', 'Volume'], [['Sphere / ball', '4πr²', '(4/3)πr³'], ['Hemisphere (solid)', '3πr²', '(2/3)πr³'], ['Hemispherical bowl (open)', '2πr²', '(2/3)πr³']])),
           ('Example', '<p>Ball r = 6: SA = 144π, V = 288π</p><p>Melting: how many balls of r = 1 from a ball of r = 3? (4/3)π27 ÷ (4/3)π = <b>27</b></p>')],
          [fill('r = 3. In terms of π.', 'SA = {0}, V = {1}', [['36π', '36pi'], ['36π', '36pi']]),
           fill('Solid hemisphere r = 4. In terms of π.', 'SA = {0}', [['48π', '48pi']]),
           fill('A sphere of radius 6 is melted into spheres of radius 2.', 'Number of small spheres = {0}', [['27']], '(6/2)³ = 27'),
           fill('A ball has surface area 100π.', 'r = {0}', [['5']]),
           mcq('A bowl is a hemisphere of radius 9 cm. How much water does it hold (in terms of π)?', ['486π cm³', '972π cm³', '243π cm³'], '486π cm³', '(2/3)π × 729')]),
}
