"""Lower Sixth ICT: computing history, AI, computer types and hardware (lessons 1-14)."""
from helpers import *
from f3_maths_part1 import table

FDE = flow([('Fetch', 'from memory'), ('Decode', 'by the CU'), ('Execute', 'by the ALU')])

VON = svg(440, 200, ''.join([
    box(150, 10, 140, 90, 'CPU', 'CU · ALU · registers', 'v-box2'),
    box(10, 125, 120, 50, 'Input', '', 'v-box'), box(310, 125, 120, 50, 'Output', '', 'v-box'),
    box(150, 125, 140, 50, 'Main memory', 'data + programs', 'v-box3'),
    arrow(130, 140, 150, 110), arrow(290, 110, 310, 140), arrow(205, 125, 205, 100), arrow(235, 100, 235, 125),
    marker(150, 10, 1), marker(150, 125, 2),
]), 'Von Neumann architecture')

MEM = svg(420, 200, ''.join([
    '<polygon points="210,10 330,190 90,190" class="v-box" style="fill-opacity:.35"/>',
    '<text x="210" y="55" text-anchor="middle" class="v-t">Registers</text>',
    '<text x="210" y="90" text-anchor="middle" class="v-t">Cache</text>',
    '<text x="210" y="125" text-anchor="middle" class="v-t">RAM</text>',
    '<text x="210" y="165" text-anchor="middle" class="v-t">Secondary storage</text>',
    '<text x="350" y="30" class="v-s">faster,</text><text x="350" y="46" class="v-s">smaller,</text><text x="350" y="62" class="v-s">dearer ↑</text>',
]), 'Memory hierarchy')

LESSONS = {
    1: L('Computing grew from counting tools to mechanical machines, then five generations of electronic computers.',
         [('Early devices', table(['Device', 'Who / when'], [['Abacus', 'ancient counting frame'], ['Napier\'s bones', 'John Napier, 1617'], ['Pascaline', 'Blaise Pascal, 1642'], ['Analytical Engine', 'Charles Babbage, 1830s'], ['Punched-card tabulator', 'Herman Hollerith, 1890']])),
          ('Generations', table(['Gen', 'Technology', 'Example'], [['1st (1940s–50s)', 'vacuum tubes', 'ENIAC'], ['2nd (late 1950s–60s)', 'transistors', 'IBM 1401'], ['3rd (1960s–70s)', 'integrated circuits', 'IBM 360'], ['4th (1970s–)', 'microprocessors (VLSI)', 'personal computers'], ['5th', 'AI, parallel processing', 'expert systems, AI assistants']])),
          ('Trend', '<p class="wt-key">Each generation: smaller, faster, cheaper, more reliable, less power.</p><p>Ada Lovelace wrote the first algorithm for Babbage\'s engine; Alan Turing set out the theory of computation.</p>')],
         [order('Put these in chronological order.', ['Abacus', 'Pascaline', 'Analytical Engine', 'ENIAC', 'Personal computer']),
          match('Match the generation to its technology.', [('1st', 'Vacuum tubes'), ('2nd', 'Transistors'), ('3rd', 'Integrated circuits'), ('4th', 'Microprocessors')]),
          match('Match the person to the contribution.', [('Charles Babbage', 'Analytical Engine'), ('Ada Lovelace', 'First published algorithm'), ('Blaise Pascal', 'Mechanical adding machine'), ('Herman Hollerith', 'Punched-card tabulator')]),
          tf('Third-generation computers used vacuum tubes.', False, 'They used integrated circuits.')]),

    2: L('Artificial Intelligence is the ability of machines to perform tasks that normally require human intelligence.',
         [('Definition', '<p>AI systems <b>perceive</b>, <b>reason</b>, <b>learn</b> and <b>act</b>. The Turing test asks whether a machine\'s answers can be told apart from a human\'s.</p>'),
          ('Types of AI', table(['Type', 'Meaning'], [['Narrow (weak) AI', 'one task: translation, face recognition — all AI today'], ['General (strong) AI', 'human-level on any task — not yet achieved'], ['Super AI', 'beyond human intelligence — hypothetical']])),
          ('Fields', '<div class="chips"><span>Machine learning</span><span>Natural language processing</span><span>Computer vision</span><span>Robotics</span><span>Expert systems</span></div>')],
         [mcq('All AI systems in use today are…', ['narrow AI', 'general AI', 'super AI'], 'narrow AI'),
          match('Match the field to the example.', [('Computer vision', 'Detecting tumours in X-rays'), ('NLP', 'A chatbot answering questions'), ('Expert system', 'Diagnosing faults with rules'), ('Robotics', 'Automated warehouse arm')]),
          mcq('What does the Turing test check?', ['Whether a machine\'s answers seem human', 'How fast a CPU is', 'If a program has bugs'], 'Whether a machine\'s answers seem human'),
          tf('General AI already exists.', False)]),

    3: L('AI must be fair, transparent, private, safe and accountable.',
         [('Ethical principles', table(['Principle', 'Meaning'], [['Fairness', 'no unjust bias against groups'], ['Transparency', 'people can know how decisions are made'], ['Privacy', 'personal data is protected'], ['Accountability', 'a human/organisation is responsible'], ['Safety', 'systems don\'t cause harm']])),
          ('Risks', '<ul><li><b>Bias</b> from unrepresentative training data</li><li><b>Deepfakes</b> and misinformation</li><li><b>Surveillance</b> and loss of privacy</li><li><b>Job displacement</b></li><li><b>Over-reliance</b> on AI answers</li></ul>'),
          ('Responsible use', '<p class="wt-key">Verify outputs, disclose AI use, protect data, keep a human in the loop for important decisions.</p>')],
         [match('Match the problem to the principle it breaks.', [('A loan AI rejects one ethnic group more often', 'Fairness'), ('Nobody can explain why the AI refused', 'Transparency'), ('An app sells users\' photos', 'Privacy'), ('No one takes responsibility for an AI error', 'Accountability')]),
          mcq('A face-recognition system works badly on dark skin. The most likely cause is…', ['unrepresentative training data', 'a slow processor', 'a virus'], 'unrepresentative training data'),
          sort('Responsible or irresponsible?', ['Responsible', 'Irresponsible'], [('Citing that a report used AI help', 'Responsible'), ('Creating a deepfake of a classmate', 'Irresponsible'), ('Checking AI facts against sources', 'Responsible'), ('Letting AI alone decide a medical treatment', 'Irresponsible')]),
          tf('A "human in the loop" means a person reviews important AI decisions.', True)]),

    4: L('AI uses techniques like search, rules, machine learning and neural networks to build intelligent systems.',
         [('Techniques', table(['Technique', 'Idea'], [['Search', 'explore possible moves (chess, route finding)'], ['Rule-based / expert systems', 'IF–THEN rules from human experts'], ['Machine learning', 'learn patterns from data'], ['Neural networks', 'layers of artificial neurons; deep learning'], ['Fuzzy logic', 'degrees of truth (0 to 1), e.g. "warm"']])),
          ('Expert system parts', '<ul><li><b>Knowledge base</b>: facts and rules</li><li><b>Inference engine</b>: applies rules to reach conclusions</li><li><b>User interface</b></li><li><b>Explanation facility</b>: says why</li></ul>'),
          ('Intelligent agents', '<p>An agent <b>senses</b> its environment and <b>acts</b> to reach a goal (a robot vacuum, a game bot).</p>')],
         [match('Match the technique to the example.', [('Search', 'GPS finding the shortest route'), ('Expert system', 'Medical diagnosis with IF–THEN rules'), ('Neural network', 'Recognising handwritten digits'), ('Fuzzy logic', 'Washing machine adjusting to "quite dirty"')]),
          order('Order the parts of an expert system from user to knowledge.', ['User interface', 'Inference engine', 'Knowledge base']),
          mcq('In an expert system, the inference engine…', ['applies rules to facts to reach conclusions', 'stores the facts', 'draws the screen'], 'applies rules to facts to reach conclusions'),
          tf('Fuzzy logic allows values between true and false.', True)]),

    5: L('Machine learning lets computers learn from data instead of following hand-written rules.',
         [('Three types', table(['Type', 'Data', 'Example'], [['Supervised', 'labelled examples', 'spam / not spam'], ['Unsupervised', 'no labels; find groups', 'customer segments'], ['Reinforcement', 'rewards and penalties', 'game-playing agent']])),
          ('Workflow', flow([('Collect', 'data'), ('Prepare', 'clean, split'), ('Train', 'model'), ('Evaluate', 'test data'), ('Deploy', 'use it')])),
          ('Key ideas', '<ul><li><b>Training set</b> vs <b>test set</b></li><li><b>Classification</b> (category) vs <b>regression</b> (number)</li><li><b>Overfitting</b>: memorises training data, fails on new data</li></ul>')],
         [sort('Which type of learning?', ['Supervised', 'Unsupervised', 'Reinforcement'], [('Predict exam grades from labelled past results', 'Supervised'), ('Group shoppers with similar habits', 'Unsupervised'), ('Robot learns to walk by trial and reward', 'Reinforcement'), ('Classify emails as spam using labelled emails', 'Supervised')]),
          order('Order the ML workflow.', ['Collect data', 'Prepare data', 'Train the model', 'Evaluate on test data', 'Deploy']),
          sort('Classification or regression?', ['Classification', 'Regression'], [('Is this photo a cat?', 'Classification'), ('Predict tomorrow\'s temperature', 'Regression'), ('Predict a house price', 'Regression'), ('Is this transaction fraud?', 'Classification')]),
          mcq('A model scores 99% on training data but 60% on new data. This is…', ['overfitting', 'underfitting', 'perfect'], 'overfitting')]),

    6: L('Developing an AI system follows clear stages, from defining the problem to monitoring the model.',
         [('Stages', '<ol><li>Define the problem and success measure</li><li>Collect and label data</li><li>Clean and prepare data</li><li>Choose and train a model</li><li>Evaluate (accuracy, fairness)</li><li>Deploy</li><li>Monitor and update</li></ol>'),
          ('Tools', '<div class="chips"><span>Python</span><span>scikit-learn</span><span>TensorFlow</span><span>Teachable Machine</span><span>Jupyter</span></div>'),
          ('Evaluation', '<p><b>Accuracy</b> = correct predictions ÷ total. 90 correct out of 100 → 90%.</p><p class="wt-key">Data quality decides model quality.</p>')],
         [order('Order the stages of developing an AI system.', ['Define the problem', 'Collect data', 'Prepare data', 'Train a model', 'Evaluate', 'Deploy and monitor']),
          fill('A model classifies 170 of 200 test images correctly.', 'Accuracy = {0}%', [['85']]),
          mcq('Why keep a separate test set?', ['To check performance on unseen data', 'To train faster', 'To save storage'], 'To check performance on unseen data'),
          tf('Once deployed, an AI model never needs updating.', False, 'Data changes over time; models must be monitored.')]),

    7: L('Computers are classified by size and power, by type of data handled, and by purpose.',
         [('By size', table(['Type', 'Use'], [['Supercomputer', 'weather, scientific simulation'], ['Mainframe', 'banks, many simultaneous users'], ['Minicomputer / server', 'departments, networks'], ['Microcomputer', 'desktop, laptop, tablet, smartphone'], ['Embedded', 'inside appliances, cars']])),
          ('By data', '<p><b>Analog</b> (continuous), <b>digital</b> (discrete 0/1), <b>hybrid</b> (both, e.g. ICU monitors).</p>'),
          ('By purpose', '<p><b>General-purpose</b> (PC) vs <b>special-purpose</b> (ATM, traffic controller).</p>')],
         [order('From most to least powerful.', ['Supercomputer', 'Mainframe', 'Minicomputer', 'Microcomputer']),
          sort('Analog, digital or hybrid?', ['Analog', 'Digital', 'Hybrid'], [('Smartphone', 'Digital'), ('Mercury thermometer', 'Analog'), ('ICU patient monitor', 'Hybrid'), ('Laptop', 'Digital')]),
          mcq('A bank processing millions of transactions for many users uses a…', ['mainframe', 'microcomputer', 'calculator'], 'mainframe'),
          tf('An ATM is a special-purpose computer.', True)]),

    8: L('Every computer has input, processing, storage and output components, linked by buses.',
         [('Von Neumann model', VON + '<ol><li><b>CPU</b>: control unit, ALU, registers</li><li><b>Main memory</b>: holds both data and programs</li></ol>'),
          ('Buses', table(['Bus', 'Carries'], [['Data bus', 'the data (two-way)'], ['Address bus', 'memory addresses (one-way, from CPU)'], ['Control bus', 'control signals: read, write, clock']])),
          ('Motherboard', '<p>Holds the CPU socket, RAM slots, chipset, expansion slots, BIOS/UEFI chip and ports.</p>')],
         [label('Name the parts.', VON, ['CPU', 'Main memory']),
          match('Match the bus to what it carries.', [('Data bus', 'Data values'), ('Address bus', 'Memory locations'), ('Control bus', 'Read/write and clock signals')]),
          mcq('In the von Neumann model, programs and data are stored…', ['in the same memory', 'in separate memories', 'only on disk'], 'in the same memory'),
          tf('The address bus is one-way (from the CPU).', True)]),

    9: L('Input devices capture data and instructions. Choose them by the type of data and the user.',
         [('Categories', table(['Category', 'Devices'], [['Keying', 'keyboard, keypad'], ['Pointing', 'mouse, touchpad, touchscreen, light pen'], ['Scanning / direct entry', 'scanner, barcode/QR reader, OCR, OMR, MICR'], ['Biometric', 'fingerprint, iris, face scanners'], ['Audio/video', 'microphone, webcam, digital camera'], ['Sensors', 'temperature, light, motion']])),
          ('Direct data entry', '<ul><li><b>OMR</b>: marks on forms (MCQ answer sheets)</li><li><b>OCR</b>: printed text → editable text</li><li><b>MICR</b>: magnetic ink on cheques</li><li><b>RFID / NFC</b>: contactless tags and cards</li></ul>')],
         [match('Best input device for the job.', [('Marking 500 MCQ answer sheets', 'OMR'), ('Reading cheque numbers', 'MICR'), ('Turning a printed page into editable text', 'OCR'), ('Tapping a card to pay', 'NFC / RFID')]),
          sort('Which category?', ['Pointing', 'Scanning', 'Biometric'], [('Touchpad', 'Pointing'), ('Barcode reader', 'Scanning'), ('Iris scanner', 'Biometric'), ('Light pen', 'Pointing'), ('Fingerprint reader', 'Biometric')]),
          tf('Direct data entry reduces typing errors.', True)]),

    10: L('Output devices present results as soft copy (screen, sound) or hard copy (paper).',
          [('Screens', '<p>CRT (old), LCD, LED, OLED. Quality depends on <b>resolution</b> (e.g. 1920 × 1080 pixels), size and refresh rate.</p>'),
           ('Printers', table(['Printer', 'Type', 'Notes'], [['Dot-matrix', 'impact', 'noisy, carbon copies, receipts'], ['Inkjet', 'non-impact', 'cheap to buy, good colour photos'], ['Laser', 'non-impact', 'fast, sharp text, offices'], ['3D printer', 'additive', 'builds objects layer by layer'], ['Plotter', '—', 'large drawings, maps']])),
           ('Others', '<p>Speakers, headphones, projectors, actuators (motors, buzzers), Braille embossers.</p>')],
          [match('Best output device.', [('Printing carbon-copy invoices', 'Dot-matrix printer'), ('Engineering drawings on A0', 'Plotter'), ('Printing 2000 pages of text per day', 'Laser printer'), ('Making a plastic prototype', '3D printer')]),
           fill('A screen is 1920 × 1080.', 'Total pixels = {0}', [['2073600', '2,073,600']]),
           sort('Soft or hard copy?', ['Soft copy', 'Hard copy'], [('Projected slide', 'Soft copy'), ('Printed report', 'Hard copy'), ('Audio announcement', 'Soft copy'), ('Braille print-out', 'Hard copy')]),
           tf('An actuator, like a motor, is an output device.', True)]),

    11: L('Secondary storage keeps data permanently: magnetic, optical, solid-state and cloud.',
          [('Types', table(['Type', 'Examples', 'Notes'], [['Magnetic', 'HDD, magnetic tape', 'large, cheap; tape for backups (sequential access)'], ['Optical', 'CD (700 MB), DVD (4.7 GB), Blu-ray (25 GB)', 'portable, slow'], ['Solid-state', 'SSD, USB flash, SD card', 'fast, no moving parts, shock-resistant'], ['Cloud', 'Google Drive, OneDrive', 'online, needs internet']])),
           ('Access', '<p><b>Direct (random) access</b>: jump to any data (disks). <b>Sequential access</b>: read in order (tape).</p>'),
           ('Choosing', '<p>Compare capacity, speed, cost per GB, portability and durability.</p>')],
          [sort('Magnetic, optical or solid-state?', ['Magnetic', 'Optical', 'Solid-state'], [('HDD', 'Magnetic'), ('Blu-ray', 'Optical'), ('SSD', 'Solid-state'), ('Magnetic tape', 'Magnetic'), ('SD card', 'Solid-state'), ('DVD', 'Optical')]),
           mcq('Which uses sequential access?', ['Magnetic tape', 'SSD', 'HDD'], 'Magnetic tape'),
           mcq('Best storage for a laptop that is often dropped?', ['SSD', 'HDD', 'Tape'], 'SSD', 'No moving parts.'),
           fill('How many 700 MB CDs are needed for 3.5 GB (use 1 GB = 1000 MB)?', '{0}', [['5']])]),

    12: L('Primary storage is directly accessed by the CPU: RAM, ROM, cache and registers.',
          [('RAM and ROM', table(['', 'RAM', 'ROM'], [['Volatile?', 'yes', 'no'], ['Read/write', 'read and write', 'read only (mostly)'], ['Holds', 'running programs and data', 'firmware / boot program (BIOS)']])),
           ('Types', '<ul><li><b>SRAM</b>: fast, used for cache · <b>DRAM</b>: main memory, needs refreshing</li><li><b>PROM, EPROM, EEPROM</b> (flash): ROM that can be programmed/erased</li></ul>'),
           ('Memory hierarchy', MEM)],
          [match('Match the memory to its use.', [('Cache', 'Holds frequently used instructions near the CPU'), ('DRAM', 'Main memory'), ('ROM', 'Stores the boot program'), ('Registers', 'Hold values the CPU is working on now')]),
           order('From fastest to slowest.', ['Registers', 'Cache', 'RAM', 'Secondary storage']),
           mcq('Which ROM can be erased electrically?', ['EEPROM', 'PROM', 'Mask ROM'], 'EEPROM'),
           tf('RAM loses its contents when power is off.', True)]),

    13: L('The CPU runs programs by repeating the fetch–decode–execute cycle using special registers.',
          [('The cycle', FDE),
           ('Registers', table(['Register', 'Role'], [['PC (program counter)', 'address of the next instruction'], ['MAR', 'address to read/write'], ['MDR (MBR)', 'data just read / to write'], ['CIR', 'current instruction being decoded'], ['ACC (accumulator)', 'results from the ALU']])),
           ('Step by step', '<ol><li>PC → MAR</li><li>Instruction copied from memory → MDR</li><li>MDR → CIR; PC increases by 1</li><li>CU decodes CIR</li><li>Execute: ALU works, result in ACC</li></ol><p>Speed: <b>clock speed</b> (GHz), number of <b>cores</b>, <b>cache</b> size.</p>')],
          [order('Order the fetch–decode–execute steps.', ['Copy PC to MAR', 'Fetch instruction into MDR', 'Copy MDR to CIR and increment PC', 'Decode the instruction', 'Execute it']),
           match('Match the register to its role.', [('PC', 'Address of the next instruction'), ('MAR', 'Address being accessed'), ('MDR', 'Data being transferred'), ('ACC', 'Result of calculations')]),
           mcq('Which does NOT directly increase CPU performance?', ['Bigger monitor', 'Higher clock speed', 'More cores'], 'Bigger monitor'),
           fill('A 3 GHz CPU has how many clock cycles per second?', '{0} billion', [['3']])]),

    14: L('Architectures differ in how they handle instructions and data; parallel and distributed computing share work.',
          [('Architectures', table(['Architecture', 'Idea'], [['Von Neumann', 'one memory for data and instructions (bottleneck)'], ['Harvard', 'separate memories/buses for data and instructions'], ['CISC', 'many complex instructions (x86)'], ['RISC', 'few simple instructions, fast (ARM in phones)']])),
           ('Parallel computing', '<p>Several processors/cores work on parts of one task at the same time: multicore CPUs, GPUs.</p>'),
           ('Distributed computing', '<p>Many networked computers share a job: clusters, grid computing, cloud services.</p>')],
          [match('Match the architecture to its description.', [('Harvard', 'Separate data and instruction memory'), ('RISC', 'Small set of simple instructions'), ('CISC', 'Large set of complex instructions'), ('Von Neumann', 'Shared memory for data and programs')]),
           mcq('Most smartphones use…', ['RISC (ARM) processors', 'CISC mainframes', 'vacuum tubes'], 'RISC (ARM) processors'),
           sort('Parallel or distributed?', ['Parallel', 'Distributed'], [('8 cores rendering one video', 'Parallel'), ('Thousands of PCs analysing data over the internet', 'Distributed'), ('A GPU training a neural network', 'Parallel'), ('A cloud service spread across data centres', 'Distributed')]),
           tf('The von Neumann bottleneck comes from sharing one bus for data and instructions.', True)]),
}
