"""Lower Sixth ICT: software, operating systems, maintenance, ergonomics, office software (lessons 16-33)."""
from helpers import *
from f3_maths_part1 import table

SOFT_TREE = svg(440, 170, ''.join([
    box(150, 8, 140, 40, 'Software', '', 'v-box2'),
    arrow(220, 48, 110, 80), arrow(220, 48, 330, 80),
    box(30, 80, 160, 40, 'System software', '', 'v-box'), box(250, 80, 160, 40, 'Application software', '', 'v-box3'),
    '<text x="110" y="145" text-anchor="middle" class="v-s">OS · utilities · drivers · translators</text>',
    '<text x="330" y="145" text-anchor="middle" class="v-s">general · specialist · bespoke</text>',
]), 'Classification of software')

PROC_STATES = svg(440, 170, ''.join([
    box(10, 60, 80, 44, 'New', '', 'v-box'), box(130, 60, 80, 44, 'Ready', '', 'v-box2'), box(250, 60, 80, 44, 'Running', '', 'v-box3'),
    box(350, 60, 80, 44, 'Exit', '', 'v-box'), box(190, 125, 80, 40, 'Waiting', '', 'v-box'),
    arrow(90, 82, 130, 82), arrow(210, 76, 250, 76), arrow(250, 92, 210, 92), arrow(330, 82, 350, 82),
    arrow(290, 104, 255, 128), arrow(205, 128, 170, 104),
    '<text x="230" y="70" text-anchor="middle" class="v-s">dispatch</text>',
]), 'Process states')

LESSONS = {
    16: L('Software is the set of programs that make the hardware useful. It is either system software or application software.',
          [('Classification', SOFT_TREE),
           ('By licence', table(['Licence', 'Meaning', 'Example'], [['Proprietary', 'owned; you buy a licence', 'Microsoft Office'], ['Open source', 'source code free to view and modify', 'Linux, LibreOffice'], ['Freeware', 'free to use, code closed', 'Zoom basic'], ['Shareware', 'free trial, then pay', 'WinRAR']])),
           ('Firmware', '<p>Software stored in ROM/flash inside hardware (BIOS, router firmware).</p>')],
          [sort('System or application software?', ['System', 'Application'], [('Windows 11', 'System'), ('Excel', 'Application'), ('Printer driver', 'System'), ('Antivirus', 'System'), ('Photoshop', 'Application'), ('Compiler', 'System')]),
           match('Match the licence.', [('Linux', 'Open source'), ('Microsoft Office', 'Proprietary'), ('Free trial for 30 days', 'Shareware'), ('Free, but code is closed', 'Freeware')]),
           mcq('BIOS is an example of…', ['firmware', 'an application', 'a virus'], 'firmware'),
           tf('Open-source software lets you read and modify the source code.', True)]),

    17: L('Application software lets users do specific tasks: general-purpose packages, specialist software, or bespoke (custom) software.',
          [('Types', table(['Type', 'Examples'], [['General-purpose', 'word processor, spreadsheet, DBMS, presentation, browser'], ['Specialist', 'payroll, CAD, school management, accounting'], ['Bespoke (custom)', 'written for one organisation\'s needs']])),
           ('Off-the-shelf vs bespoke', '<div class="two-col"><div><b>Off-the-shelf</b>cheaper, ready now, tested, support available; may not fit exactly</div><div><b>Bespoke</b>fits needs exactly; expensive, slow to develop</div></div>'),
           ('Suites', '<p>A suite (Microsoft 365, LibreOffice) bundles programs with a common interface and easy data sharing.</p>')],
          [match('Match the task to the software.', [('Writing a letter', 'Word processor'), ('Calculating a budget', 'Spreadsheet'), ('Storing student records with queries', 'Database'), ('Designing a building', 'CAD software')]),
           sort('Advantage of off-the-shelf or bespoke?', ['Off-the-shelf', 'Bespoke'], [('Available immediately', 'Off-the-shelf'), ('Fits the exact needs', 'Bespoke'), ('Cheaper', 'Off-the-shelf'), ('No unnecessary features', 'Bespoke')]),
           tf('A software suite shares a common interface between its programs.', True)]),

    18: L('System software runs and manages the computer: operating systems, utilities, drivers and language translators.',
          [('Types', table(['Type', 'Examples'], [['Operating system', 'Windows, Linux, macOS, Android'], ['Utilities', 'antivirus, backup, disk cleanup, compression, defragmenter'], ['Device drivers', 'printer, graphics card drivers'], ['Translators', 'compiler, interpreter, assembler']])),
           ('Utilities in detail', '<ul><li><b>Defragmenter</b>: rearranges file pieces on an HDD (not needed on SSD)</li><li><b>Compression</b>: zip files to save space</li><li><b>Encryption</b>: protect data</li><li><b>File manager</b>: organise files</li></ul>')],
          [match('Match the utility to its job.', [('Defragmenter', 'Puts file fragments together on an HDD'), ('Compression tool', 'Makes files smaller'), ('Backup utility', 'Copies data for recovery'), ('Antivirus', 'Detects and removes malware')]),
           mcq('Software that lets the OS control a printer is a…', ['device driver', 'compiler', 'spreadsheet'], 'device driver'),
           tf('Defragmenting an SSD is useful.', False, 'SSDs have no moving parts; defragmenting only wears them.')]),

    19: L('The operating system is the main system software: it manages hardware and resources and provides an interface.',
          [('Definition', '<p class="wt-key">OS = resource manager + user interface + platform for applications.</p>'),
           ('Types of OS', table(['Type', 'Meaning'], [['Single-user, single-task', 'one user, one program (old MS-DOS)'], ['Multi-tasking', 'several programs at once (Windows)'], ['Multi-user', 'many users share resources (Unix servers)'], ['Real-time', 'responds within strict time limits (airbag, robots)'], ['Batch', 'jobs grouped and run without interaction (payroll)'], ['Mobile', 'Android, iOS'], ['Network OS', 'manages a network (Windows Server)']])),
           ('Booting', '<p>Power on → BIOS/UEFI runs POST → finds boot device → loads the OS kernel into RAM.</p>')],
          [match('Which OS type?', [('Airbag controller', 'Real-time'), ('Monthly payroll overnight', 'Batch'), ('Many terminals on one server', 'Multi-user'), ('Phone', 'Mobile')]),
           order('Order the boot process.', ['Power on', 'BIOS/UEFI runs POST', 'Boot device found', 'OS kernel loaded into RAM']),
           mcq('POST stands for…', ['Power-On Self Test', 'Program Output Start Task', 'Primary Operating System Tool'], 'Power-On Self Test'),
           tf('A real-time OS must respond within a guaranteed time.', True)]),

    20: L('The OS manages processes and memory: scheduling the CPU and allocating RAM.',
          [('Process management', PROC_STATES + '<p>A process moves between states. The <b>scheduler</b> decides which ready process runs next.</p>'),
           ('Scheduling', '<ul><li><b>FCFS</b>: first come, first served</li><li><b>Round robin</b>: each gets a time slice</li><li><b>Priority</b>: most important first</li><li><b>SJF</b>: shortest job first</li></ul>'),
           ('Memory management', '<p>Allocates RAM to processes, protects them from each other. <b>Virtual memory</b> uses disk space when RAM is full (paging) — slower ("thrashing" if overused).</p>')],
          [order('Order the normal life of a process.', ['New', 'Ready', 'Running', 'Exit']),
           match('Match the scheduling method.', [('Round robin', 'Each process gets a fixed time slice'), ('FCFS', 'In order of arrival'), ('SJF', 'Shortest job first'), ('Priority', 'Most important first')]),
           mcq('A process waiting for keyboard input is in the…', ['waiting (blocked) state', 'running state', 'exit state'], 'waiting (blocked) state'),
           mcq('Virtual memory uses…', ['part of the disk as extra RAM', 'more cache', 'cloud storage'], 'part of the disk as extra RAM')]),

    21: L('The OS also manages files, devices, security and communication.',
          [('File management', '<p>Creates, names, organises (folders), protects files; uses a file system (NTFS, FAT32, ext4).</p>'),
           ('Device management', '<p>Uses drivers, handles interrupts, buffers and spooling (printer queue).</p>'),
           ('Security', '<p>User accounts, passwords, permissions (read/write/execute), firewall, updates.</p>'),
           ('Interrupts', '<p class="wt-key">An interrupt is a signal that makes the CPU pause and deal with an urgent event (key pressed, printer out of paper).</p>')],
          [match('Match the OS function.', [('Keeping a print queue', 'Device management (spooling)'), ('Folders and file names', 'File management'), ('Passwords and permissions', 'Security management'), ('Allocating RAM', 'Memory management')]),
           mcq('A printer runs out of paper and the computer shows a message. This uses…', ['an interrupt', 'a compiler', 'a spreadsheet'], 'an interrupt'),
           sort('Which is a file system?', ['File system', 'Not a file system'], [('NTFS', 'File system'), ('FAT32', 'File system'), ('ext4', 'File system'), ('HTML', 'Not a file system')]),
           tf('Spooling stores print jobs in a queue so the user can keep working.', True)]),

    22: L('Install an OS step by step, then choose the right user interface: GUI, CLI, menu-driven or touch/voice.',
          [('Installation steps', '<ol><li>Check hardware requirements</li><li>Back up data</li><li>Boot from USB/DVD installer</li><li>Partition and format the disk</li><li>Copy files, set language, user account</li><li>Install drivers and updates</li></ol>'),
           ('User interfaces', table(['Interface', 'Pros', 'Cons'], [['GUI', 'easy, visual', 'needs more resources'], ['CLI', 'fast, scriptable, light', 'commands to learn'], ['Menu-driven', 'simple choices (ATM)', 'limited'], ['Natural language / voice', 'hands-free', 'can misunderstand']]))],
          [order('Order the installation steps.', ['Check requirements', 'Back up data', 'Boot from the installer', 'Partition and format', 'Set up user account', 'Install drivers and updates']),
           match('Match the interface to the example.', [('GUI', 'Windows desktop'), ('CLI', 'Linux terminal'), ('Menu-driven', 'ATM screen'), ('Voice', 'Smart speaker')]),
           tf('Formatting a partition erases the data on it.', True)]),

    23: L('A GUI uses WIMP: Windows, Icons, Menus and Pointer.',
          [('WIMP', '<ul><li><b>W</b>indows: framed areas for each program</li><li><b>I</b>cons: small pictures for files and programs</li><li><b>M</b>enus: lists of commands</li><li><b>P</b>ointer: the mouse cursor</li></ul>'),
           ('Common tasks', table(['Task', 'How'], [['Switch windows', 'Alt + Tab'], ['Copy / paste', 'Ctrl + C / Ctrl + V'], ['Rename a file', 'select + F2'], ['Open Task Manager', 'Ctrl + Shift + Esc'], ['Lock screen', 'Windows + L']]))],
          [match('What does WIMP stand for?', [('W', 'Windows'), ('I', 'Icons'), ('M', 'Menus'), ('P', 'Pointer')]),
           match('Match the shortcut.', [('Ctrl + C', 'Copy'), ('Alt + Tab', 'Switch window'), ('F2', 'Rename'), ('Windows + L', 'Lock the computer')]),
           tf('A GUI needs more memory and processing than a CLI.', True)]),

    24: L('The CLI lets you control the OS by typing commands.',
          [('Windows vs Linux', table(['Task', 'Windows (cmd)', 'Linux (bash)'], [['List files', 'dir', 'ls'], ['Change folder', 'cd', 'cd'], ['Make folder', 'mkdir', 'mkdir'], ['Copy', 'copy', 'cp'], ['Move/rename', 'move / ren', 'mv'], ['Delete file', 'del', 'rm'], ['Clear screen', 'cls', 'clear']])),
           ('Paths', '<p><b>Absolute</b>: C:\\Users\\Awa\\notes.txt · <b>Relative</b>: ..\\notes.txt (".." = parent folder)</p><p class="wt-key">Be careful: deleting from the CLI usually skips the Recycle Bin.</p>')],
          [match('Match the Linux command.', [('ls', 'List files'), ('cp', 'Copy'), ('mv', 'Move or rename'), ('rm', 'Delete')]),
           mcq('Which Windows command lists the contents of a folder?', ['dir', 'ls', 'list'], 'dir'),
           mcq('"cd .." means…', ['go to the parent folder', 'delete the folder', 'create a folder'], 'go to the parent folder'),
           fill('Command to create a folder called Projects (Windows or Linux).', '{0} Projects', [['mkdir', 'md']])]),

    25: L('Diagnose hardware faults systematically: symptoms, possible causes, test, fix.',
          [('Common faults', table(['Symptom', 'Likely cause', 'Fix'], [['No power, no lights', 'power cable, PSU', 'check socket/cable, replace PSU'], ['Beeps, no display', 'RAM not seated, graphics card', 'reseat RAM / card'], ['Overheating, shutdowns', 'dust, failed fan, dry thermal paste', 'clean, replace fan, new paste'], ['Clicking noise', 'failing HDD', 'back up immediately, replace'], ['Peripheral not working', 'cable, port, driver', 'reconnect, try another port']])),
           ('Method', flow(['Identify', 'Theory of cause', 'Test', 'Fix', 'Verify', 'Document'])),
           ('Safety', '<p>Power off and unplug, use an anti-static wrist strap, never open a PSU or CRT.</p>')],
          [order('Order the troubleshooting method.', ['Identify the problem', 'Establish a probable cause', 'Test the theory', 'Fix it', 'Verify it works', 'Document']),
           match('Match the symptom to the likely cause.', [('Beeps at start-up, no display', 'RAM not seated properly'), ('Random shutdowns when busy', 'Overheating'), ('Clicking from the case', 'Failing hard disk'), ('Completely dead, no lights', 'Power supply / cable')]),
           tf('You should wear an anti-static strap when touching internal components.', True)]),

    26: L('Software faults: crashes, freezes, errors, slowness and malware. Fix them from the simplest step up.',
          [('Common faults', table(['Fault', 'Fix'], [['Program not responding', 'end task in Task Manager'], ['Slow system', 'close start-up programs, free disk space, scan malware'], ['Blue screen (BSOD)', 'note the error code, update/roll back drivers'], ['App won\'t start', 'repair or reinstall, check compatibility'], ['Boot failure', 'safe mode, startup repair, system restore']])),
           ('Tools', '<div class="chips"><span>Task Manager</span><span>Safe Mode</span><span>System Restore</span><span>Event Viewer</span><span>Antivirus</span><span>Device Manager</span></div>')],
          [match('Match the fault to the tool.', [('Frozen program', 'Task Manager'), ('Problem after a bad update', 'System Restore'), ('Driver problem', 'Device Manager'), ('Strange pop-ups', 'Antivirus scan')]),
           mcq('Safe Mode starts Windows with…', ['only essential drivers and services', 'all programs', 'no operating system'], 'only essential drivers and services'),
           order('From simplest to most drastic.', ['Restart', 'Update / repair the program', 'System Restore', 'Reinstall the OS'])]),

    27: L('Assistive technology helps people with disabilities use computers independently.',
          [('Examples', table(['Need', 'Technology'], [['Blind / low vision', 'screen reader (NVDA, JAWS), magnifier, Braille display/embosser'], ['Deaf / hard of hearing', 'captions, visual alerts, speech-to-text'], ['Limited movement', 'voice control, eye-tracking, switch access, sip-and-puff, on-screen keyboard'], ['Learning difficulties', 'text-to-speech, word prediction, spell checkers']])),
           ('Accessibility settings', '<p>High contrast, larger text, sticky keys, filter keys, narrator. Websites should use alt text for images.</p>')],
          [match('Match the person to the best technology.', [('Blind student', 'Screen reader'), ('Student who cannot use hands', 'Eye-tracking'), ('Deaf viewer', 'Captions'), ('Student with dyslexia', 'Text-to-speech')]),
           mcq('Alt text on a website image helps…', ['screen reader users', 'the website load faster', 'search engines only'], 'screen reader users'),
           tf('Sticky keys let users press key combinations one key at a time.', True)]),

    28: L('Ergonomics designs the workstation to fit the user and prevent health problems.',
          [('Health risks', table(['Problem', 'Cause', 'Prevention'], [['RSI / carpal tunnel', 'repetitive typing', 'wrist rest, breaks, ergonomic keyboard'], ['Eye strain', 'long screen use, glare', '20-20-20 rule, anti-glare, correct brightness'], ['Back and neck pain', 'bad posture', 'adjustable chair, screen at eye level'], ['Stress', 'long hours', 'breaks, good lighting']])),
           ('Good posture', '<ul><li>Top of screen at eye level, arm\'s length away</li><li>Feet flat, knees ≈ 90°</li><li>Elbows ≈ 90°, wrists straight</li><li>20-20-20: every 20 min, look 20 feet away for 20 s</li></ul>')],
          [match('Match the problem to the prevention.', [('RSI', 'Wrist rest and regular breaks'), ('Eye strain', 'Anti-glare screen and 20-20-20 rule'), ('Back pain', 'Adjustable chair with lumbar support'), ('Neck pain', 'Screen at eye level')]),
           mcq('Where should the top of the monitor be?', ['At eye level', 'Well above the head', 'At desk level'], 'At eye level'),
           tf('The 20-20-20 rule helps reduce eye strain.', True)]),

    29: L('Editing changes the content; formatting changes how it looks.',
          [('Editing', '<p>Insert, delete, cut, copy, paste, find and replace, undo/redo, spell check, track changes.</p>'),
           ('Formatting', table(['Level', 'Examples'], [['Character', 'font, size, bold, italic, colour'], ['Paragraph', 'alignment, line spacing, indent, bullets'], ['Page', 'margins, orientation, size, columns, headers/footers'], ['Styles', 'Heading 1, Normal — consistent formatting, automatic table of contents']])),
           ('Shortcuts', '<p>Ctrl+B bold · Ctrl+I italic · Ctrl+U underline · Ctrl+E centre · Ctrl+J justify · Ctrl+H replace</p>')],
          [sort('Editing or formatting?', ['Editing', 'Formatting'], [('Find and replace', 'Editing'), ('Make a title bold', 'Formatting'), ('Delete a sentence', 'Editing'), ('Change line spacing', 'Formatting'), ('Spell check', 'Editing')]),
           match('Match the shortcut.', [('Ctrl + B', 'Bold'), ('Ctrl + E', 'Centre'), ('Ctrl + J', 'Justify'), ('Ctrl + H', 'Find and replace')]),
           mcq('Using Heading styles lets you…', ['generate an automatic table of contents', 'print faster', 'remove viruses'], 'generate an automatic table of contents')]),

    30: L('Insert and format images and tables to present information clearly.',
          [('Images', '<p>Insert → Picture. Resize with corner handles (keeps proportions), crop, set <b>text wrapping</b> (square, tight, behind, in front), add borders and captions.</p>'),
           ('Tables', '<p>Insert → Table (rows × columns). Merge/split cells, add/delete rows, borders and shading, header row repeat, sort data, simple formulas (=SUM(ABOVE)).</p>')],
          [mcq('To resize an image without distorting it, drag…', ['a corner handle', 'a side handle', 'the rotation handle'], 'a corner handle'),
           match('Match the task.', [('Text flows around a picture', 'Text wrapping'), ('Combine two cells into one', 'Merge cells'), ('Remove part of a picture', 'Crop'), ('Column titles on every page', 'Repeat header row')]),
           fill('A table has 4 rows and 5 columns.', 'Number of cells = {0}', [['20']])]),

    31: L('Text boxes place text anywhere; page layout controls margins, orientation, columns and breaks.',
          [('Text boxes', '<p>Insert → Text Box: move freely, add borders/fill, link boxes so text flows from one to the next (newsletters).</p>'),
           ('Page layout', table(['Setting', 'Use'], [['Margins', 'space around the page'], ['Orientation', 'portrait or landscape'], ['Size', 'A4, A3, letter'], ['Columns', 'newspaper-style text'], ['Breaks', 'page break, section break'], ['Header / footer', 'page numbers, titles on every page']]))],
          [match('Match the need to the setting.', [('A wide table', 'Landscape orientation'), ('Newspaper-style text', 'Columns'), ('Page numbers on every page', 'Footer'), ('Start a new chapter on a new page', 'Page break')]),
           mcq('To use portrait for some pages and landscape for others you need…', ['section breaks', 'text boxes', 'bold text'], 'section breaks'),
           tf('Linked text boxes let text flow from one box to another.', True)]),

    32: L('A spreadsheet is a grid of cells for storing data and calculating automatically.',
          [('Vocabulary', table(['Term', 'Meaning'], [['Workbook', 'the file'], ['Worksheet', 'one sheet/tab'], ['Cell', 'intersection of column and row, e.g. C4'], ['Range', 'block of cells, e.g. A1:C10'], ['Formula', 'starts with =, e.g. =B2*C2'], ['Function', 'built-in formula, e.g. =SUM(A1:A10)']])),
           ('Data types', '<p>Labels (text), values (numbers, dates, currency), formulas. Format cells as currency, percentage, date…</p>'),
           ('Uses', '<p>Budgets, mark sheets, payroll, statistics, charts, what-if analysis.</p>')],
          [fill('How many cells are in the range B2:D5?', '{0}', [['12']], '3 columns × 4 rows'),
           sort('Label, value or formula?', ['Label', 'Value', 'Formula'], [('Name', 'Label'), ('2500', 'Value'), ('=A1+A2', 'Formula'), ('=AVERAGE(B2:B9)', 'Formula'), ('Total', 'Label')]),
           mcq('A worksheet is…', ['one sheet in a workbook', 'the whole file', 'a cell'], 'one sheet in a workbook'),
           tf('Formulas must begin with =', True)]),

    33: L('Use formulas and functions to calculate: SUM, AVERAGE, MAX, MIN, COUNT, IF, and more.',
          [('Functions', table(['Function', 'Does'], [['SUM(A1:A5)', 'adds'], ['AVERAGE(A1:A5)', 'mean'], ['MAX / MIN', 'largest / smallest'], ['COUNT(A1:A5)', 'counts numbers'], ['COUNTIF(A1:A5,">=10")', 'counts cells meeting a condition'], ['IF(B2>=10,"Pass","Fail")', 'chooses a result'], ['ROUND(A1,2)', 'rounds to 2 decimals']])),
           ('Order of operations', '<p>Brackets first, then ^, then × ÷, then + −: =2+3*4 gives 14, =(2+3)*4 gives 20.</p>'),
           ('Errors', '<p>#DIV/0! (divide by zero) · #NAME? (misspelt function) · #REF! (deleted cell) · ##### (column too narrow)</p>')],
          [fill('What does =2+3*4 give?', '{0}', [['14']]),
           fill('What does =(10-4)/2 give?', '{0}', [['3']]),
           fill('A1:A4 contains 8, 12, 5, 15. =COUNTIF(A1:A4,">=10") gives…', '{0}', [['2']]),
           match('Match the error.', [('#DIV/0!', 'Dividing by zero'), ('#NAME?', 'Misspelt function name'), ('#REF!', 'Reference to a deleted cell'), ('#####', 'Column too narrow')]),
           mcq('B2 = 9. =IF(B2>=10,"Pass","Fail") shows…', ['Fail', 'Pass', '9'], 'Fail')]),
}
