"""Lower Sixth ICT: paradigms, reuse, translators, Python coding, functions, testing (lessons 92-105)."""
from helpers import *
from f3_maths_part1 import table
from l6_ict_part5 import code

LESSONS = {
    92: L('A programming paradigm is a style of programming: procedural, object-oriented, functional, logic, event-driven, declarative.',
          [('Paradigms', table(['Paradigm', 'Idea', 'Languages'], [['Procedural', 'sequence of procedures/functions', 'C, Pascal, Python'], ['Object-oriented', 'objects with attributes and methods; classes, inheritance', 'Java, C++, Python'], ['Functional', 'functions without side effects', 'Haskell, Lisp'], ['Logic', 'facts and rules, the system infers', 'Prolog'], ['Event-driven', 'code reacts to events (clicks)', 'JavaScript, VB'], ['Declarative', 'say WHAT, not HOW', 'SQL, HTML']])),
           ('OOP key ideas', '<p><b>Class</b> (template) · <b>object</b> (instance) · <b>encapsulation</b> · <b>inheritance</b> · <b>polymorphism</b></p>')],
          [match('Match the paradigm.', [('SELECT * FROM Student', 'Declarative'), ('parent(john, mary). with rules', 'Logic'), ('Button click runs a function', 'Event-driven'), ('Class Student with methods', 'Object-oriented')]),
           match('Match the OOP term.', [('Template for objects', 'Class'), ('Hiding data inside an object', 'Encapsulation'), ('A child class reuses a parent class', 'Inheritance'), ('One instance of a class', 'Object')]),
           tf('Python supports more than one paradigm.', True)]),

    93: L('Software reuse means using existing code — libraries, modules, components, APIs, frameworks — instead of writing everything again.',
          [('Forms of reuse', '<div class="chips"><span>Functions</span><span>Libraries / modules</span><span>Components</span><span>APIs</span><span>Frameworks</span><span>Templates</span></div>'),
           ('Benefits and risks', '<div class="two-col"><div><b>➕</b>faster, cheaper, already tested, consistent</div><div><b>➖</b>licence issues, may not fit exactly, security of third-party code, dependency on others</div></div>'),
           ('Python example', code('import math\nprint(math.sqrt(49))   # 7.0'))],
          [mcq('Using a mobile-money API in your app is an example of…', ['software reuse', 'reverse engineering', 'piracy'], 'software reuse'),
           sort('Benefit or risk of reuse?', ['Benefit', 'Risk'], [('Already tested code', 'Benefit'), ('Licence restrictions', 'Risk'), ('Faster development', 'Benefit'), ('Hidden security flaw in a library', 'Risk')]),
           fill('What does math.sqrt(81) return in Python?', '{0}', [['9.0', '9']])]),

    94: L('Software can be developed in-house or obtained externally (outsourced, off-the-shelf, open source).',
          [('Comparison', table(['Option', 'Pros', 'Cons'], [['In-house', 'exact fit, control, keeps skills inside', 'needs skilled staff, slow'], ['Outsourced (contractor)', 'expertise, frees staff', 'costly, less control, dependency'], ['Off-the-shelf', 'cheap, quick, support', 'may not fit, licence fees'], ['Open source', 'free, customisable', 'support may be limited']]))],
          [match('Best option?', [('A unique process no product supports, with skilled IT staff', 'In-house'), ('A small shop needs accounting tomorrow', 'Off-the-shelf'), ('No IT staff, needs a custom app', 'Outsourced'), ('Tight budget, wants to customise', 'Open source')]),
           tf('Off-the-shelf software is usually cheaper than bespoke software.', True)]),

    95: L('Translators turn source code into machine code. An IDE provides tools to write, run and debug code.',
          [('Translators', table(['Translator', 'How', 'Notes'], [['Compiler', 'whole program → executable file', 'fast to run; errors reported at the end'], ['Interpreter', 'translates and runs line by line', 'easy debugging; slower; needs interpreter'], ['Assembler', 'assembly language → machine code', 'low-level']])),
           ('IDE features', '<div class="chips"><span>Code editor</span><span>Syntax highlighting</span><span>Auto-complete</span><span>Debugger</span><span>Breakpoints</span><span>Run/compile button</span></div><p>Examples: VS Code, PyCharm, IDLE, Code::Blocks, Thonny.</p>')],
          [match('Match the translator.', [('Produces a standalone .exe', 'Compiler'), ('Stops at the first error line while running', 'Interpreter'), ('Converts MOV AX, 5 to binary', 'Assembler')]),
           mcq('A breakpoint lets you…', ['pause the program at a line to inspect variables', 'delete code', 'compile faster'], 'pause the program at a line to inspect variables'),
           tf('Python is usually run by an interpreter.', True)]),

    96: L('Python programs use print() for output, input() for input, variables to store values, and # for comments.',
          [('First program', code('# My first program\nname = input("What is your name? ")\nprint("Hello", name)')),
           ('Variables and types', code('age = 17          # int\nheight = 1.72     # float\nname = "Awa"      # str\npassed = True     # bool\nprint(type(age))  # <class \'int\'>')),
           ('Rules for names', '<p>Letters, digits, underscore; can\'t start with a digit; no spaces; case-sensitive (Mark ≠ mark).</p>')],
          [mcq('What does print("2" + "3") show?', ['23', '5', 'Error'], '23', 'Strings are joined.'),
           sort('Valid variable name?', ['Valid', 'Invalid'], [('total_marks', 'Valid'), ('2nd_mark', 'Invalid'), ('student name', 'Invalid'), ('mark2', 'Valid')]),
           match('Match the value to its type.', [('17', 'int'), ('3.5', 'float'), ('"Yaoundé"', 'str'), ('False', 'bool')]),
           tf('input() always returns a string.', True)]),

    97: L('Python arithmetic: + − * / // % ** and type conversion with int() and float().',
          [('Operators', table(['Operator', 'Meaning', 'Example', 'Result'], [['/', 'division', '17 / 5', '3.4'], ['//', 'whole division', '17 // 5', '3'], ['%', 'remainder', '17 % 5', '2'], ['**', 'power', '2 ** 5', '32']])),
           ('Converting input', code('a = int(input("First number: "))\nb = int(input("Second number: "))\nprint("Sum:", a + b)')),
           ('Precedence', '<p>** then * / // % then + −. Use brackets: (2 + 3) * 4 = 20.</p>')],
          [fill('Python: 20 // 6 =', '{0}', [['3']]),
           fill('Python: 20 % 6 =', '{0}', [['2']]),
           fill('Python: 3 ** 3 =', '{0}', [['27']]),
           fill('Python: 2 + 3 * 4 =', '{0}', [['14']]),
           mcq('Why use int(input())?', ['input() gives text; int() turns it into a number', 'To print faster', 'To make a comment'], 'input() gives text; int() turns it into a number')]),

    98: L('Selection in Python uses if, elif and else. Indentation shows which lines belong to each branch.',
          [('Example', code('mark = int(input("Mark: "))\nif mark >= 16:\n    print("Very good")\nelif mark >= 10:\n    print("Pass")\nelse:\n    print("Fail")')),
           ('Comparison and logic', '<p>== != &lt; &gt; &lt;= &gt;= and or not</p><p class="wt-key">= assigns, == compares. Don\'t forget the colon : and the indentation.</p>')],
          [mcq('mark = 12. What is printed?', ['Pass', 'Very good', 'Fail'], 'Pass'),
           mcq('Which line has a syntax error?', ['if mark >= 10', 'if mark >= 10:', 'else:'], 'if mark >= 10', 'The colon is missing.'),
           mcq('x = 7. What does (x > 5 and x < 10) give?', ['True', 'False'], 'True'),
           tf('In Python, == compares and = assigns.', True)]),

    99: L('Loops in Python: for with range() for a known count, while for a condition.',
          [('for and range', code('for i in range(1, 6):\n    print(i)        # 1 2 3 4 5') + '<p>range(1, 6) stops <b>before</b> 6. range(5) gives 0 to 4. range(0, 10, 2) gives 0, 2, 4, 6, 8.</p>'),
           ('while', code('total = 0\nn = int(input("Number (0 to stop): "))\nwhile n != 0:\n    total = total + n\n    n = int(input("Number (0 to stop): "))\nprint("Total:", total)'))],
          [fill('How many numbers does range(3, 9) produce?', '{0}', [['6']]),
           fill('s = 0; for i in range(1, 5): s += i. Final s?', '{0}', [['10']]),
           mcq('What is the last value of range(0, 10, 3)?', ['9', '10', '12'], '9'),
           mcq('A while loop whose condition never becomes False…', ['runs forever (infinite loop)', 'runs once', 'does not run'], 'runs forever (infinite loop)')]),

    100: L('Lists store many values in order. Access by index (from 0), add with append(), loop over them.',
           [('Lists', code('marks = [12, 15, 9, 18]\nprint(marks[0])    # 12\nprint(marks[-1])   # 18 (last)\nmarks.append(14)\nprint(len(marks))  # 5')),
            ('Process a list', code('total = 0\nfor m in marks:\n    total = total + m\nprint("Average:", total / len(marks))\nprint("Highest:", max(marks))'))],
           [fill('marks = [12, 15, 9, 18].', 'marks[1] = {0}, marks[-1] = {1}', [['15'], ['18']]),
            fill('After marks.append(10), len(marks) =', '{0}', [['5']]),
            fill('Average of [12, 15, 9, 18]?', '{0}', [['13.5']]),
            mcq('marks[4] on a list of 4 items gives…', ['IndexError', '0', 'the last item'], 'IndexError')]),

    101: L('Strings are sequences of characters: index them, slice them and use string methods.',
           [('String basics', code('s = "Cameroon"\nprint(len(s))      # 8\nprint(s[0])        # C\nprint(s[0:4])      # Came\nprint(s.upper())   # CAMEROON\nprint(s.count("o"))  # 2')),
            ('Mini program', code('word = input("Word: ")\nif word == word[::-1]:\n    print("Palindrome")\nelse:\n    print("Not a palindrome")') + '<p>[::-1] reverses a string.</p>')],
           [fill('s = "Douala".', 'len(s) = {0}, s[0] = {1}', [['6'], ['D']]),
            fill('s = "Douala". s[1:4] =', '{0}', [['oua']]),
            mcq('Is "radar" a palindrome?', ['Yes', 'No'], 'Yes'),
            fill('"Bamenda".lower() =', '{0}', [['bamenda']])]),

    102: L('Functions are named blocks of code. Define with def, pass parameters, return results.',
           [('Defining and calling', code('def area(length, width):\n    return length * width\n\nprint(area(5, 3))   # 15')),
            ('Function vs procedure', '<div class="two-col"><div><b>Function</b>returns a value (return)</div><div><b>Procedure</b>does a task, returns nothing (prints, saves)</div></div>'),
            ('Why?', '<p>Reuse, shorter code, easier testing and teamwork.</p>')],
           [fill('def double(x): return x * 2. double(7) =', '{0}', [['14']]),
            fill('def f(a, b): return a - b. f(10, 4) =', '{0}', [['6']]),
            mcq('In def area(length, width): length and width are…', ['parameters', 'return values', 'modules'], 'parameters'),
            tf('A procedure in Python is a function that does not return a value.', True)]),

    103: L('Variables inside a function are local. Functions can call other functions — even themselves (recursion).',
           [('Scope', code('x = 10            # global\ndef show():\n    y = 5         # local\n    print(x, y)\nshow()            # 10 5\nprint(y)          # NameError: y is local')),
            ('Default parameters', code('def greet(name, msg="Hello"):\n    print(msg, name)\ngreet("Awa")              # Hello Awa\ngreet("Paul", "Bonjour")  # Bonjour Paul')),
            ('Recursion', code('def factorial(n):\n    if n == 0:\n        return 1\n    return n * factorial(n - 1)\nprint(factorial(5))   # 120'))],
           [fill('factorial(4) =', '{0}', [['24']]),
            mcq('greet("Eric") prints…', ['Hello Eric', 'Eric Hello', 'Error'], 'Hello Eric'),
            mcq('A variable created inside a function is…', ['local', 'global', 'constant'], 'local'),
            mcq('What stops a recursive function from running forever?', ['A base case', 'A global variable', 'print()'], 'A base case')]),

    104: L('Three kinds of error: syntax, runtime and logic. Debug them systematically.',
           [('Error types', table(['Error', 'When', 'Example'], [['Syntax', 'code breaks language rules; won\'t run', 'missing colon, bad indentation'], ['Runtime', 'crashes while running', 'division by zero, IndexError'], ['Logic', 'runs but gives wrong result', 'using + instead of *']])),
            ('Debugging', '<ul><li>Read the error message and line number</li><li>Print variable values</li><li>Use breakpoints and step through</li><li>Test small parts separately</li><li>Explain the code aloud ("rubber duck")</li></ul>')],
           [match('Which error?', [('print("Hi"', 'Syntax error'), ('10 / 0', 'Runtime error'), ('average = total * count', 'Logic error')]),
            mcq('The program runs but the average is wrong. This is…', ['a logic error', 'a syntax error', 'a hardware fault'], 'a logic error'),
            tf('Syntax errors stop the program from running at all.', True)]),

    105: L('Test a program with a test plan, varied test data, trace tables, and input validation.',
           [('Validation in Python', code('while True:\n    try:\n        mark = int(input("Mark 0-20: "))\n        if 0 <= mark <= 20:\n            break\n        print("Out of range")\n    except ValueError:\n        print("Enter a whole number")')),
            ('Test plan', table(['Test', 'Data', 'Type', 'Expected'], [['1', '15', 'normal', 'accepted'], ['2', '0, 20', 'boundary', 'accepted'], ['3', '21', 'boundary (outside)', '"Out of range"'], ['4', 'abc', 'erroneous', '"Enter a whole number"']]))],
           [sort('Mark 0–20. Normal, boundary or erroneous?', ['Normal', 'Boundary', 'Erroneous'], [('14', 'Normal'), ('20', 'Boundary'), ('0', 'Boundary'), ('twelve', 'Erroneous'), ('7', 'Normal')]),
            mcq('Which Python block catches a ValueError when converting text to int?', ['try … except', 'if … else', 'for … in'], 'try … except'),
            order('Order the testing process.', ['Write the test plan', 'Choose test data', 'Run the tests', 'Compare actual and expected results', 'Fix errors and re-test'])]),
}
