"""Upper Sixth Computer Science: information systems and database design (lessons 62-79)."""
from helpers import *
from f3_maths_part1 import table
from l6_ict_part4 import ER

THREE_LEVEL = svg(440, 190, ''.join([
    box(20, 10, 120, 40, 'View 1', '', 'v-box'), box(160, 10, 120, 40, 'View 2', '', 'v-box'), box(300, 10, 120, 40, 'View 3', '', 'v-box'),
    box(80, 80, 280, 40, 'Conceptual (logical) schema', '', 'v-box2'),
    box(80, 145, 280, 40, 'Internal (physical) schema', '', 'v-box3'),
    arrow(80, 50, 160, 80), arrow(220, 50, 220, 80), arrow(360, 50, 280, 80), arrow(220, 120, 220, 145),
    marker(20, 10, 1), marker(80, 80, 2), marker(80, 145, 3),
]), 'ANSI-SPARC three-level architecture')

LESSONS = {
    62: L('An information system (IS) combines people, procedures, data, software, hardware and networks to support decisions.',
          [('Components', '<div class="chips"><span>People</span><span>Procedures</span><span>Data</span><span>Software</span><span>Hardware</span><span>Networks</span></div>'),
           ('Functions', flow(['Input', 'Processing', 'Storage', 'Output', 'Feedback'])),
           ('Value of information', '<p>Good information is accurate, timely, relevant, complete, concise, reliable and cost-effective (its value exceeds the cost of producing it).</p>')],
          [mcq('Which is NOT a component of an IS?', ['Competitors', 'Procedures', 'People'], 'Competitors'),
           match('Match the quality of information.', [('Arrives before the decision is made', 'Timely'), ('Free from errors', 'Accurate'), ('Only what is needed, briefly', 'Concise'), ('Worth more than it costs', 'Cost-effective')]),
           order('Order the IS functions.', ['Input', 'Processing', 'Storage', 'Output', 'Feedback'])]),

    63: L('Data capture collects data for input — manually or automatically — as accurately and efficiently as possible.',
          [('Methods', table(['Method', 'Example'], [['Manual keying', 'typing from a form'], ['OMR', 'exam answer sheets'], ['OCR / ICR', 'scanned text / handwriting'], ['MICR', 'cheques'], ['Barcode / QR', 'shop tills, inventory'], ['RFID / NFC', 'access cards, toll tags'], ['Sensors / data logging', 'weather stations'], ['Online forms / mobile apps', 'registrations, mobile money']])),
           ('Form design', '<p>Clear instructions, logical order, boxes for each character, tick boxes, drop-down lists, validation in online forms.</p>')],
          [match('Best capture method.', [('500 multiple-choice answer sheets', 'OMR'), ('Supermarket checkout', 'Barcode'), ('Cheque numbers in banks', 'MICR'), ('Contactless staff entry', 'RFID / NFC')]),
           mcq('Advantage of automatic data capture?', ['Fewer transcription errors and faster input', 'Always cheaper to set up', 'No hardware needed'], 'Fewer transcription errors and faster input'),
           tf('Drop-down lists on online forms reduce input errors.', True)]),

    64: L('Validation checks that data is sensible; verification checks that it was entered correctly.',
          [('Validation checks', table(['Check', 'Example'], [['Presence', 'name must not be empty'], ['Type', 'age must be a number'], ['Range', 'mark between 0 and 20'], ['Length', 'phone has 9 digits'], ['Format', 'date DD/MM/YYYY'], ['Lookup', 'region from a list'], ['Check digit', 'ISBN, barcodes']])),
           ('Check digit (modulo 11)', '<p>Digits 1 3 5, weights 4 3 2: 4 + 9 + 10 = 23; 23 MOD 11 = 1; check digit = 11 − 1 = <b>10 (written X)</b>.</p>'),
           ('Verification', '<p>Double entry (type twice), visual check / proofreading, parity bits and checksums in transmission.</p>')],
          [match('Match the check.', [('Mark 0–20', 'Range check'), ('Field cannot be blank', 'Presence check'), ('Phone must have 9 digits', 'Length check'), ('Enter password twice', 'Verification (double entry)')]),
           fill('Digits 2 1 4 with weights 4 3 2. Weighted sum =', '{0}', [['19']], '8 + 3 + 8'),
           fill('19 MOD 11 = 8, so the check digit (11 − remainder) =', '{0}', [['3']]),
           tf('Validation guarantees that the data is correct.', False, 'It only guarantees it is reasonable (e.g. a wrong but valid age).')]),

    65: L('Each level of management needs a different kind of information system.',
          [('Levels', table(['Level', 'Decisions', 'System'], [['Strategic (top)', 'long-term, unstructured', 'EIS / ESS, DSS'], ['Tactical (middle)', 'medium-term, semi-structured', 'MIS, DSS'], ['Operational (bottom)', 'daily, structured', 'TPS'], ['Knowledge workers', 'specialist', 'KMS, expert systems, CAD']])),
           ('Information characteristics', '<p>Higher levels: summarised, external, future-oriented. Lower levels: detailed, internal, current.</p>')],
          [match('Match the decision to the level.', [('Open a branch in Garoua next year', 'Strategic'), ('Monthly staff rota', 'Tactical'), ('Process today\'s sales', 'Operational')]),
           match('Match the system.', [('Records every transaction', 'TPS'), ('Periodic summary reports', 'MIS'), ('What-if models for semi-structured decisions', 'DSS'), ('Dashboards for executives', 'EIS')]),
           mcq('Top managers need information that is…', ['summarised and future-oriented', 'detailed transaction lists', 'only internal'], 'summarised and future-oriented')]),

    67: L('Information systems are developed in stages: investigation, analysis, design, development, testing, implementation and review.',
          [('Stages', flow(['Investigation', 'Feasibility', 'Analysis', 'Design', 'Development', 'Testing', 'Implementation', 'Review'])),
           ('Feasibility (TELOS)', table(['Type', 'Question'], [['Technical', 'can we build it?'], ['Economic', 'do benefits exceed costs?'], ['Legal', 'does it comply with law?'], ['Operational', 'will people use it?'], ['Schedule', 'can it be done in time?']])),
           ('Implementation', '<p>Training, data conversion, changeover (direct, parallel, phased, pilot), documentation (user and technical).</p>')],
          [match('Match the feasibility type.', [('Is the cost justified by savings?', 'Economic'), ('Do we have the skills and hardware?', 'Technical'), ('Does it respect data protection law?', 'Legal'), ('Will staff accept it?', 'Operational')]),
           order('Order these stages.', ['Feasibility study', 'Analysis', 'Design', 'Development', 'Testing', 'Implementation', 'Post-implementation review']),
           mcq('A manual explaining how to use the system is…', ['user documentation', 'technical documentation', 'a test plan'], 'user documentation')]),

    68: L('Design tools model processes, data and logic: DFDs, ERDs, flowcharts, decision tables, UML and data dictionaries.',
          [('Tools', table(['Tool', 'Models'], [['DFD', 'flow of data through processes'], ['ERD', 'data and relationships'], ['System flowchart', 'programs, files, media'], ['Decision table / tree', 'complex logic'], ['UML (use case, class, sequence, activity)', 'object-oriented design'], ['Data dictionary', 'name, type, size, validation of each item'], ['Gantt chart', 'schedule']])),
           ('Data dictionary entry', table(['Field', 'Type', 'Size', 'Validation'], [['StudentID', 'Text', '8', 'format S0000000'], ['DOB', 'Date', '—', 'age 10–25']]))],
          [match('Match the tool.', [('Lists every data item with type and validation', 'Data dictionary'), ('Actors and their goals', 'Use case diagram'), ('All combinations of conditions and actions', 'Decision table'), ('Entities and relationships', 'ERD')]),
           fill('A decision table has 4 yes/no conditions. Number of rules =', '{0}', [['16']]),
           tf('A data dictionary helps keep data definitions consistent.', True)]),

    69: L('System testing checks the whole system against its requirements, followed by user acceptance testing.',
          [('Strategy', table(['Level', 'Focus'], [['Unit', 'single module'], ['Integration', 'interfaces between modules (top-down / bottom-up)'], ['System', 'whole system: functional + performance, load, security, recovery'], ['Acceptance (UAT)', 'users confirm requirements'], ['Alpha / beta', 'in-house / selected real users']])),
           ('Test data', '<p>Normal, boundary (extreme), erroneous (abnormal). Use <b>live data</b> in acceptance testing.</p>'),
           ('Non-functional tests', '<p><b>Load</b>: expected users · <b>stress</b>: beyond limits · <b>recovery</b>: after crash · <b>security</b>: attacks.</p>')],
          [match('Match the test.', [('1000 students log in at once', 'Load testing'), ('Push the server until it fails', 'Stress testing'), ('Pull the power and check data survives', 'Recovery testing'), ('Users try it before sign-off', 'Acceptance testing')]),
           mcq('Integration testing focuses on…', ['interfaces between modules', 'a single function', 'user satisfaction'], 'interfaces between modules'),
           tf('Beta testing is done by selected real users outside the developer.', True)]),

    70: L('Managing an information system covers operation, security, maintenance, backup, change management and evaluation.',
          [('Responsibilities', '<ul><li>Daily operation and support (help desk)</li><li>Security: access control, audits, policies</li><li>Backup and disaster recovery</li><li>Maintenance: corrective, adaptive, perfective, preventive</li><li>Change management and version control</li><li>Performance monitoring and evaluation</li></ul>'),
           ('Roles', table(['Role', 'Job'], [['CIO / IT manager', 'IT strategy'], ['Systems analyst', 'requirements and design'], ['DBA', 'manages databases'], ['Network administrator', 'network and security'], ['Help desk', 'user support']]))],
          [match('Match the role.', [('Designs and tunes the database', 'DBA'), ('Sets the organisation\'s IT strategy', 'CIO'), ('Answers user problems', 'Help desk'), ('Gathers requirements', 'Systems analyst')]),
           match('Match the maintenance type.', [('Fix a calculation bug', 'Corrective'), ('Support a new OS version', 'Adaptive'), ('Add a new report users asked for', 'Perfective')]),
           tf('A disaster recovery plan should be tested regularly.', True)]),

    71: L('A database is an organised collection of related data managed by a DBMS, replacing separate files.',
          [('Hierarchy of data', flow(['Bit', 'Byte', 'Field', 'Record', 'File/Table', 'Database'])),
           ('File approach problems', '<ul><li>Data redundancy and inconsistency</li><li>Program–data dependence</li><li>Difficult sharing and querying</li><li>Weak security and integrity</li></ul>'),
           ('DBMS advantages', '<p>Less redundancy, consistency, data independence, sharing, security, integrity, backup and recovery, concurrent access, query languages.</p>')],
          [order('From smallest to largest.', ['Bit', 'Byte', 'Field', 'Record', 'Table', 'Database']),
           mcq('A student\'s address stored in 3 different files is an example of…', ['data redundancy', 'data independence', 'normalisation'], 'data redundancy'),
           mcq('Changing the storage structure without changing programs is…', ['data independence', 'redundancy', 'a transaction'], 'data independence')]),

    72: L('Database models organise data as hierarchies, networks, relations, objects or documents.',
          [('Models', table(['Model', 'Structure', 'Example'], [['Hierarchical', 'tree: one parent per child', 'IBM IMS, Windows registry'], ['Network', 'graph: many parents (sets)', 'IDMS'], ['Relational', 'tables with keys', 'MySQL, PostgreSQL'], ['Object-oriented', 'objects with methods', 'db4o'], ['NoSQL (document, key-value, graph)', 'flexible schemas', 'MongoDB, Redis, Neo4j']]))],
          [match('Match the model.', [('Tables, rows and keys', 'Relational'), ('Each child has exactly one parent', 'Hierarchical'), ('Records can have many owners', 'Network'), ('JSON-like documents', 'NoSQL document')]),
           mcq('Which model is most used today for business data?', ['Relational', 'Hierarchical', 'Network'], 'Relational'),
           tf('MongoDB is a document database.', True)]),

    73: L('The relational model stores data in relations (tables) of tuples (rows) and attributes (columns), linked by keys.',
          [('Terminology', table(['Formal', 'Informal'], [['Relation', 'table'], ['Tuple', 'row / record'], ['Attribute', 'column / field'], ['Domain', 'allowed values of an attribute'], ['Degree', 'number of attributes'], ['Cardinality', 'number of tuples']])),
           ('Keys', table(['Key', 'Meaning'], [['Super key', 'any set of attributes that identifies a tuple'], ['Candidate key', 'minimal super key'], ['Primary key', 'chosen candidate key'], ['Alternate key', 'other candidate keys'], ['Foreign key', 'refers to a primary key in another table'], ['Composite key', 'key made of two or more attributes']])),
           ('Relational algebra', '<p>SELECT (σ: rows), PROJECT (π: columns), JOIN (⋈), UNION, DIFFERENCE, PRODUCT.</p>')],
          [fill('STUDENT has 5 columns and 120 rows.', 'Degree = {0}, cardinality = {1}', [['5'], ['120']]),
           match('Match the key.', [('Chosen to identify each row', 'Primary key'), ('Links to another table\'s primary key', 'Foreign key'), ('Made of two attributes together', 'Composite key'), ('A candidate key not chosen', 'Alternate key')]),
           match('Relational algebra.', [('Choose certain rows', 'Selection σ'), ('Choose certain columns', 'Projection π'), ('Combine tables on a common attribute', 'Join ⋈')])]),

    74: L('The ANSI-SPARC three-level architecture separates user views, the logical schema and physical storage.',
          [('Three levels', THREE_LEVEL + '<ol><li><b>External</b>: what each user sees</li><li><b>Conceptual</b>: all entities, attributes, relationships, constraints</li><li><b>Internal</b>: files, indexes, storage</li></ol>'),
           ('Independence', '<p><b>Logical data independence</b>: change the conceptual schema without changing views. <b>Physical data independence</b>: change storage without changing the conceptual schema.</p>'),
           ('Architectures', '<p>Centralised, client–server (2-tier / 3-tier: client, application server, DB server), distributed, cloud.</p>')],
          [label('Name the levels.', THREE_LEVEL, ['External level', 'Conceptual level', 'Internal level']),
           mcq('Adding an index without changing programs shows…', ['physical data independence', 'logical data independence', 'redundancy'], 'physical data independence'),
           mcq('Browser → web/app server → database server is a…', ['3-tier architecture', '1-tier architecture', 'hierarchical model'], '3-tier architecture')]),

    75: L('An ER model shows entities, attributes and relationships with cardinality and participation.',
          [('Notation', ER + '<p>Entity (rectangle), relationship (diamond), attributes (ovals), key attributes underlined. Weak entities: double rectangle.</p>'),
           ('Cardinality and participation', '<p>1:1, 1:M, M:N. <b>Total</b> participation (every entity must take part, double line) vs <b>partial</b>.</p>'),
           ('Attribute types', table(['Type', 'Example'], [['Simple', 'age'], ['Composite', 'name (first, last)'], ['Multi-valued', 'phone numbers'], ['Derived', 'age from date of birth']]))],
          [match('Match the attribute type.', [('Phone numbers (several)', 'Multi-valued'), ('Age calculated from DOB', 'Derived'), ('Address = street + town', 'Composite'), ('Matricule', 'Key attribute')]),
           match('Cardinality.', [('A department has many employees; each employee one department', '1 : M'), ('Students enrol in many courses; courses have many students', 'M : N'), ('Each country has one capital', '1 : 1')]),
           tf('A weak entity cannot be identified without its owner entity.', True)]),

    76: L('Turn the ER model into relations: entities become tables, relationships become foreign keys or link tables.',
          [('Mapping rules', table(['ER element', 'Relational design'], [['Strong entity', 'table with its primary key'], ['1 : M', 'foreign key on the "many" side'], ['1 : 1', 'foreign key on either side (often total-participation side)'], ['M : N', 'new link table with both keys (composite PK)'], ['Multi-valued attribute', 'separate table']])),
           ('Example', '<p>STUDENT(<u>StudentID</u>, Name, ClassID*) · CLASS(<u>ClassID</u>, Room) · ENROLMENT(<u>StudentID*, CourseID*</u>, Grade) · COURSE(<u>CourseID</u>, Title)</p><p>* = foreign key</p>')],
          [mcq('M:N between STUDENT and COURSE becomes…', ['a link table ENROLMENT(StudentID, CourseID)', 'a foreign key in STUDENT', 'one merged table'], 'a link table ENROLMENT(StudentID, CourseID)'),
           mcq('CLASS 1 : M STUDENT. Where is the foreign key?', ['ClassID in STUDENT', 'StudentID in CLASS', 'Both'], 'ClassID in STUDENT'),
           mcq('Primary key of ENROLMENT(StudentID, CourseID, Grade)?', ['(StudentID, CourseID)', 'Grade', 'StudentID only'], '(StudentID, CourseID)')]),

    77: L('Normalisation uses functional dependencies to remove redundancy: 1NF, 2NF, 3NF and BCNF.',
          [('Functional dependency', '<p>A → B: each value of A determines exactly one value of B. StudentID → Name.</p>'),
           ('Normal forms', table(['Form', 'Condition'], [['1NF', 'atomic values, no repeating groups'], ['2NF', '1NF + no partial dependency (non-key depends on whole composite key)'], ['3NF', '2NF + no transitive dependency (non-key → non-key)'], ['BCNF', 'every determinant is a candidate key']])),
           ('Example', '<p>ORDERLINE(<u>OrderID, ProductID</u>, Qty, ProductName): ProductID → ProductName is <b>partial</b> → move to PRODUCT(<u>ProductID</u>, ProductName).</p><p>STUDENT(<u>ID</u>, ClassID, ClassRoom): ID → ClassID → ClassRoom is <b>transitive</b> → CLASS(<u>ClassID</u>, ClassRoom).</p>')],
          [match('Which normal form does it violate?', [('A cell holds "Maths, Physics, Chemistry"', '1NF'), ('In (OrderID, ProductID, ProductName), ProductName depends only on ProductID', '2NF'), ('EmpID → DeptID → DeptName in one table', '3NF')]),
           mcq('A → B means…', ['each A value determines one B value', 'A and B are equal', 'B determines A'], 'each A value determines one B value'),
           tf('A relation with a single-attribute primary key in 1NF is automatically in 2NF.', True, 'Partial dependencies need a composite key.')]),

    78: L('Database design moves through requirements, conceptual, logical and physical stages.',
          [('Stages', flow(['Requirements', 'Conceptual (ER)', 'Logical (relations, normalised)', 'Physical (DBMS, types, indexes)', 'Implementation'])),
           ('Physical design decisions', '<ul><li>Data types and sizes</li><li>Indexes for frequent searches</li><li>Storage, partitioning</li><li>Security: users, roles, views</li><li>Denormalisation for performance (carefully)</li></ul>')],
          [order('Order the design stages.', ['Requirements analysis', 'Conceptual design (ER)', 'Logical design', 'Physical design', 'Implementation']),
           match('Which stage?', [('Draw the ER diagram', 'Conceptual design'), ('Normalise relations to 3NF', 'Logical design'), ('Choose VARCHAR(50) and add an index', 'Physical design')]),
           tf('An index speeds up searches but slows down inserts.', True)]),

    79: L('Integrity rules keep data valid: entity integrity, referential integrity, domain and user-defined constraints.',
          [('Integrity types', table(['Rule', 'Meaning'], [['Entity integrity', 'primary key is unique and never NULL'], ['Referential integrity', 'a foreign key must match an existing primary key (or be NULL)'], ['Domain integrity', 'values come from the allowed domain (type, range)'], ['User-defined', 'business rules, e.g. CHECK (mark BETWEEN 0 AND 20)']])),
           ('Referential actions', '<p>When a referenced row is deleted/updated: RESTRICT (refuse), CASCADE (follow), SET NULL.</p>'),
           ('Transactions (ACID)', '<p>Atomicity, Consistency, Isolation, Durability — e.g. a mobile-money transfer debits and credits together or not at all.</p>')],
          [match('Which rule is broken?', [('Two students with the same StudentID', 'Entity integrity'), ('Enrolment for a non-existent course', 'Referential integrity'), ('Mark = 35 when the range is 0–20', 'Domain / CHECK constraint')]),
           mcq('Deleting a class also deletes its students\' class link with…', ['ON DELETE CASCADE', 'ON DELETE RESTRICT', 'PRIMARY KEY'], 'ON DELETE CASCADE'),
           match('ACID.', [('All or nothing', 'Atomicity'), ('Committed changes survive crashes', 'Durability'), ('Concurrent transactions don\'t interfere', 'Isolation'), ('Rules hold before and after', 'Consistency')])]),
}
