"""Upper Sixth Computer Science: C programming, software development, classification of software (lessons 18-37)."""
from helpers import *
from f3_maths_part1 import table
from l6_ict_part5 import code

LESSONS = {
    18: L('To program in C you need an editor, a compiler (gcc) and ideally an IDE. Source → compile → link → run.',
          [('Tools', '<div class="chips"><span>gcc / MinGW</span><span>Code::Blocks</span><span>Dev-C++</span><span>VS Code + gcc</span><span>Online: OnlineGDB</span></div>'),
           ('From source to program', flow([('hello.c', 'source'), ('Preprocess', '#include'), ('Compile', '→ object'), ('Link', 'libraries'), ('hello.exe', 'run')])),
           ('First program', code('#include <stdio.h>\n\nint main(void) {\n    printf("Hello, Cameroon!\\n");\n    return 0;\n}') + '<p>Compile: <code>gcc hello.c -o hello</code> then run <code>./hello</code></p>')],
          [order('Order the build steps.', ['Write source code', 'Preprocess', 'Compile', 'Link', 'Run']),
           mcq('What does #include <stdio.h> provide?', ['Input/output functions like printf and scanf', 'The main function', 'Memory'], 'Input/output functions like printf and scanf'),
           mcq('Every C program starts executing in…', ['main()', 'printf()', 'stdio.h'], 'main()'),
           tf('C is a compiled language.', True)]),

    19: L('Basic C: declare typed variables, read with scanf, print with printf, and calculate with operators.',
          [('Types and format specifiers', table(['Type', 'Example', 'printf/scanf'], [['int', 'int age = 17;', '%d'], ['float', 'float avg = 12.5;', '%f'], ['double', 'double pi = 3.14159;', '%lf'], ['char', "char grade = 'A';", '%c']])),
           ('Input and output', code('int a, b;\nprintf("Enter two numbers: ");\nscanf("%d %d", &a, &b);\nprintf("Sum = %d\\n", a + b);') + '<p class="wt-key">scanf needs the address: &amp;a</p>'),
           ('Operators', '<p>+ − * / % · integer division: 7 / 2 = 3 · 7 % 2 = 1 · 7.0 / 2 = 3.5 · ++, --, +=</p>')],
          [fill('In C, 17 / 5 (both int) =', '{0}', [['3']]),
           fill('In C, 17 % 5 =', '{0}', [['2']]),
           match('Match the format specifier.', [('int', '%d'), ('float', '%f'), ('char', '%c'), ('double (scanf)', '%lf')]),
           mcq('Which line correctly reads an int x?', ['scanf("%d", &x);', 'scanf("%d", x);', 'scanf(x);'], 'scanf("%d", &x);'),
           fill('int x = 5; x += 3; x++; Final x =', '{0}', [['9']])]),

    20: L('Selection in C: if, if–else, else if chains and switch.',
          [('if / else if', code('if (mark >= 16)\n    printf("Very good");\nelse if (mark >= 10)\n    printf("Pass");\nelse\n    printf("Fail");')),
           ('switch', code('switch (day) {\n    case 1: printf("Monday"); break;\n    case 2: printf("Tuesday"); break;\n    default: printf("Other");\n}') + '<p>Without <b>break</b>, execution falls through to the next case.</p>'),
           ('Operators', '<p>== != &lt; &gt; &lt;= &gt;= · &amp;&amp; (and) · || (or) · ! (not). Beware: <code>if (x = 5)</code> assigns!</p>')],
          [mcq('mark = 10. Output?', ['Pass', 'Fail', 'Very good'], 'Pass'),
           mcq('What is wrong with if (x = 5)?', ['It assigns 5 instead of comparing', 'Nothing', 'Missing semicolon'], 'It assigns 5 instead of comparing'),
           mcq('In a switch, a missing break causes…', ['fall-through to the next case', 'a compile error', 'an infinite loop'], 'fall-through to the next case'),
           mcq('(x > 0 && x < 10) with x = 10 is…', ['false', 'true'], 'false')]),

    21: L('Iteration in C: for, while and do–while.',
          [('Three loops', code('for (int i = 1; i <= 5; i++) sum += i;      // count-controlled\n\nwhile (n != 0) { ... }                       // test first\n\ndo { scanf("%d", &m); } while (m < 0 || m > 20);   // runs at least once')),
           ('Example', code('int n = 5, fact = 1;\nfor (int i = 1; i <= n; i++)\n    fact *= i;\nprintf("%d", fact);   // 120')),
           ('Control', '<p><b>break</b> exits the loop · <b>continue</b> skips to the next iteration.</p>')],
          [fill('for (i = 0; i < 10; i += 2) runs how many times?', '{0}', [['5']]),
           fill('int s = 0; for (i = 1; i <= 4; i++) s += i * i; s =', '{0}', [['30']]),
           mcq('Which loop always executes its body at least once?', ['do–while', 'while', 'for'], 'do–while'),
           fill('int k = 1; while (k < 100) k *= 3; Final k =', '{0}', [['243']], '1 → 3 → 9 → 27 → 81 → 243')]),

    22: L('C strings are char arrays ending with \'\\0\'. Use <string.h> functions to handle them.',
          [('Strings', code('char name[20] = "Awa";   // A w a \\0\nprintf("%s has %lu letters", name, strlen(name));')),
           ('string.h', table(['Function', 'Does'], [['strlen(s)', 'length (without \\0)'], ['strcpy(d, s)', 'copy s into d'], ['strcat(d, s)', 'append s to d'], ['strcmp(a, b)', '0 if equal, <0 or >0 otherwise']])),
           ('Characters', '<p>&lt;ctype.h&gt;: toupper, tolower, isdigit, isalpha. Characters are numbers: \'A\' = 65, \'a\' − \'A\' = 32.</p>')],
          [fill('strlen("Bamenda") =', '{0}', [['7']]),
           fill('char s[] = "CAT"; how many bytes does s occupy?', '{0}', [['4']], '3 letters + \\0'),
           mcq('strcmp("abc", "abc") returns…', ['0', '1', '-1'], '0'),
           fill('In C, \'A\' + 2 is the character', '{0}', [['C']]),
           mcq('Why not compare strings with ==?', ['It compares addresses, not contents', 'It is slower', 'It is not allowed'], 'It compares addresses, not contents')]),

    23: L('A 1D array stores many values of the same type. Loop through it with an index from 0 to n − 1.',
          [('Declare and use', code('int marks[5] = {12, 15, 9, 18, 14};\nint total = 0, max = marks[0];\nfor (int i = 0; i < 5; i++) {\n    total += marks[i];\n    if (marks[i] > max) max = marks[i];\n}\nprintf("Avg %.2f, max %d", total / 5.0, max);')),
           ('Watch out', '<ul><li>Indices go from 0 to size − 1</li><li>C does not check bounds: marks[5] is a bug (undefined behaviour)</li><li>Arrays are passed to functions as pointers</li></ul>')],
          [fill('Using the array above: total =', '{0}', [['68']]),
           fill('Average (2 decimals) =', '{0}', [['13.60', '13.6']]),
           fill('int a[4] = {3, 7, 1, 9}; a[2] =', '{0}', [['1']]),
           mcq('Valid indices for int a[10] are…', ['0 to 9', '1 to 10', '0 to 10'], '0 to 9')]),

    24: L('A 2D array is a table: rows × columns. Use nested loops.',
          [('Declare', code('int m[2][3] = {{1, 2, 3},\n               {4, 5, 6}};\n// m[1][2] is row 1, column 2 = 6')),
           ('Nested loops', code('int sum = 0;\nfor (int r = 0; r < 2; r++)\n    for (int c = 0; c < 3; c++)\n        sum += m[r][c];\nprintf("%d", sum);   // 21')),
           ('Uses', '<p>Mark sheets (students × subjects), matrices, game boards, images (pixels).</p>')],
          [fill('m[0][1] =', '{0}', [['2']]),
           fill('int t[3][4] has how many elements?', '{0}', [['12']]),
           fill('Sum of row 1 of m (4, 5, 6) =', '{0}', [['15']]),
           mcq('To visit every element of a 2D array you usually use…', ['two nested loops', 'one loop', 'a switch'], 'two nested loops')]),

    25: L('A struct (record) groups fields of different types. Arrays of structs or linked lists store many records.',
          [('struct', code('struct Student {\n    char name[30];\n    int age;\n    float avg;\n};\nstruct Student s = {"Awa", 17, 14.5};\nprintf("%s %.1f", s.name, s.avg);')),
           ('Array of records', code('struct Student cls[40];\ncls[0].age = 16;')),
           ('Linked list', code('struct Node {\n    int data;\n    struct Node *next;   // pointer to the next node\n};') + '<p>Grows dynamically with <code>malloc</code>; the last node points to NULL.</p>')],
          [mcq('Access the age field of struct s:', ['s.age', 's->age', 'age.s'], 's.age'),
           mcq('With a pointer p to a struct, access age with…', ['p->age', 'p.age', '*p.age'], 'p->age'),
           mcq('The last node of a linked list points to…', ['NULL', 'the first node always', 'itself'], 'NULL'),
           tf('A struct can contain fields of different types.', True)]),

    26: L('Functions (subroutines) break a C program into reusable parts. Parameters are passed by value, or by address with pointers.',
          [('A function', code('int square(int x) {\n    return x * x;\n}\n\nint main(void) {\n    printf("%d", square(6));   // 36\n}')),
           ('By value vs by reference', code('void swap(int *a, int *b) {\n    int t = *a; *a = *b; *b = t;\n}\n// call: swap(&x, &y);') + '<p>Passing by value copies the argument; passing a pointer lets the function change the caller\'s variable.</p>'),
           ('Prototypes and scope', '<p>Declare before use: <code>int square(int);</code> · <code>void</code> functions return nothing · local variables exist only inside the function.</p>')],
          [fill('int cube(int n) { return n*n*n; } cube(3) =', '{0}', [['27']]),
           mcq('Why does swap need pointers?', ['To change the caller\'s variables', 'To make it faster', 'Because ints cannot be returned'], 'To change the caller\'s variables'),
           mcq('A function that returns nothing has return type…', ['void', 'int', 'null'], 'void'),
           fill('int f(int a){ a = a + 10; return a; } int x = 5; f(x); After the call, x =', '{0}', [['5']], 'x was passed by value.')]),

    28: L('Software development activities — specification, design, implementation, validation, evolution — are organised by process models.',
          [('Activities', table(['Activity', 'Output'], [['Specification', 'requirements document'], ['Design', 'architecture, data, interface designs'], ['Implementation', 'code'], ['Validation', 'tested system'], ['Evolution', 'maintained, updated system']])),
           ('Models', table(['Model', 'Best when'], [['Waterfall', 'stable, well-understood requirements'], ['V-model', 'safety-critical, testing planned early'], ['Incremental', 'deliver core features first'], ['Spiral', 'large, high-risk projects'], ['Agile / Scrum', 'changing requirements, close customer contact'], ['RAD / prototyping', 'UI-heavy systems, fast delivery']]))],
          [match('Best model.', [('Medical device software with strict verification', 'V-model'), ('Start-up app with changing requirements', 'Agile'), ('Large risky defence project', 'Spiral'), ('Small system with fixed, clear requirements', 'Waterfall')]),
           order('Order the generic activities.', ['Specification', 'Design', 'Implementation', 'Validation', 'Evolution']),
           tf('In Scrum, work is done in short iterations called sprints.', True)]),

    29: L('Requirements analysis finds out what the system must do (functional) and how well (non-functional), and records it in a specification.',
          [('Types', '<div class="two-col"><div><b>Functional</b>"The system shall print a report card"</div><div><b>Non-functional</b>performance, security, usability, reliability: "respond in under 2 s"</div></div>'),
           ('Elicitation', '<p>Interviews, questionnaires, observation, document study, workshops, prototypes, use cases.</p>'),
           ('SRS', '<p>Software Requirements Specification: complete, consistent, unambiguous, verifiable, traceable. Use cases / user stories: "As a teacher, I want to enter marks so that…"</p>')],
          [sort('Functional or non-functional?', ['Functional', 'Non-functional'], [('Calculate the class average', 'Functional'), ('Load any page in under 2 seconds', 'Non-functional'), ('Send SMS to parents', 'Functional'), ('Available 99.9% of the time', 'Non-functional'), ('Passwords stored encrypted', 'Non-functional')]),
           mcq('A good requirement must be…', ['verifiable (testable)', 'vague', 'secret'], 'verifiable (testable)'),
           mcq('"As a student, I want to see my marks so that I can track progress" is a…', ['user story', 'test case', 'class diagram'], 'user story')]),

    30: L('Design moves from architecture to detailed design, documented with diagrams and specifications.',
          [('Stages', flow(['Architectural design', 'Interface design', 'Component design', 'Data design', 'Detailed design'])),
           ('Documentation', table(['Tool', 'Shows'], [['Structure chart', 'module hierarchy'], ['DFD', 'data movement'], ['ER diagram', 'data structure'], ['UML class / sequence', 'objects and interactions'], ['Pseudocode', 'algorithms'], ['Wireframes', 'screen layouts']])),
           ('Principles', '<p>Modularity, abstraction, information hiding, high cohesion, low coupling.</p>')],
          [order('Order the design stages.', ['Architectural design', 'Interface design', 'Component design', 'Detailed design']),
           match('Match the diagram.', [('Order of messages between objects', 'Sequence diagram'), ('Screen layout sketch', 'Wireframe'), ('Entities and relationships', 'ER diagram'), ('Movement of data', 'DFD')]),
           mcq('Good modular design aims for…', ['high cohesion and low coupling', 'low cohesion and high coupling', 'one big module'], 'high cohesion and low coupling')]),

    31: L('Software tools support each stage: CASE tools, IDEs, version control, testing and project tools.',
          [('Tools', table(['Tool', 'Example', 'Use'], [['Upper CASE', 'StarUML, draw.io', 'analysis and design diagrams'], ['Lower CASE / IDE', 'VS Code, Code::Blocks', 'coding, debugging'], ['Version control', 'Git, GitHub', 'track changes, teamwork'], ['Testing', 'unit test frameworks', 'automated tests'], ['Project management', 'Trello, Jira, MS Project', 'tasks, schedules'], ['Documentation', 'Doxygen, wikis', 'manuals']])),
           ('Git basics', code('git add .\ngit commit -m "Add login form"\ngit push'))],
          [match('Match the tool.', [('Git', 'Version control'), ('StarUML', 'Design diagrams (CASE)'), ('Trello', 'Task management'), ('Debugger', 'Finding runtime errors')]),
           order('Order the Git commands to save and share work.', ['git add', 'git commit', 'git push']),
           tf('Version control lets a team go back to earlier versions of code.', True)]),

    32: L('Quality software is correct, reliable, efficient, usable, maintainable and portable. Acquire and evaluate it carefully.',
          [('Quality factors', table(['Factor', 'Meaning'], [['Correctness', 'meets the specification'], ['Reliability', 'works without failure'], ['Efficiency', 'uses little time/memory'], ['Usability', 'easy to learn and use'], ['Maintainability', 'easy to fix and change'], ['Portability', 'runs on other platforms']])),
           ('Acquisition', '<p>Build in-house, outsource, buy off-the-shelf, open source, SaaS subscription.</p>'),
           ('Evaluation criteria', '<p>Requirements fit, cost (licence + training + support), compatibility, vendor support, security, user reviews, trial period.</p>')],
          [match('Match the quality factor.', [('Runs on Windows and Linux', 'Portability'), ('New staff learn it in a day', 'Usability'), ('Easy to fix bugs', 'Maintainability'), ('Never crashes during exams', 'Reliability')]),
           mcq('A school rents online software paid monthly. This is…', ['SaaS', 'bespoke in-house', 'freeware'], 'SaaS'),
           tf('Total cost includes training and support, not just the licence.', True)]),

    33: L('Verification: "Are we building the product right?" Validation: "Are we building the right product?"',
          [('V &amp; V', '<div class="two-col"><div><b>Verification</b>reviews, inspections, walkthroughs, static analysis</div><div><b>Validation</b>testing with users, acceptance testing</div></div>'),
           ('Testing levels and methods', table(['', 'Examples'], [['Levels', 'unit → integration → system → acceptance'], ['Black box', 'equivalence partitioning, boundary value analysis'], ['White box', 'statement and branch coverage'], ['Others', 'regression, alpha, beta, performance, security']])),
           ('Boundary values', '<p>Valid range 1–100 → test 0, 1, 2, 99, 100, 101.</p>')],
          [match('Verification or validation?', [('Code inspection meeting', 'Verification'), ('Users try the system for acceptance', 'Validation')]),
           sort('Valid range 18–60. Which are boundary test values?', ['Boundary', 'Not boundary'], [('17', 'Boundary'), ('18', 'Boundary'), ('60', 'Boundary'), ('35', 'Not boundary'), ('61', 'Boundary')]),
           mcq('Testing every branch of an IF statement is…', ['white-box (branch coverage)', 'black-box', 'acceptance testing'], 'white-box (branch coverage)'),
           order('Order the testing levels.', ['Unit', 'Integration', 'System', 'Acceptance'])]),

    34: L('Project management plans scope, time, cost and quality, using tools like Gantt charts and critical path analysis.',
          [('Triple constraint', '<p>Scope, time, cost — change one and the others are affected; quality in the middle.</p>'),
           ('Planning tools', '<ul><li><b>WBS</b>: break work into tasks</li><li><b>Gantt chart</b>: tasks on a timeline</li><li><b>PERT / CPM</b>: dependencies; the <b>critical path</b> is the longest path — any delay on it delays the project</li></ul>'),
           ('CPM example', '<p>A (3 days) → B (4) → D (2); A → C (2) → D. Paths: A-B-D = 9, A-C-D = 7 → critical path <b>A-B-D, 9 days</b>.</p>'),
           ('Reporting', '<p>Progress reports, milestones, risk register, final report.</p>')],
          [fill('Paths: P-Q-S = 3 + 5 + 2, P-R-S = 3 + 6 + 2. Project duration =', '{0} days', [['11']]),
           mcq('A task on the critical path is delayed by 2 days. The project…', ['is delayed by 2 days', 'is not affected', 'finishes earlier'], 'is delayed by 2 days'),
           match('Match the tool.', [('Tasks as bars on a timeline', 'Gantt chart'), ('Hierarchy of all work packages', 'WBS'), ('Longest chain of dependent tasks', 'Critical path')])]),

    35: L('Reuse saves effort, teamwork needs roles and communication, and maintenance keeps software useful.',
          [('Maintenance types', table(['Type', 'Purpose'], [['Corrective', 'fix bugs'], ['Adaptive', 'adapt to new environment (OS, law)'], ['Perfective', 'improve performance / add features'], ['Preventive', 'refactor to avoid future problems']])),
           ('Teamwork', '<p>Roles: project manager, analyst, designer, programmers, tester, technical writer. Practices: code reviews, pair programming, stand-up meetings, shared repositories.</p>'),
           ('Reuse', '<p>Libraries, frameworks, components, design patterns, APIs.</p>')],
          [match('Match the maintenance type.', [('Fix a crash on login', 'Corrective'), ('Update for a new tax law', 'Adaptive'), ('Add a dark mode', 'Perfective'), ('Clean up messy code', 'Preventive')]),
           mcq('Two programmers working at one computer is…', ['pair programming', 'outsourcing', 'regression testing'], 'pair programming'),
           tf('Most of a software system\'s lifetime cost is usually maintenance.', True)]),

    37: L('Software is classified by function (system/application), licence, development (bespoke/off-the-shelf) and deployment.',
          [('Classifications', table(['Basis', 'Categories'], [['Function', 'system software, application software, programming tools'], ['Licence', 'proprietary, open source, freeware, shareware, public domain'], ['Development', 'bespoke, off-the-shelf, customised'], ['Deployment', 'desktop, web, mobile, cloud/SaaS, embedded']])),
           ('Open-source licences', '<p>GPL (copyleft: derivatives must stay open), MIT/BSD (permissive).</p>')],
          [sort('Classify by licence.', ['Proprietary', 'Open source'], [('Windows', 'Proprietary'), ('Linux', 'Open source'), ('MS Office', 'Proprietary'), ('LibreOffice', 'Open source')]),
           mcq('A GPL licence requires that modified versions…', ['are also released as open source', 'are sold', 'are deleted'], 'are also released as open source'),
           match('Match the deployment.', [('Runs in a browser', 'Web application'), ('Installed on a phone', 'Mobile app'), ('Runs inside a microwave', 'Embedded software'), ('Paid monthly, hosted online', 'SaaS')])]),
}
