"""Upper Sixth Computer Science: SQL, architecture, projects, networks, theory (lessons 81-103)."""
from helpers import *
from f3_maths_part1 import table
from l6_ict_part5 import code

STU = table(['ID', 'Name', 'ClassID', 'Mark'], [['1', 'Awa', 'A', '15'], ['2', 'Paul', 'B', '9'], ['3', 'Ngum', 'A', '18'], ['4', 'Eric', 'B', '12'], ['5', 'Bih', 'C', '11']])
CLS = table(['ClassID', 'Room'], [['A', 'R1'], ['B', 'R2'], ['D', 'R4']])

OSI = svg(440, 230, ''.join(
    box(40, 8 + i * 31, 170, 27, n, '', ('v-box', 'v-box2', 'v-box3')[i % 3], 6) + f'<text x="225" y="{26 + i * 31}" class="v-s">{e}</text>'
    for i, (n, e) in enumerate([('7 Application', 'HTTP, SMTP, DNS'), ('6 Presentation', 'encryption, formats'), ('5 Session', 'sessions'), ('4 Transport', 'TCP, UDP'), ('3 Network', 'IP, routers'), ('2 Data link', 'MAC, switches'), ('1 Physical', 'cables, signals')])), 'OSI model')

FSM = svg(420, 150, ''.join([
    '<circle cx="110" cy="75" r="36" class="v-box2"/><circle cx="110" cy="75" r="30" class="v-line" style="fill:none"/><text x="110" y="80" text-anchor="middle" class="v-t">Even</text>',
    '<circle cx="310" cy="75" r="36" class="v-box"/><text x="310" y="80" text-anchor="middle" class="v-t">Odd</text>',
    '<path d="M 140 55 Q 210 15 280 55" class="v-arrow" style="fill:none"/><text x="210" y="28" text-anchor="middle" class="v-s">1</text>',
    '<path d="M 280 95 Q 210 135 140 95" class="v-arrow" style="fill:none"/><text x="210" y="140" text-anchor="middle" class="v-s">1</text>',
    '<text x="60" y="30" class="v-s">0 (stay)</text><text x="330" y="30" class="v-s">0 (stay)</text>',
    arrow(20, 75, 74, 75),
]), 'Finite state machine: even number of 1s')

LESSONS = {
    81: L('DDL (Data Definition Language) creates and changes the structure of a database: CREATE, ALTER, DROP.',
          [('CREATE TABLE', code('CREATE TABLE Class (\n  ClassID CHAR(1) PRIMARY KEY,\n  Room    VARCHAR(10) NOT NULL\n);\n\nCREATE TABLE Student (\n  ID      INT PRIMARY KEY,\n  Name    VARCHAR(40) NOT NULL,\n  ClassID CHAR(1),\n  Mark    INT CHECK (Mark BETWEEN 0 AND 20),\n  FOREIGN KEY (ClassID) REFERENCES Class(ClassID)\n);')),
           ('ALTER and DROP', code('ALTER TABLE Student ADD Phone VARCHAR(15);\nALTER TABLE Student DROP COLUMN Phone;\nDROP TABLE Student;    -- deletes structure AND data')),
           ('Constraints', '<p>PRIMARY KEY, FOREIGN KEY, NOT NULL, UNIQUE, CHECK, DEFAULT.</p>')],
          [match('Match the command.', [('Make a new table', 'CREATE TABLE'), ('Add a column', 'ALTER TABLE … ADD'), ('Delete a table completely', 'DROP TABLE')]),
           match('Match the constraint.', [('Value must be given', 'NOT NULL'), ('No two rows may share the value', 'UNIQUE'), ('Mark between 0 and 20', 'CHECK'), ('Must match a key in another table', 'FOREIGN KEY')]),
           tf('DROP TABLE removes both the table structure and its data.', True)]),

    82: L('DML (Data Manipulation Language) changes the data: INSERT, UPDATE, DELETE.',
          [('Commands', code("INSERT INTO Student (ID, Name, ClassID, Mark)\nVALUES (6, 'Tani', 'A', 14);\n\nUPDATE Student SET Mark = Mark + 1 WHERE ClassID = 'B';\n\nDELETE FROM Student WHERE Mark < 5;")),
           ('Danger', '<p class="wt-key">UPDATE or DELETE without WHERE affects EVERY row!</p>'),
           ('Transactions', code('START TRANSACTION;\nUPDATE Account SET Bal = Bal - 5000 WHERE No = 1;\nUPDATE Account SET Bal = Bal + 5000 WHERE No = 2;\nCOMMIT;   -- or ROLLBACK;'))],
          [mcq('Which adds a new row?', ["INSERT INTO Student VALUES (7, 'Lum', 'C', 13);", "UPDATE Student ADD 7;", "CREATE ROW Student 7;"], "INSERT INTO Student VALUES (7, 'Lum', 'C', 13);"),
           fill('Using the table, UPDATE Student SET Mark = Mark + 2 WHERE ClassID = \'B\'. Paul\'s mark becomes', '{0}', [['11']], visual=STU),
           fill('DELETE FROM Student WHERE Mark < 12 removes how many rows from the table?', '{0}', [['2']], 'Paul (9) and Bih (11).', visual=STU),
           mcq('What does DELETE FROM Student; (no WHERE) do?', ['Deletes every row', 'Deletes the table structure', 'Nothing'], 'Deletes every row')]),

    83: L('DQL: SELECT retrieves data with filters (WHERE), sorting (ORDER BY) and pattern matching (LIKE).',
          [('The table', STU),
           ('SELECT', code("SELECT Name, Mark FROM Student\nWHERE Mark >= 12 AND ClassID = 'A'\nORDER BY Mark DESC;") + '<p>→ Ngum 18, Awa 15</p>'),
           ('Operators', '<p>=, &lt;&gt;, &lt;, &gt;, BETWEEN 10 AND 15, IN (\'A\', \'C\'), LIKE \'A%\' (starts with A), IS NULL, DISTINCT.</p>')],
          [fill('SELECT COUNT(*) FROM Student WHERE Mark BETWEEN 10 AND 15 returns', '{0}', [['3']], 'Awa 15, Eric 12, Bih 11', visual=STU),
            mcq("SELECT Name FROM Student WHERE Name LIKE 'B%' returns…", ['Bih', 'Awa', 'Paul'], 'Bih'),
            fill('SELECT DISTINCT ClassID FROM Student returns how many rows?', '{0}', [['3']]),
            mcq('Which sorts from lowest to highest mark?', ['ORDER BY Mark ASC', 'ORDER BY Mark DESC', 'SORT BY Mark'], 'ORDER BY Mark ASC')]),

    84: L('Joins combine rows from tables using matching keys.',
          [('Tables', STU + CLS),
           ('Join types', table(['Join', 'Returns'], [['INNER JOIN', 'only rows with a match in both tables'], ['LEFT JOIN', 'all rows of the left table, NULL where no match'], ['RIGHT JOIN', 'all rows of the right table'], ['FULL OUTER JOIN', 'all rows of both']])),
           ('Example', code('SELECT s.Name, c.Room\nFROM Student s\nINNER JOIN Class c ON s.ClassID = c.ClassID;') + '<p>Bih (class C) has no matching class → not in the INNER JOIN result.</p>')],
          [fill('How many rows does the INNER JOIN return?', '{0}', [['4']]),
           fill('How many rows does Student LEFT JOIN Class return?', '{0}', [['5']], 'All 5 students; Bih gets Room = NULL.'),
           mcq('Which class row never appears in an INNER JOIN with Student?', ['D', 'A', 'B'], 'D'),
           mcq('The ON clause specifies…', ['the matching condition', 'the sort order', 'the table name only'], 'the matching condition')]),

    85: L('Aggregate functions summarise many rows: COUNT, SUM, AVG, MIN, MAX — often with GROUP BY and HAVING.',
          [('The table', STU),
           ('GROUP BY', code('SELECT ClassID, COUNT(*) AS n, AVG(Mark) AS avg\nFROM Student\nGROUP BY ClassID\nHAVING COUNT(*) >= 2;') + table(['ClassID', 'n', 'avg'], [['A', '2', '16.5'], ['B', '2', '10.5']])),
           ('WHERE vs HAVING', '<p><b>WHERE</b> filters rows before grouping; <b>HAVING</b> filters groups after aggregation.</p>')],
          [fill('SELECT SUM(Mark) FROM Student =', '{0}', [['65']]),
           fill('SELECT AVG(Mark) FROM Student =', '{0}', [['13']]),
           fill('SELECT MAX(Mark) - MIN(Mark) FROM Student =', '{0}', [['9']]),
           mcq('To keep only groups with an average above 12 use…', ['HAVING AVG(Mark) > 12', 'WHERE AVG(Mark) > 12', 'ORDER BY AVG(Mark)'], 'HAVING AVG(Mark) > 12')]),

    86: L('RDBMS packages implement the relational model. Choose one and implement the design with users and privileges.',
          [('Packages', table(['RDBMS', 'Notes'], [['MySQL / MariaDB', 'open source, web (LAMP)'], ['PostgreSQL', 'open source, advanced features'], ['SQLite', 'embedded in apps, single file'], ['Oracle', 'enterprise'], ['SQL Server', 'Microsoft enterprise'], ['MS Access', 'desktop, forms and reports']])),
           ('Implementation steps', '<ol><li>Create database and tables (DDL)</li><li>Add constraints and indexes</li><li>Load data</li><li>Create users and roles, GRANT privileges</li><li>Build forms, reports, queries</li><li>Back up</li></ol>' + code("CREATE USER 'teacher'@'localhost' IDENTIFIED BY '••••';\nGRANT SELECT, UPDATE ON school.Student TO 'teacher'@'localhost';"))],
          [match('Best RDBMS.', [('Database inside a mobile app', 'SQLite'), ('Free database for a PHP website', 'MySQL'), ('Small office with forms, no server', 'MS Access')]),
           mcq('GRANT SELECT ON Student TO teacher allows the teacher to…', ['read Student data', 'delete the table', 'create users'], 'read Student data'),
           mcq('Which command removes a privilege?', ['REVOKE', 'DROP', 'DELETE'], 'REVOKE')]),

    87: L('Web applications connect forms to databases through server-side code; object-oriented programs map objects to tables.',
          [('Web flow', flow(['HTML form', 'HTTP POST', 'Server script (PHP/Python)', 'SQL query', 'Database', 'HTML response'])),
           ('Prepared statements', code('$stmt = $pdo->prepare("INSERT INTO Student (Name, Mark) VALUES (?, ?)");\n$stmt->execute([$_POST["name"], $_POST["mark"]]);') + '<p class="wt-key">Never paste user input directly into SQL: that allows SQL injection.</p>'),
           ('OO integration', '<p><b>ORM</b> (object-relational mapping) maps classes to tables and objects to rows (Django ORM, Hibernate). Object databases and JSON columns store objects directly.</p>')],
          [order('Order the web request.', ['User submits the HTML form', 'Server script receives the data', 'Script runs an SQL query', 'Database returns results', 'Server sends an HTML page back']),
           mcq('Typing \' OR \'1\'=\'1 into a login box to bypass it is…', ['SQL injection', 'phishing', 'normalisation'], 'SQL injection'),
           mcq('Best defence against SQL injection?', ['Prepared (parameterised) statements', 'Longer passwords', 'More RAM'], 'Prepared (parameterised) statements'),
           tf('An ORM maps classes to tables.', True)]),

    89: L('Computer architecture: CPU, memory and I/O connected by buses; performance depends on clock, cores, cache, bus width and pipelining.',
          [('Buses', table(['Bus', 'Width effect'], [['Address bus (n bits)', '2ⁿ addressable locations — 32 bits → 4 GiB'], ['Data bus', 'bits moved per transfer (word size)'], ['Control bus', 'read/write, clock, interrupt signals']])),
           ('Performance', '<ul><li>Clock speed (GHz)</li><li>Number of cores (parallel tasks)</li><li>Cache size and levels (L1, L2, L3)</li><li>Word length / bus width</li><li><b>Pipelining</b>: overlap fetch, decode, execute of several instructions</li></ul>'),
           ('Architectures', '<p>Von Neumann (shared memory and bus) vs Harvard (separate instruction and data memories — used in microcontrollers, DSPs).</p>')],
          [fill('A 16-bit address bus can address how many locations?', '{0}', [['65536']]),
           fill('A 20-bit address bus addresses how many MiB (1 MiB = 2²⁰ bytes)?', '{0}', [['1']]),
           mcq('Pipelining improves performance by…', ['overlapping stages of several instructions', 'increasing clock speed', 'adding RAM'], 'overlapping stages of several instructions'),
           mcq('Separate memories for instructions and data is the…', ['Harvard architecture', 'von Neumann architecture', 'RISC architecture'], 'Harvard architecture')]),

    90: L('The instruction set architecture defines instructions, formats, registers and addressing modes used by machine and assembly code.',
          [('Instruction format', '<p><b>Opcode</b> (what to do) + <b>operand</b> (data or address). 8-bit instruction with 3-bit opcode → 2³ = 8 instructions, 5-bit operand → 32 addresses.</p>'),
           ('Addressing modes', table(['Mode', 'Example', 'Meaning'], [['Immediate', 'LDA #5', 'the value 5 itself'], ['Direct', 'LDA 20', 'value stored at address 20'], ['Indirect', 'LDA (20)', 'address 20 holds the address of the value'], ['Indexed', 'LDA 20,X', 'address 20 + index register']])),
           ('Trace', code('LDA #5      ; ACC <- 5\nADD 10      ; ACC <- ACC + [10]   ([10] = 7)\nSTO 11      ; [11] <- ACC') + '<p>→ memory 11 = <b>12</b></p>')],
          [fill('Memory: [20] = 30, [30] = 8. LDA 20 loads', '{0}', [['30']]),
           fill('Same memory. LDA (20) (indirect) loads', '{0}', [['8']]),
           fill('LDA #20 loads', '{0}', [['20']]),
           fill('Opcode field of 4 bits allows how many different instructions?', '{0}', [['16']]),
           match('Match the mode.', [('Operand is the actual value', 'Immediate'), ('Operand is the address of the value', 'Direct'), ('Operand points to the address of the value', 'Indirect'), ('Address + index register', 'Indexed')])]),

    91: L('Project: simulate the fetch–decode–execute cycle and memory in C.',
          [('Model', code('int mem[32];          // memory\nint PC = 0, ACC = 0;   // registers\nint running = 1;\nwhile (running) {\n    int instr = mem[PC++];          // FETCH\n    int op = instr / 100, addr = instr % 100;  // DECODE\n    switch (op) {                    // EXECUTE\n        case 1: ACC = mem[addr]; break;        // LOAD\n        case 2: ACC += mem[addr]; break;       // ADD\n        case 3: mem[addr] = ACC; break;        // STORE\n        case 0: running = 0; break;            // HALT\n    }\n}')),
           ('Program in memory', table(['Address', 'Content', 'Meaning'], [['0', '110', 'LOAD 10'], ['1', '211', 'ADD 11'], ['2', '312', 'STORE 12'], ['3', '000', 'HALT'], ['10', '4', 'data'], ['11', '9', 'data']])),
           ('Extensions', '<p>Add SUB, JUMP, JUMPZ; print registers each cycle; count cycles.</p>')],
          [fill('After the program runs, mem[12] =', '{0}', [['13']]),
           fill('How many instructions are fetched (including HALT)?', '{0}', [['4']]),
           fill('Decode instruction 211.', 'opcode {0}, address {1}', [['2'], ['11']]),
           mcq('Which line performs the FETCH?', ['int instr = mem[PC++];', 'case 3: mem[addr] = ACC;', 'running = 0;'], 'int instr = mem[PC++];')]),

    92: L('Lab: manipulate registers with assembly-style operations — arithmetic, shifts and bitwise masks.',
          [('Shifts', '<p>Logical shift left by 1 multiplies by 2: 00000101 (5) → 00001010 (10). Shift right divides by 2: 00010100 (20) → 00001010 (10).</p>'),
           ('Masks', table(['Operation', 'Use', 'Example'], [['AND', 'clear / test bits', '1011 0110 AND 0000 1111 = 0000 0110'], ['OR', 'set bits', '1000 0000 OR 0000 0011 = 1000 0011'], ['XOR', 'toggle bits', '1010 XOR 1111 = 0101']])),
           ('In C', code('unsigned char r = 0x2D;   // 0010 1101\nr = r << 1;               // 0101 1010\nr = r & 0x0F;             // 0000 1010\nprintf("%d", r);          // 10'))],
          [fill('Shift 00000110 left by 2. Result in denary =', '{0}', [['24']]),
           fill('1100 1010 AND 0000 1111 =', '{0}', [['00001010', '0000 1010']]),
           fill('0101 XOR 0011 =', '{0}', [['0110']]),
           mcq('To set bit 0 without changing others, use…', ['OR with 00000001', 'AND with 00000001', 'XOR with 11111111'], 'OR with 00000001')]),

    93: L('C foundations for data structures: pointers, dynamic memory and linked structures.',
          [('Pointers', code('int x = 10;\nint *p = &x;   // p holds the address of x\n*p = 20;       // x is now 20')),
           ('Dynamic memory', code('int *arr = malloc(n * sizeof(int));\nif (arr == NULL) { /* out of memory */ }\n...\nfree(arr);     // avoid memory leaks')),
           ('Stack with an array', code('int stack[MAX], top = -1;\nvoid push(int v) { if (top < MAX - 1) stack[++top] = v; }\nint  pop(void)   { return (top >= 0) ? stack[top--] : -1; }'))],
          [fill('int x = 5; int *p = &x; *p = *p * 3; x =', '{0}', [['15']]),
           mcq('Forgetting to call free() causes…', ['a memory leak', 'a syntax error', 'faster programs'], 'a memory leak'),
           fill('Stack: push(4), push(9), pop(), push(2). top index =', '{0}', [['1']], 'top: −1 → 0 → 1 → 0 → 1'),
           mcq('&x gives…', ['the address of x', 'the value of x', 'x squared'], 'the address of x')]),

    94: L('Review: the OS manages processes, memory, files, I/O and security; system software supports programs.',
          [('Summary', table(['Area', 'Key ideas'], [['Processes', 'states, PCB, scheduling (FCFS, SJF, RR, priority), synchronisation, deadlock'], ['Memory', 'partitions, paging, segmentation, virtual memory, page replacement'], ['Files', 'directories, allocation, permissions'], ['I/O', 'drivers, buffering, spooling, interrupts, DMA'], ['Security', 'authentication, access control, logs']]))],
          [match('Match the concept to the area.', [('Round robin', 'Process scheduling'), ('LRU', 'Page replacement'), ('i-node', 'File system'), ('DMA', 'I/O management')]),
           mcq('The four deadlock conditions include…', ['circular wait', 'paging', 'spooling'], 'circular wait'),
           mcq('Which reduces external fragmentation?', ['Paging', 'Contiguous allocation', 'Polling'], 'Paging')]),

    95: L('Project: build a data indexing and search module in C — sorted index, binary search and hashing.',
          [('Index + binary search', code('typedef struct { int key; int pos; } Index;\n\nint bsearch_idx(Index idx[], int n, int key) {\n    int lo = 0, hi = n - 1;\n    while (lo <= hi) {\n        int mid = (lo + hi) / 2;\n        if (idx[mid].key == key) return idx[mid].pos;\n        if (idx[mid].key < key) lo = mid + 1; else hi = mid - 1;\n    }\n    return -1;\n}')),
           ('Hash table', code('#define SIZE 11\nint h(int key) { return key % SIZE; }\n// linear probing: if slot taken, try (h + 1) % SIZE, ...'))],
          [fill('Keys 10, 22, 31 inserted with h = key % 11 and linear probing. 22 goes to slot', '{0}', [['0']], '22 % 11 = 0'),
           fill('Then 33 (33 % 11 = 0, slot taken) goes to slot', '{0}', [['1']]),
           fill('Binary search on 15 sorted keys needs at most how many comparisons?', '{0}', [['4']]),
           mcq('Why keep a separate sorted index?', ['To search fast without moving the large records', 'To save keys', 'To avoid using C'], 'To search fast without moving the large records')]),

    96: L('Project: simulate CPU scheduling and memory allocation, and compare results.',
          [('FCFS vs SJF', '<p>Jobs (all arrive at 0): P1 = 5, P2 = 3, P3 = 8.</p>' + table(['Algorithm', 'Order', 'Waiting times', 'Average'], [['FCFS', 'P1, P2, P3', '0, 5, 8', '4.33'], ['SJF', 'P2, P1, P3', '0, 3, 8', '3.67']])),
           ('Memory simulation', '<p>Holes 100, 250, 75, 300 (KB). Requests 90, 200, 70 with first fit → 100, 250, 75.</p>'),
           ('In C', code('for (i = 0; i < n; i++) {\n    wait[i] = (i == 0) ? 0 : wait[i-1] + burst[i-1];\n    total += wait[i];\n}\nprintf("Average wait = %.2f", (float) total / n);'))],
          [fill('FCFS, bursts 4, 6, 2 (arrival 0). Average waiting time =', '{0}', [['4.67', '14/3']], 'Waits 0, 4, 10 → 14/3'),
           fill('SJF with the same bursts 4, 6, 2. Average waiting time =', '{0}', [['2.67', '8/3']], 'Order 2, 4, 6 → waits 0, 2, 6 → 8/3'),
           mcq('Holes 100, 250, 75, 300. Request 260 with first fit uses…', ['300', '250', 'none'], '300'),
           tf('SJF gives the minimum average waiting time for jobs arriving together.', True)]),

    97: L('Review: model data with ER diagrams, map to relations, and normalise to 3NF.',
          [('Checklist', '<ol><li>Identify entities, attributes, keys</li><li>Find relationships and cardinalities</li><li>Resolve M:N with link entities</li><li>Map to tables with PKs and FKs</li><li>Check 1NF → 2NF → 3NF using functional dependencies</li></ol>'),
           ('Unnormalised example', '<p>BORROW(MemberID, MemberName, {BookID, Title, DateOut}) → 1NF: remove the repeating group → 2NF/3NF: MEMBER(<u>MemberID</u>, Name), BOOK(<u>BookID</u>, Title), LOAN(<u>MemberID*, BookID*, DateOut</u>)</p>')],
          [order('Order the modelling steps.', ['Identify entities and keys', 'Find relationships', 'Resolve M:N relationships', 'Map to tables', 'Normalise to 3NF']),
           mcq('In LOAN(MemberID, BookID, DateOut), MemberName would cause…', ['a partial dependency (breaks 2NF)', 'nothing', 'a 1NF violation'], 'a partial dependency (breaks 2NF)'),
           tf('A repeating group must be removed to reach 1NF.', True)]),

    98: L('Review: answer information needs with SQL — filters, joins, aggregates and subqueries.',
          [('Tables', STU + CLS),
           ('Subquery', code('SELECT Name FROM Student\nWHERE Mark > (SELECT AVG(Mark) FROM Student);') + '<p>Average = 13 → Awa (15), Ngum (18).</p>')],
          [fill('How many students score above the average?', '{0}', [['2']], visual=STU),
           mcq('Which query lists names with their room?', ['SELECT s.Name, c.Room FROM Student s JOIN Class c ON s.ClassID = c.ClassID;', 'SELECT Name, Room FROM Student;', 'SELECT * FROM Class WHERE Name;'], 'SELECT s.Name, c.Room FROM Student s JOIN Class c ON s.ClassID = c.ClassID;'),
           fill('SELECT COUNT(*) FROM Student WHERE ClassID IN (\'A\', \'C\') =', '{0}', [['3']])]),

    99: L('Case study: design a school library database from ER diagram to 3NF.',
          [('Scenario', '<p>Members borrow books. A book has several copies. Each loan records the copy, member, date out and date returned. Books have one publisher.</p>'),
           ('Entities', '<p>MEMBER, BOOK, COPY, LOAN, PUBLISHER</p><p>PUBLISHER 1:M BOOK · BOOK 1:M COPY · MEMBER 1:M LOAN · COPY 1:M LOAN</p>'),
           ('Relations', '<p>MEMBER(<u>MemberID</u>, Name, Class) · PUBLISHER(<u>PubID</u>, Name) · BOOK(<u>ISBN</u>, Title, PubID*) · COPY(<u>CopyID</u>, ISBN*) · LOAN(<u>LoanID</u>, CopyID*, MemberID*, DateOut, DateIn)</p>')],
          [mcq('Why separate COPY from BOOK?', ['A book can have several physical copies', 'To save the title', 'Copies have no ID'], 'A book can have several physical copies'),
           mcq('Where does PubID go as a foreign key?', ['BOOK', 'PUBLISHER', 'MEMBER'], 'BOOK'),
           match('Cardinality.', [('Publisher – Book', '1 : M'), ('Member – Book (through loans)', 'M : N')]),
           tf('LOAN acts as the link between MEMBER and COPY.', True)]),

    100: L('Project: create the database in SQL and bind a web form to it.',
           [('Create', code("CREATE TABLE Member (\n  MemberID INT AUTO_INCREMENT PRIMARY KEY,\n  Name VARCHAR(50) NOT NULL,\n  Class VARCHAR(10)\n);")),
            ('Form', code('<form action="add_member.php" method="post">\n  <input name="name" required>\n  <input name="class">\n  <button>Save</button>\n</form>')),
            ('Server script', code('$stmt = $pdo->prepare("INSERT INTO Member (Name, Class) VALUES (?, ?)");\n$stmt->execute([$_POST["name"], $_POST["class"]]);'))],
           [match('Match the form field to the column.', [('name="name"', 'Member.Name'), ('name="class"', 'Member.Class')]),
            mcq('Why use method="post" for this form?', ['Data goes in the request body, not the URL', 'It is faster to type', 'GET is not allowed'], 'Data goes in the request body, not the URL'),
            mcq('AUTO_INCREMENT on MemberID means…', ['the DBMS generates the next ID', 'the user must type the ID', 'IDs can repeat'], 'the DBMS generates the next ID'),
            tf('The required attribute gives client-side validation, but the server must still validate.', True)]),

    101: L('Networks move data between devices following layered protocols; security protects it.',
           [('OSI model', OSI + '<p>TCP/IP model: Application, Transport, Internet, Network access.</p>'),
            ('Network basics', table(['Topic', 'Examples'], [['Types', 'PAN, LAN, MAN, WAN'], ['Topologies', 'bus, star, ring, mesh'], ['Devices', 'switch (MAC), router (IP), access point, modem'], ['Addressing', 'IPv4 (32-bit), IPv6 (128-bit), MAC (48-bit)']])),
            ('Security', '<p><b>Symmetric</b> encryption: one shared key (AES). <b>Asymmetric</b>: public/private keys (RSA), used in HTTPS. Firewalls, VPNs, digital signatures and certificates.</p>')],
           [order('Order the OSI layers from 7 to 1.', ['Application', 'Presentation', 'Session', 'Transport', 'Network', 'Data link', 'Physical']),
            match('Match the device/protocol to the layer.', [('Router / IP', 'Network'), ('Switch / MAC', 'Data link'), ('TCP', 'Transport'), ('HTTP', 'Application')]),
            fill('An IPv4 address has how many bits?', '{0}', [['32']]),
            mcq('HTTPS uses public/private keys to exchange a session key. This is…', ['asymmetric encryption', 'no encryption', 'hashing only'], 'asymmetric encryption')]),

    102: L('Software engineering brings discipline to building software; theoretical CS studies what computers can compute.',
           [('Finite state machine', FSM + '<p>Accepts binary strings with an even number of 1s. Input 1011 → Even → Odd → Odd → Even → Odd: rejected.</p>'),
            ('Theory', table(['Concept', 'Idea'], [['Regular expression', 'pattern, e.g. [0-9]{9} for a 9-digit phone'], ['Turing machine', 'tape + head + states: model of any computation'], ['Halting problem', 'no algorithm can decide for every program whether it halts'], ['Big-O', 'growth of time/space: O(1), O(log n), O(n), O(n²)']])),
            ('SE recap', '<p>SDLC models, requirements, design, testing, maintenance, project management.</p>')],
           [mcq('Does the FSM accept 1001?', ['Yes (two 1s)', 'No'], 'Yes (two 1s)', visual=FSM),
            mcq('Does the FSM accept 111?', ['No (three 1s)', 'Yes'], 'No (three 1s)'),
            mcq('The halting problem shows that…', ['some problems cannot be solved by any algorithm', 'all programs halt', 'computers are slow'], 'some problems cannot be solved by any algorithm'),
            mcq('Which regular expression matches exactly 3 digits?', ['[0-9]{3}', '[a-z]+', '.*'], '[0-9]{3}')]),

    103: L('Subnetting splits a network into smaller networks by borrowing host bits for the network part.',
           [('Basics', '<p>192.168.1.0/24: 24 network bits, 8 host bits → 2⁸ − 2 = <b>254 hosts</b> (network and broadcast addresses excluded).</p>'),
            ('Splitting /24 into /26', table(['Subnet', 'Range', 'Broadcast'], [['192.168.1.0/26', '.1 – .62', '.63'], ['192.168.1.64/26', '.65 – .126', '.127'], ['192.168.1.128/26', '.129 – .190', '.191'], ['192.168.1.192/26', '.193 – .254', '.255']]) + '<p>Mask 255.255.255.192 · 4 subnets × 62 hosts.</p>'),
            ('Formulas', '<p class="wt-key">Subnets = 2^(borrowed bits) · hosts = 2^(host bits) − 2</p>')],
           [fill('Hosts per subnet for /27?', '{0}', [['30']]),
            fill('Subnet mask for /27 (last octet)?', '255.255.255.{0}', [['224']]),
            fill('192.168.1.70/26 belongs to the subnet starting at 192.168.1.', '{0}', [['64']]),
            fill('Its broadcast address is 192.168.1.', '{0}', [['127']]),
            fill('How many /26 subnets fit in a /24?', '{0}', [['4']])]),
}
