"""Upper Sixth Computer Science: system software and operating systems (lessons 38-60)."""
from helpers import *
from f3_maths_part1 import table

LESSONS = {
    38: L('System software controls the hardware and provides a platform for applications.',
          [('Components', table(['Type', 'Examples'], [['Operating system', 'kernel, shell, drivers'], ['Utilities', 'antivirus, backup, compression, disk tools'], ['Language translators', 'compiler, interpreter, assembler'], ['Linkers and loaders', 'combine object files; load programs into memory'], ['Firmware', 'BIOS/UEFI']])),
           ('Kernel', '<p>The core of the OS: manages processes, memory, devices and system calls. <b>Monolithic</b> (Linux) vs <b>microkernel</b> (minimal kernel, services in user space).</p>'),
           ('User vs kernel mode', '<p>Applications run in user mode; privileged instructions need kernel mode via <b>system calls</b>.</p>')],
          [match('Match the system software.', [('Loads an executable into RAM', 'Loader'), ('Joins object files and libraries', 'Linker'), ('Translates the whole program before running', 'Compiler'), ('Runs at power-on to start the system', 'Firmware (BIOS/UEFI)')]),
           mcq('A program asks the OS to open a file through…', ['a system call', 'an interrupt vector table', 'a compiler'], 'a system call'),
           mcq('Linux uses which kernel design?', ['Monolithic', 'Microkernel', 'No kernel'], 'Monolithic')]),

    39: L('Utility software maintains, protects and optimises the system.',
          [('Utilities', table(['Utility', 'Purpose'], [['Antivirus / antimalware', 'detect and remove malicious software'], ['Disk defragmenter', 'store file fragments contiguously (HDD)'], ['Disk cleanup / formatter', 'free space / prepare a disk'], ['Backup / restore', 'protect against data loss'], ['Compression', 'reduce file size (lossless zip, lossy JPEG/MP3)'], ['Encryption', 'protect confidentiality'], ['System monitor', 'CPU, memory, processes']])),
           ('Lossless vs lossy', '<p>Lossless (ZIP, PNG): original restored exactly — needed for text and programs. Lossy (JPEG, MP3): smaller, some detail lost.</p>')],
          [match('Match the utility.', [('Puts file pieces together on an HDD', 'Defragmenter'), ('Makes a .zip file', 'Compression'), ('Copies data to another drive nightly', 'Backup'), ('Shows CPU usage per process', 'System monitor')]),
           sort('Lossless or lossy?', ['Lossless', 'Lossy'], [('ZIP', 'Lossless'), ('JPEG', 'Lossy'), ('PNG', 'Lossless'), ('MP3', 'Lossy')]),
           tf('A program file must be compressed losslessly.', True)]),

    40: L('Operating systems evolved from batch systems to multiprogramming, time-sharing, personal, network, real-time, mobile and distributed systems.',
          [('Evolution', table(['Era', 'Type', 'Idea'], [['1950s', 'Batch', 'jobs grouped and run one after another'], ['1960s', 'Multiprogramming', 'several jobs in memory; CPU switches during I/O'], ['1970s', 'Time-sharing', 'many users, small time slices'], ['1980s', 'Personal (GUI)', 'single-user desktops'], ['1990s+', 'Network / distributed', 'resources shared across computers'], ['2000s+', 'Mobile, cloud, real-time embedded', 'Android, iOS, RTOS']])),
           ('Real-time', '<p><b>Hard</b> real-time: missing a deadline is a failure (airbag). <b>Soft</b>: occasional delay tolerated (video streaming).</p>')],
          [order('Order the evolution.', ['Batch', 'Multiprogramming', 'Time-sharing', 'Personal GUI', 'Mobile and cloud']),
           sort('Hard or soft real-time?', ['Hard', 'Soft'], [('Car airbag controller', 'Hard'), ('Online video streaming', 'Soft'), ('Pacemaker', 'Hard'), ('Video game frame rate', 'Soft')]),
           mcq('Keeping the CPU busy by switching to another job during I/O is…', ['multiprogramming', 'batch', 'spooling'], 'multiprogramming')]),

    41: L('Users interact with the OS through a CLI, a GUI, menus, touch or voice; programs interact through APIs and system calls.',
          [('User interfaces', table(['Interface', 'Strengths', 'Weaknesses'], [['CLI (shell)', 'powerful, scriptable, low resources', 'must learn commands'], ['GUI (WIMP)', 'intuitive, visual', 'more memory/CPU'], ['Menu-driven', 'simple (ATM)', 'limited options'], ['Touch / gesture', 'natural on phones', 'less precise'], ['Voice / NLI', 'hands-free, accessible', 'errors with accents/noise']])),
           ('Shell scripting', '<p>Automate tasks: <code>for f in *.txt; do cp "$f" backup/; done</code> (bash) or batch files (.bat).</p>')],
          [match('Best interface.', [('Administrator managing 100 servers', 'CLI with scripts'), ('Bank cash machine', 'Menu-driven'), ('Driver using a phone while driving', 'Voice'), ('First-time computer user', 'GUI')]),
           tf('A GUI generally needs more resources than a CLI.', True),
           mcq('A program requests OS services through…', ['an API / system calls', 'the GUI', 'a printer driver only'], 'an API / system calls')]),

    42: L('Installing an OS prepares the disk (partitions, file system) and the boot loader. The file system organises storage.',
          [('Installation', '<ol><li>Check requirements and back up</li><li>Boot from installation media</li><li>Partition (MBR or GPT) and format (NTFS, ext4…)</li><li>Copy system files, install the boot loader (GRUB / Windows Boot Manager)</li><li>Configure users, drivers, updates</li></ol><p>Dual-boot: two OSs on separate partitions.</p>'),
           ('File storage', table(['File system', 'Used by', 'Notes'], [['FAT32', 'USB drives', 'max file 4 GB'], ['NTFS', 'Windows', 'permissions, journaling'], ['ext4', 'Linux', 'journaling'], ['APFS', 'macOS', 'SSD-optimised']]))],
          [order('Order the installation steps.', ['Back up data', 'Boot from the installer', 'Partition and format', 'Install the boot loader', 'Configure users and drivers']),
           mcq('Why can\'t a 6 GB video be copied to a FAT32 USB drive?', ['FAT32 limits files to 4 GB', 'USB drives are read-only', 'Videos cannot be copied'], 'FAT32 limits files to 4 GB'),
           mcq('GRUB is a…', ['boot loader', 'file system', 'virus'], 'boot loader')]),

    44: L('A process is a program in execution. The OS tracks each process with a Process Control Block (PCB).',
          [('Process states', '<p>New → Ready → Running → (Waiting) → Ready … → Terminated. The <b>dispatcher</b> gives the CPU to a ready process; a <b>context switch</b> saves one PCB and loads another.</p>'),
           ('PCB contents', '<div class="chips"><span>Process ID</span><span>State</span><span>Program counter</span><span>Registers</span><span>Priority</span><span>Memory info</span><span>Open files</span></div>'),
           ('Processes vs threads', '<p>A <b>thread</b> is a lightweight unit inside a process; threads share memory, processes do not.</p>')],
          [order('Normal sequence of process states.', ['New', 'Ready', 'Running', 'Terminated']),
           match('Transition cause.', [('Running → Waiting', 'Process requests I/O'), ('Running → Ready', 'Time slice expires'), ('Waiting → Ready', 'I/O completes'), ('Ready → Running', 'Dispatcher selects it')]),
           mcq('Saving one process\'s state and loading another\'s is a…', ['context switch', 'deadlock', 'page fault'], 'context switch'),
           tf('Threads of the same process share memory.', True)]),

    48: L('Processes that share data must be synchronised to avoid race conditions in their critical sections.',
          [('Race condition', '<p>Two processes update a shared counter at the same time; the final value depends on timing → wrong results.</p>'),
           ('Critical section rules', '<ul><li><b>Mutual exclusion</b>: one process at a time</li><li><b>Progress</b>: no unnecessary waiting</li><li><b>Bounded waiting</b>: no starvation</li></ul>'),
           ('Tools', '<p><b>Semaphores</b> (wait/P and signal/V), <b>mutex locks</b>, monitors. Classic problems: producer–consumer, readers–writers, dining philosophers.</p>')],
          [mcq('A result that depends on the timing of processes is a…', ['race condition', 'deadlock', 'context switch'], 'race condition'),
           fill('A semaphore is 1. Process A does wait(); value =', '{0}', [['0']]),
           mcq('Process B then does wait() on that semaphore. B…', ['is blocked until signal()', 'continues', 'terminates'], 'is blocked until signal()'),
           match('Match the requirement.', [('Only one process in the critical section', 'Mutual exclusion'), ('A waiting process eventually enters', 'Bounded waiting'), ('Decision is not postponed forever', 'Progress')])]),

    49: L('Deadlock: processes wait forever for resources held by each other. Prevent, avoid, or detect and recover.',
          [('Four conditions (all needed)', '<ol><li><b>Mutual exclusion</b></li><li><b>Hold and wait</b></li><li><b>No pre-emption</b></li><li><b>Circular wait</b></li></ol>'),
           ('Handling', table(['Strategy', 'How'], [['Prevention', 'break one condition (e.g. request all resources at once, order resources)'], ['Avoidance', 'only grant safe requests (Banker\'s algorithm)'], ['Detection & recovery', 'find cycles in the wait-for graph, kill/roll back a process'], ['Ignore', '"ostrich" approach (rare deadlocks)']])),
           ('Example', '<p>P1 holds the printer and wants the scanner; P2 holds the scanner and wants the printer → circular wait → deadlock.</p>')],
          [mcq('How many conditions must hold for a deadlock?', ['All four', 'Any one', 'Two'], 'All four'),
           match('Match the strategy.', [('Banker\'s algorithm', 'Avoidance'), ('Number resources and request in order', 'Prevention'), ('Find cycles, then kill a process', 'Detection and recovery')]),
           mcq('Requesting all needed resources at the start breaks…', ['hold and wait', 'circular wait', 'mutual exclusion'], 'hold and wait'),
           tf('Starvation and deadlock are exactly the same thing.', False, 'Starvation: a process waits indefinitely while others progress.')]),

    51: L('Memory management allocates RAM to processes, protects them, and translates logical addresses to physical ones.',
          [('Goals', '<ul><li>Allocate and free memory</li><li>Protect processes from each other</li><li>Allow sharing</li><li>Use memory efficiently</li></ul>'),
           ('Addresses', '<p>Logical address (from the program) → <b>MMU</b> → physical address. Base/relocation register: physical = base + logical (if logical &lt; limit).</p><p>Base 3000, logical 250 → physical <b>3250</b>.</p>'),
           ('Binding', '<p>Addresses can be bound at compile time, load time or run time (most flexible).</p>')],
          [fill('Base register 5000, logical address 120.', 'Physical address = {0}', [['5120']]),
           mcq('Base 4000, limit 1000. Logical address 1200 causes…', ['a protection fault (trap)', 'physical address 5200', 'nothing'], 'a protection fault (trap)'),
           mcq('Which hardware translates logical to physical addresses?', ['MMU', 'ALU', 'DMA'], 'MMU')]),

    52: L('Contiguous allocation gives each process one continuous block, using fixed or variable partitions and a placement strategy.',
          [('Placement strategies', '<p>Free holes: 100K, 500K, 200K, 300K, 600K. Request: 212K.</p>' + table(['Strategy', 'Rule', 'Chooses'], [['First fit', 'first hole big enough', '500K'], ['Best fit', 'smallest hole big enough', '300K'], ['Worst fit', 'largest hole', '600K']])),
           ('Fragmentation', '<p><b>Internal</b>: wasted space inside an allocated partition. <b>External</b>: free memory split into holes too small to use. Fix: <b>compaction</b>.</p>')],
          [mcq('Holes: 50K, 150K, 300K, 80K. Request 70K. First fit chooses…', ['150K', '80K', '300K'], '150K'),
           mcq('Same holes, request 70K. Best fit chooses…', ['80K', '150K', '50K'], '80K'),
           mcq('Same holes, request 70K. Worst fit chooses…', ['300K', '150K', '80K'], '300K'),
           match('Match the term.', [('Unused space inside a partition', 'Internal fragmentation'), ('Many small unusable holes', 'External fragmentation'), ('Moving processes to merge holes', 'Compaction')])]),

    53: L('Non-contiguous allocation splits a process into pages (paging) or logical segments (segmentation).',
          [('Paging', '<p>Logical memory → fixed-size <b>pages</b>; physical memory → <b>frames</b> of the same size. A <b>page table</b> maps page → frame. No external fragmentation.</p><p>Page size 1 KB (1024): logical address 2100 → page 2, offset 52. If page 2 is in frame 5 → physical = 5 × 1024 + 52 = <b>5172</b>.</p>'),
           ('Segmentation', '<p>Variable-size segments matching program parts (code, data, stack). Segment table: base + limit.</p>'),
           ('TLB', '<p>Translation lookaside buffer: fast cache of recent page-table entries.</p>')],
          [fill('Page size 1024. Logical address 3000.', 'Page = {0}, offset = {1}', [['2'], ['952']]),
           fill('Page 2 is in frame 7.', 'Physical address = {0}', [['8120']], '7 × 1024 + 952'),
           mcq('Paging eliminates…', ['external fragmentation', 'internal fragmentation', 'the need for RAM'], 'external fragmentation'),
           mcq('The TLB is…', ['a cache of page-table entries', 'a type of disk', 'a scheduling algorithm'], 'a cache of page-table entries')]),

    54: L('Virtual memory lets programs use more memory than physical RAM by keeping only needed pages in RAM (demand paging).',
          [('Demand paging', '<p>A page is loaded only when referenced. If it is not in RAM → <b>page fault</b> → OS loads it from disk, possibly replacing a page.</p>'),
           ('Replacement algorithms', '<p>Reference string 7, 0, 1, 2, 0, 3, 0, 4 with 3 frames:</p>' + table(['Algorithm', 'Idea', 'Faults'], [['FIFO', 'replace the oldest page', '7'], ['LRU', 'replace the least recently used', '6'], ['Optimal', 'replace the page not needed for longest', '6']])),
           ('Thrashing', '<p>Too many page faults: the system spends more time swapping than working. Fix: fewer processes, more RAM.</p>')],
          [fill('Reference string 1, 2, 3, 1, 4 with 3 frames, FIFO. Number of page faults =', '{0}', [['4']], '1 F, 2 F, 3 F, 1 hit, 4 F (replaces 1)'),
           fill('Reference string 1, 2, 3, 1, 4, 1 with 3 frames, FIFO. Number of page faults =', '{0}', [['5']], 'After 4 replaces 1, the next 1 faults again (replaces 2).'),
           mcq('A page not in RAM is referenced. This is a…', ['page fault', 'deadlock', 'segmentation'], 'page fault'),
           mcq('The system spends most of its time swapping pages. This is…', ['thrashing', 'paging', 'spooling'], 'thrashing')]),

    56: L('The OS manages I/O devices with drivers, controllers, buffers, spooling and interrupts.',
          [('Layers', flow(['Application', 'OS I/O subsystem', 'Device driver', 'Device controller', 'Device'])),
           ('Techniques', table(['Technique', 'Purpose'], [['Buffering', 'temporary storage to match speeds'], ['Caching', 'keep copies of frequently used data'], ['Spooling', 'queue output for a slow shared device (printer)'], ['Device reservation', 'exclusive access']])),
           ('Device types', '<p>Block devices (disks: blocks of data) vs character devices (keyboard: stream of bytes).</p>')],
          [order('Order the I/O layers from program to hardware.', ['Application', 'OS I/O subsystem', 'Device driver', 'Device controller', 'Device']),
           match('Match the technique.', [('Print jobs wait in a queue on disk', 'Spooling'), ('Data stored temporarily between devices of different speeds', 'Buffering'), ('Recent disk blocks kept in RAM', 'Caching')]),
           sort('Block or character device?', ['Block', 'Character'], [('Hard disk', 'Block'), ('Keyboard', 'Character'), ('SSD', 'Block'), ('Mouse', 'Character')])]),

    57: L('Data moves between CPU, memory and devices by programmed I/O, interrupt-driven I/O or DMA.',
          [('Methods', table(['Method', 'How', 'CPU load'], [['Programmed I/O (polling)', 'CPU repeatedly checks device status', 'high: busy waiting'], ['Interrupt-driven', 'device interrupts the CPU when ready', 'medium'], ['DMA', 'DMA controller moves blocks directly to memory, interrupts at the end', 'low']])),
           ('Interrupt handling', '<ol><li>Device raises interrupt</li><li>CPU finishes current instruction, saves state</li><li>Jumps to the interrupt service routine (ISR) via the vector table</li><li>Restores state and continues</li></ol>')],
          [match('Match the method.', [('CPU keeps checking "are you ready?"', 'Polling'), ('Device signals when ready', 'Interrupt-driven I/O'), ('Large disk transfers without the CPU', 'DMA')]),
           order('Order interrupt handling.', ['Device raises an interrupt', 'CPU saves its state', 'ISR runs', 'State restored, program resumes']),
           mcq('Which is best for transferring a 500 MB file from disk?', ['DMA', 'Polling', 'Interrupt per byte'], 'DMA')]),

    58: L('A file system provides files, directories, attributes, allocation methods and access permissions.',
          [('Files and directories', '<p>Attributes: name, type, size, location, dates, owner, permissions. Directory structures: single-level, two-level, tree (hierarchical), acyclic graph (links).</p>'),
           ('Allocation methods', table(['Method', 'Pros', 'Cons'], [['Contiguous', 'fast sequential & direct access', 'external fragmentation, hard to grow'], ['Linked', 'no external fragmentation', 'slow direct access, pointer overhead'], ['Indexed (i-nodes)', 'fast direct access', 'index block overhead']])),
           ('Permissions (Unix)', '<p>rwxr-x--- → owner read/write/execute, group read/execute, others nothing. In octal: <b>750</b>.</p>')],
          [fill('Permissions rw-r--r-- in octal =', '{0}', [['644']]),
           fill('Permissions rwxrwxr-x in octal =', '{0}', [['775']]),
           match('Match the allocation method.', [('Blocks next to each other', 'Contiguous'), ('Each block points to the next', 'Linked'), ('A block lists all block addresses', 'Indexed')]),
           mcq('Most modern systems use which directory structure?', ['Tree (hierarchical)', 'Single-level', 'None'], 'Tree (hierarchical)')]),

    59: L('Mass storage is accessed sequentially, directly or by index. Disk scheduling reduces head movement.',
          [('Access methods', table(['Method', 'Example'], [['Sequential', 'tape, log files'], ['Direct (random)', 'database record by address'], ['Indexed sequential', 'index points into a sorted file']])),
           ('Disk scheduling', '<p>Head at 50; requests 82, 17, 43, 140, 24.</p>' + table(['Algorithm', 'Order', 'Total movement'], [['FCFS', '82, 17, 43, 140, 24', '32+65+26+97+116 = 336'], ['SSTF', '43, 24, 17, 82, 140', '7+19+7+65+58 = 156']])),
           ('RAID', '<p>RAID 0 striping (speed), RAID 1 mirroring (copy), RAID 5 striping with parity (speed + one-disk failure tolerance).</p>')],
          [fill('Head at 20. FCFS requests 30, 10. Total head movement =', '{0}', [['30']], '10 + 20'),
           mcq('SSTF chooses…', ['the request closest to the current head position', 'the oldest request', 'the largest cylinder'], 'the request closest to the current head position'),
           match('Match the RAID level.', [('Mirroring', 'RAID 1'), ('Striping only', 'RAID 0'), ('Striping with parity', 'RAID 5')]),
           mcq('A tape backup is accessed…', ['sequentially', 'directly', 'by hashing'], 'sequentially')]),

    60: L('The OS enforces security (authentication, access control, protection) and handles errors gracefully.',
          [('Security mechanisms', table(['Mechanism', 'Example'], [['Authentication', 'passwords, biometrics, 2FA'], ['Authorisation / access control', 'ACLs, permissions, roles (RBAC)'], ['Auditing / logging', 'event logs'], ['Encryption', 'BitLocker, LUKS'], ['Updates / patches', 'close vulnerabilities'], ['Least privilege', 'run as standard user, not admin']])),
           ('Threats', '<p>Malware, privilege escalation, buffer overflow, denial of service, insider misuse.</p>'),
           ('Error management', '<p>Detect (parity, checksums, CRC), report (error codes, logs), recover (retry, restart service, fall back), and fail safely (e.g. kernel panic / BSOD rather than corrupting data).</p>')],
          [match('Match the mechanism.', [('Only HR can read salary files', 'Access control'), ('Record of all login attempts', 'Auditing / logging'), ('Disk unreadable without a key', 'Encryption'), ('Users run without admin rights', 'Least privilege')]),
           mcq('Writing past the end of a buffer to inject code is a…', ['buffer overflow attack', 'page fault', 'context switch'], 'buffer overflow attack'),
           mcq('A CRC is used to…', ['detect transmission or storage errors', 'encrypt files', 'schedule processes'], 'detect transmission or storage errors')]),
}
