"""Upper Sixth ICT: office software, RDBMS, cloud, green computing, programming (lessons 58-86)."""
from helpers import *
from f3_maths_part1 import table
from l6_ict_part5 import code, LESSONS as L6ALG

MARKS = table(['', 'A', 'B', 'C'], [['1', 'Name', 'Mark', 'Grade'], ['2', 'Awa', '15', ''], ['3', 'Paul', '9', ''], ['4', 'Ngum', '18', '']])
LOOKUP = table(['', 'E', 'F'], [['1', 'Code', 'Price'], ['2', 'P01', '500'], ['3', 'P02', '1200'], ['4', 'P03', '750']])

LESSONS = {
    58: L('Word processors produce professional documents with styles, automatic tables of contents, mail merge, references and review tools.',
          [('Key features', table(['Feature', 'Use'], [['Styles', 'consistent headings; automatic table of contents'], ['Headers/footers', 'page numbers, titles on every page'], ['Section breaks', 'different layouts in one document'], ['Footnotes, citations', 'references and bibliography'], ['Mail merge', 'one letter → personalised copies for many people'], ['Track changes, comments', 'review and edit with others'], ['Templates', 'reuse a ready design']])),
           ('Mail merge steps', flow(['Main document', 'Data source (list)', 'Insert merge fields', 'Preview', 'Finish & merge']))],
          [match('Which feature?', [('Send the same invitation with each parent\'s name', 'Mail merge'), ('Automatic table of contents', 'Heading styles'), ('See what a colleague changed', 'Track changes'), ('Page numbers on every page', 'Footer')]),
           order('Order the mail merge steps.', ['Create the main document', 'Choose the data source', 'Insert merge fields', 'Preview results', 'Finish and merge']),
           tf('A table of contents can update automatically when headings change.', True)]),

    59: L('Format and manage spreadsheet data: number formats, conditional formatting, sorting, filtering, freezing and validation.',
          [('Formatting', '<p>Number formats (currency FCFA, %, date), alignment, borders, <b>conditional formatting</b> (e.g. marks &lt; 10 in red).</p>'),
           ('Managing data', table(['Tool', 'Use'], [['Sort', 'order rows by one or more columns'], ['Filter / AutoFilter', 'show only rows that match'], ['Freeze panes', 'keep headings visible when scrolling'], ['Data validation', 'restrict entries (0–20, list of classes)'], ['Remove duplicates', 'clean lists']]))],
          [match('Which tool?', [('Show only students of Form 5A', 'Filter'), ('Marks below 10 turn red automatically', 'Conditional formatting'), ('Header row stays at the top when scrolling', 'Freeze panes'), ('Only allow marks between 0 and 20', 'Data validation')]),
           mcq('Sorting by class, then by mark within each class, uses…', ['a multi-level sort', 'a filter', 'freeze panes'], 'a multi-level sort'),
           tf('Filtering deletes the hidden rows.', False, 'It only hides them.')]),

    61: L('Advanced functions — IF, nested IF, COUNTIF, SUMIF, VLOOKUP, ROUND — and charts turn data into decisions.',
          [('Functions', MARKS + table(['Formula', 'Result'], [['=IF(B2>=10,"Pass","Fail")', 'Pass'], ['=IF(B4>=16,"A",IF(B4>=10,"B","C"))', 'A'], ['=COUNTIF(B2:B4,">=10")', '2'], ['=SUMIF(B2:B4,">=10")', '33'], ['=ROUND(AVERAGE(B2:B4),1)', '14']])),
           ('VLOOKUP', LOOKUP + '<p>=VLOOKUP("P02", E2:F4, 2, FALSE) → <b>1200</b> (find P02 in the first column, return column 2, exact match).</p>'),
           ('Charts', table(['Chart', 'Best for'], [['Column / bar', 'comparing categories'], ['Line', 'trends over time'], ['Pie', 'parts of a whole'], ['Scatter', 'relationship between two variables']]))],
          [mcq('=IF(B3>=10,"Pass","Fail") gives…', ['Fail', 'Pass', '9'], 'Fail', visual=MARKS),
           fill('=VLOOKUP("P03", E2:F4, 2, FALSE) =', '{0}', [['750']], visual=LOOKUP),
           fill('=SUMIF(B2:B4,"<10") =', '{0}', [['9']]),
           match('Best chart.', [('Monthly sales over a year', 'Line chart'), ('Share of budget by department', 'Pie chart'), ('Compare marks of 5 students', 'Column chart'), ('Hours studied vs mark', 'Scatter chart')])]),

    62: L('Formulas can use cells from other worksheets and workbooks, so summary sheets update automatically.',
          [('Other sheet', '<p><code>=Term1!B5</code> → cell B5 of sheet Term1. Sheet names with spaces need quotes: <code>=\'Term 1\'!B5</code>.</p>'),
           ('3D reference', '<p><code>=SUM(Term1:Term3!B5)</code> adds B5 on every sheet from Term1 to Term3.</p>'),
           ('Other workbook', '<p><code>=[Fees.xlsx]Sheet1!C2</code>. If the source file moves, links must be updated.</p><p class="wt-key">Link, don\'t copy: one change updates everything.</p>')],
          [mcq('Reference to cell C3 on sheet "Fees"?', ['=Fees!C3', '=C3!Fees', '=Fees:C3'], '=Fees!C3'),
           mcq('Sheet name "Term 2" (with a space). Reference to D4?', ["='Term 2'!D4", '=Term 2!D4', '=D4@Term2'], "='Term 2'!D4"),
           fill('B5 is 12 on Term1, 14 on Term2, 16 on Term3. =SUM(Term1:Term3!B5) =', '{0}', [['42']]),
           tf('A linked cell updates when the source cell changes.', True)]),

    63: L('What-if analysis tests how changing inputs affects results: Goal Seek, Scenarios and Data Tables.',
          [('Tools', table(['Tool', 'Question it answers'], [['Goal Seek', 'what input gives this result?'], ['Scenario Manager', 'compare named sets of inputs (best / worst case)'], ['Data Table', 'show results for many input values at once']])),
           ('Goal Seek example', '<p>Profit = (price − 300) × 200. What price gives a profit of 100 000? Goal Seek → <b>800 FCFA</b>.</p><p>(800 − 300) × 200 = 100 000 ✓</p>')],
          [fill('Profit = (price − 400) × 100. Goal Seek for profit 50 000 gives price =', '{0}', [['900']]),
           match('Which tool?', [('Find the sales needed to break even', 'Goal Seek'), ('Compare optimistic and pessimistic budgets', 'Scenario Manager'), ('Profit for prices 500, 600, 700, 800', 'Data Table')]),
           tf('What-if analysis changes inputs to see effects on outputs.', True)]),

    65: L('Produce clear presentations: plan the message, use a consistent design, and keep slides simple.',
          [('Building', '<ul><li>Choose a theme; use the <b>slide master</b> for logos and fonts on all slides</li><li>Layouts: title, title + content, two content, picture</li><li>Speaker notes and presenter view</li><li>Insert tables, charts, SmartArt, images</li></ul>'),
           ('Design rules', '<p>One idea per slide, 6×6 rule, font ≥ 24 pt, high contrast, consistent colours, images that support the message.</p>')],
          [match('Which feature?', [('Logo on every slide automatically', 'Slide master'), ('Your private notes while presenting', 'Presenter view / speaker notes'), ('Picture on the left, text on the right', 'Two-content layout')]),
           sort('Good or bad practice?', ['Good', 'Bad'], [('One idea per slide', 'Good'), ('Full paragraphs on slides', 'Bad'), ('Consistent theme', 'Good'), ('Red text on a green background', 'Bad')]),
           tf('The slide master changes the design of all slides at once.', True)]),

    66: L('Add multimedia, transitions and animations to support — not distract from — the message.',
          [('Multimedia', '<p>Insert audio and video (embedded or linked), set playback (on click, automatically), trim clips, add captions.</p>'),
           ('Animations', table(['Type', 'Effect'], [['Entrance', 'object appears'], ['Emphasis', 'object pulses, grows'], ['Exit', 'object disappears'], ['Motion path', 'object moves along a path']]) + '<p>Timing: on click, with previous, after previous; triggers.</p>'),
           ('Transitions', '<p>Effects between slides (fade, push). Use one subtle transition throughout.</p>')],
          [match('Match the animation type.', [('Bullet points appear one by one', 'Entrance'), ('A word grows to highlight it', 'Emphasis'), ('A car moves across the slide', 'Motion path'), ('An image fades away', 'Exit')]),
           mcq('Difference between transition and animation?', ['Transition: between slides; animation: objects on a slide', 'They are the same', 'Transitions are only for video'], 'Transition: between slides; animation: objects on a slide'),
           tf('A linked video stops working if the file is moved.', True)]),

    68: L('In an RDBMS (e.g. MS Access), create tables with fields and keys, then link them with relationships.',
          [('Table design', table(['Field', 'Type', 'Notes'], [['StudentID', 'AutoNumber / Short Text', 'primary key'], ['Name', 'Short Text', 'required'], ['DOB', 'Date/Time', 'validation rule'], ['ClassID', 'Short Text', 'foreign key'], ['FeesPaid', 'Yes/No', '']])),
           ('Relationships', '<p>Drag ClassID from CLASS to STUDENT in the Relationships window → 1:M. Tick <b>Enforce referential integrity</b>; optional cascade update/delete.</p>'),
           ('Field properties', '<p>Field size, format, input mask, default value, validation rule and text, required, indexed.</p>')],
          [match('Choose the data type.', [('Has paid fees?', 'Yes/No'), ('Date of birth', 'Date/Time'), ('Automatic unique number', 'AutoNumber'), ('Remarks of any length', 'Long Text')]),
           mcq('Enforcing referential integrity prevents…', ['a student with a non-existent ClassID', 'duplicate names', 'empty tables'], 'a student with a non-existent ClassID'),
           mcq('Field property to force marks between 0 and 20?', ['Validation rule', 'Input mask', 'Caption'], 'Validation rule')]),

    69: L('Select queries retrieve records that match criteria, from one or more tables, sorted as needed.',
          [('Criteria', table(['Criteria', 'Finds'], [['>=10', 'marks of 10 or more'], ['Between 10 And 15', 'from 10 to 15'], ['Like "A*"', 'names starting with A'], ['"Form 5A"', 'exact text'], ['Is Null', 'empty field'], ['>=#01/01/2008#', 'dates on/after 1 Jan 2008']])),
           ('AND / OR', '<p>Criteria on the same row = AND; on different rows = OR.</p>'),
           ('SQL view', code("SELECT Name, Mark FROM Student\nWHERE Mark >= 10 AND ClassID = '5A'\nORDER BY Mark DESC;"))],
          [match('Match the criteria.', [('Names beginning with B', 'Like "B*"'), ('Marks from 12 to 16', 'Between 12 And 16'), ('No phone number entered', 'Is Null'), ('Marks below 10', '<10')]),
           mcq('Criteria on two different rows of the grid mean…', ['OR', 'AND', 'NOT'], 'OR'),
           mcq('A query with two tables needs…', ['a relationship (join) between them', 'two primary keys in one table', 'a form'], 'a relationship (join) between them')]),

    70: L('More queries: calculated fields, parameter queries, totals (grouping) and action queries.',
          [('Types', table(['Query', 'Example'], [['Calculated field', 'Total: [Price]*[Qty]'], ['Parameter', '[Enter class:] asks the user each time'], ['Totals (GROUP BY)', 'average mark per class'], ['Update', 'add 1 to all marks of 5A'], ['Delete', 'remove students who left'], ['Append', 'add records to another table'], ['Make-table', 'save results as a new table']])),
           ('Caution', '<p class="wt-key">Action queries change data: back up first and preview with a select query.</p>')],
          [match('Which query?', [('Ask the user which class to show', 'Parameter query'), ('Average mark per class', 'Totals query'), ('Increase all prices by 10%', 'Update query'), ('Remove last year\'s records', 'Delete query')]),
           fill('Calculated field Total: [Price]*[Qty] with Price 1500 and Qty 4 =', '{0}', [['6000']]),
           tf('Action queries change the data in tables.', True)]),

    71: L('Forms make data entry easy and safe; reports present data neatly for printing.',
          [('Forms', '<p>Built from a table or query (wizard or design view). Controls: text boxes, combo boxes (drop-down), check boxes, buttons. Validation and default values help accuracy. Subforms show related records (class → students).</p>'),
           ('Reports', '<p>Grouping and sorting (by class), totals and averages, headers/footers, page numbers, labels. Based on queries to filter data.</p>'),
           ('Navigation', '<p>A navigation form/switchboard gives users buttons to open forms and reports.</p>')],
          [sort('Form or report?', ['Form', 'Report'], [('Entering new students', 'Form'), ('Printed class list with averages', 'Report'), ('Editing a record on screen', 'Form'), ('Mailing labels', 'Report')]),
           mcq('A drop-down list on a form is a…', ['combo box', 'label', 'report footer'], 'combo box'),
           mcq('To show each class with its students underneath, a report uses…', ['grouping', 'a parameter query only', 'a calculated field only'], 'grouping')]),

    73: L('Cloud computing delivers computing resources over the internet, on demand, paid by use.',
          [('Five characteristics', '<ol><li>On-demand self-service</li><li>Broad network access</li><li>Resource pooling</li><li>Rapid elasticity (scale up/down)</li><li>Measured service (pay per use)</li></ol>'),
           ('Pros and cons', '<div class="two-col"><div><b>➕</b>no upfront hardware, scalable, accessible anywhere, automatic updates and backups</div><div><b>➖</b>needs internet, ongoing costs, privacy and data location, vendor lock-in</div></div>')],
          [match('Match the characteristic.', [('Add servers automatically during exam-results day', 'Rapid elasticity'), ('Pay only for storage used', 'Measured service'), ('Access from phone, laptop, anywhere', 'Broad network access'), ('Create an account and start without calling anyone', 'On-demand self-service')]),
           sort('Advantage or disadvantage?', ['Advantage', 'Disadvantage'], [('No servers to buy', 'Advantage'), ('Useless during an internet outage', 'Disadvantage'), ('Scales with demand', 'Advantage'), ('Hard to switch provider', 'Disadvantage')])]),

    74: L('Cloud service models: IaaS, PaaS and SaaS differ in how much the provider manages.',
          [('Models', table(['Model', 'You get', 'You manage', 'Examples'], [['IaaS', 'virtual servers, storage, network', 'OS, apps, data', 'AWS EC2, Azure VMs'], ['PaaS', 'platform to build and run apps', 'your code and data', 'Google App Engine, Heroku'], ['SaaS', 'ready software', 'only your data and settings', 'Gmail, Microsoft 365, Zoom']])),
           ('Others', '<p>FaaS / serverless (run functions on events), DaaS (desktop), STaaS (storage).</p>')],
          [match('Which model?', [('School uses Gmail for staff email', 'SaaS'), ('Developer deploys an app without managing servers', 'PaaS'), ('Company rents virtual machines and installs its own OS', 'IaaS')]),
           order('From most to least control for the customer.', ['IaaS', 'PaaS', 'SaaS']),
           tf('In SaaS, the provider manages the application.', True)]),

    75: L('Clouds can be public, private, hybrid or community. Security is shared, and cloud use raises ethical questions.',
          [('Deployment models', table(['Model', 'Meaning'], [['Public', 'shared provider infrastructure (Google, AWS)'], ['Private', 'one organisation only'], ['Hybrid', 'mix of private and public'], ['Community', 'shared by organisations with common needs']])),
           ('Security', '<p><b>Shared responsibility</b>: the provider secures the infrastructure; the customer secures accounts, data and settings. Use MFA, encryption, backups, strong access policies.</p>'),
           ('Ethics', '<p>Privacy, data sovereignty (where is the data stored?), vendor lock-in, energy use, access for all.</p>')],
          [match('Which deployment model?', [('A bank keeps sensitive data on its own cloud, websites on AWS', 'Hybrid'), ('Several hospitals share one health cloud', 'Community'), ('Anyone can rent services from the provider', 'Public'), ('Used only by one ministry', 'Private')]),
           mcq('Under shared responsibility, who must protect user passwords and settings?', ['The customer', 'Only the provider', 'Nobody'], 'The customer'),
           tf('Data sovereignty concerns the country where data is stored.', True)]),

    77: L('Green computing reduces the environmental impact of ICT: use less energy, fewer resources and less waste.',
          [('Practices', '<ul><li>Energy-efficient devices (Energy Star), sleep/hibernate modes</li><li>Switch off at night; power management settings</li><li>Virtualisation and cloud to use fewer servers</li><li>Print less: double-sided, digital documents</li><li>Solar power, efficient cooling</li><li>Buy durable, repairable equipment</li></ul>'),
           ('Energy calculation', '<p class="wt-key">kWh = watts × hours ÷ 1000</p><p>A 100 W PC left on 10 extra hours a day for 30 days = 100 × 300 ÷ 1000 = <b>30 kWh</b>.</p>')],
          [fill('A 60 W monitor left on 8 hours a day for 25 days.', 'Energy = {0} kWh', [['12']]),
           fill('20 PCs each save 50 W for 10 hours a day. Daily saving =', '{0} kWh', [['10']]),
           sort('Green or not green?', ['Green', 'Not green'], [('Printing double-sided', 'Green'), ('Leaving PCs on all weekend', 'Not green'), ('Using sleep mode', 'Green'), ('Replacing a working phone every year', 'Not green')]),
           tf('Virtualisation can reduce the number of physical servers.', True)]),

    78: L('E-waste contains toxic materials. Reduce, reuse and recycle — and wipe data before disposal.',
          [('Why it matters', '<p>Old devices contain <b>lead, mercury, cadmium</b> and other toxins that pollute soil and water when dumped or burned.</p>'),
           ('Responsible disposal', '<ol><li>Reduce: buy only what is needed, repair</li><li>Reuse: donate working devices to schools</li><li>Recycle through approved e-waste collectors / take-back schemes</li><li>Before disposal: back up, then <b>securely wipe</b> or destroy storage</li></ol>')],
          [order('Order of the waste hierarchy (best first).', ['Reduce', 'Reuse', 'Recycle', 'Dispose safely']),
           mcq('Before giving away an old laptop you should…', ['back up and securely wipe the disk', 'just delete the desktop files', 'remove the keyboard'], 'back up and securely wipe the disk'),
           mcq('Which toxic metal is found in old CRT monitors?', ['Lead', 'Gold', 'Aluminium'], 'Lead'),
           tf('Burning e-waste is a safe way to recover metals.', False)]),

    80: L6ALG[87],
    81: L6ALG[88],
    82: L6ALG[85],
    83: L6ALG[90],

    84: L('Writing code 1: a complete Python program — input with validation, a list, a loop and a summary.',
          [('Program', code('marks = []\nn = int(input("How many students? "))\nfor i in range(n):\n    m = float(input(f"Mark {i + 1}: "))\n    while m < 0 or m > 20:\n        m = float(input("Mark must be 0-20, try again: "))\n    marks.append(m)\n\naverage = sum(marks) / len(marks)\npassed = len([m for m in marks if m >= 10])\nprint("Average:", round(average, 2))\nprint("Passed:", passed, "of", n)')),
           ('What it shows', '<ul><li>Input and conversion</li><li>Validation loop</li><li>List building with append</li><li>Built-in functions sum, len, round</li></ul>')],
          [fill('Marks entered: 12, 8, 16. Average printed =', '{0}', [['12', '12.0']]),
           fill('Same marks. Passed =', '{0}', [['2']]),
           mcq('The user types 25. What happens?', ['They are asked again', 'It is stored', 'The program crashes'], 'They are asked again'),
           mcq('Which line adds a mark to the list?', ['marks.append(m)', 'marks = []', 'sum(marks)'], 'marks.append(m)')]),

    85: L('Writing code 2: organise a program into functions that each do one job.',
          [('Program', code('def grade(mark):\n    if mark >= 16: return "A"\n    if mark >= 14: return "B"\n    if mark >= 12: return "C"\n    if mark >= 10: return "D"\n    return "F"\n\ndef report(name, mark):\n    print(f"{name}: {mark} -> {grade(mark)}")\n\nstudents = {"Awa": 15, "Paul": 9, "Ngum": 18}\nfor name, mark in students.items():\n    report(name, mark)')),
           ('Ideas', '<ul><li>def, parameters, return</li><li>A dictionary maps names to marks</li><li>One function calls another</li></ul>')],
          [mcq('grade(15) returns…', ['B', 'A', 'C'], 'B'),
           mcq('grade(9) returns…', ['F', 'D', 'C'], 'F'),
           fill('How many lines does the program print?', '{0}', [['3']]),
           mcq('What is students["Ngum"]?', ['18', '"A"', 'Ngum'], '18')]),

    86: L('Writing code 3: save and load data with files so it is not lost when the program ends.',
          [('Write and read a file', code('# write\nwith open("marks.csv", "w") as f:\n    f.write("Awa,15\\n")\n    f.write("Paul,9\\n")\n\n# read\ntotal = 0\nwith open("marks.csv") as f:\n    for line in f:\n        name, mark = line.strip().split(",")\n        total += int(mark)\nprint("Total:", total)')),
           ('Modes', table(['Mode', 'Meaning'], [['"r"', 'read (default)'], ['"w"', 'write (replaces the file)'], ['"a"', 'append to the end']])),
           ('Errors', '<p>Use try/except for FileNotFoundError and invalid data.</p>')],
          [fill('What does the program print?', 'Total: {0}', [['24']]),
           match('Match the mode.', [('Add a new line to the end of a log', '"a"'), ('Create a new file / overwrite', '"w"'), ('Only read the file', '"r"')]),
           mcq('"Awa,15".split(",") gives…', ["['Awa', '15']", "['Awa,15']", "('Awa', 15)"], "['Awa', '15']"),
           tf('Opening a file with "w" deletes its previous content.', True)]),
}
