"""Upper Sixth ICT: error checking, internet, e-services, web development, business, project management (lessons 35-56)."""
from helpers import *
from f3_maths_part1 import table
from l6_ict_part5 import code

GANTT = svg(440, 170, ''.join(
    [f'<text x="10" y="{36 + i * 32}" class="v-t">{t}</text>' for i, t in enumerate('ABCD')] +
    [f'<rect x="{40 + s * 36}" y="{20 + i * 32}" width="{d * 36}" height="22" rx="4" class="{c}"/>' for i, (s, d, c) in enumerate([(0, 3, 'v-box2'), (3, 4, 'v-box2'), (3, 2, 'v-box'), (7, 2, 'v-box2')])] +
    [f'<text x="{40 + k * 36}" y="160" text-anchor="middle" class="v-s">{k}</text>' for k in range(0, 11)]), 'Gantt chart')

LESSONS = {
    35: L('Errors happen during transmission. Parity, checksums, check digits, CRC and echo checks detect them; ARQ re-sends.',
          [('Parity', '<p><b>Even parity</b>: the total number of 1s (including the parity bit) is even.</p><p>1011001 has four 1s → even parity bit = <b>0</b>. Odd parity bit = <b>1</b>.</p><p>Limit: two flipped bits are not detected.</p>'),
           ('Other checks', table(['Method', 'Idea'], [['Checksum', 'sender adds a value computed from the data; receiver recomputes'], ['Check digit', 'extra digit computed from the others (barcodes, ISBN)'], ['CRC', 'polynomial division remainder — detects burst errors'], ['Echo check', 'receiver sends data back; sender compares'], ['Parity block', 'parity on rows and columns: can locate a single bit error']])),
           ('ARQ', '<p>Automatic Repeat reQuest: receiver sends ACK (ok) or NAK (error); if no ACK before the timeout, the sender re-transmits.</p>')],
          [fill('Even parity bit for 1100101?', '{0}', [['0']], 'Four 1s → already even.'),
           fill('Even parity bit for 1110000?', '{0}', [['1']]),
           fill('Odd parity bit for 1010101?', '{0}', [['1']], 'Four 1s → add 1 to make five.'),
           mcq('Even parity is used. Received 10110001 (four 1s). Conclusion?', ['No error detected', 'Error detected', 'Two errors found'], 'No error detected'),
           match('Match the method.', [('Receiver sends data back to compare', 'Echo check'), ('ACK / NAK and re-transmission', 'ARQ'), ('Remainder of polynomial division', 'CRC')])]),

    36: L('The internet grew from a 1969 research network into the global network of networks we use today.',
          [('Timeline', table(['Year', 'Event'], [['1969', 'ARPANET links 4 US universities'], ['1971', 'first email'], ['1983', 'ARPANET adopts TCP/IP — the "birth" of the internet'], ['1984', 'DNS introduced'], ['1989–91', 'Tim Berners-Lee invents the World Wide Web (HTTP, HTML)'], ['1993', 'Mosaic, first popular graphical browser'], ['1998', 'Google founded'], ['2004–2007', 'social media, smartphones (iPhone 2007)'], ['2010s', '4G, cloud, mobile money'], ['2020s', '5G, IoT, generative AI']])),
           ('Internet vs WWW', '<p>The <b>internet</b> is the infrastructure (networks, TCP/IP). The <b>WWW</b> is a service on it (web pages via HTTP).</p>')],
          [order('Put the events in order.', ['ARPANET', 'TCP/IP adopted', 'World Wide Web invented', 'Google founded', '5G networks']),
           mcq('Who invented the World Wide Web?', ['Tim Berners-Lee', 'Bill Gates', 'Charles Babbage'], 'Tim Berners-Lee'),
           tf('The internet and the World Wide Web are the same thing.', False)]),

    37: L('Connect to the internet through dial-up, DSL, cable, fibre, mobile or satellite technologies.',
          [('Technologies', table(['Technology', 'Typical speed', 'Notes'], [['Dial-up', '56 kbps', 'obsolete, phone line'], ['DSL / ADSL', 'up to ~20 Mbps', 'telephone line'], ['Cable', '100+ Mbps', 'TV cable'], ['Fibre (FTTH)', '100 Mbps – 1 Gbps+', 'fastest fixed'], ['3G / 4G / 5G', 'Mbps to Gbps', 'mobile, everywhere with coverage'], ['Satellite', 'up to ~200 Mbps', 'remote areas, higher latency']])),
           ('Requirements', '<p>Device + modem/router (or SIM) + ISP subscription + browser/apps. Optional: Wi-Fi router, firewall.</p>')],
          [order('From slowest to fastest (typical).', ['Dial-up', 'ADSL', '4G', 'Fibre']),
           mcq('Which has the highest latency?', ['Satellite', 'Fibre', 'Cable'], 'Satellite', 'The signal travels to space and back.'),
           match('Match the technology.', [('Uses the telephone line', 'DSL'), ('Uses light in glass cables', 'Fibre'), ('Uses a SIM card', 'Mobile 4G/5G'), ('Uses a dish', 'Satellite')])]),

    38: L('Social networks connect people; collaborative environments let them work together online.',
          [('Examples', table(['Type', 'Examples'], [['Social networks', 'Facebook, WhatsApp, X, Instagram, TikTok'], ['Professional', 'LinkedIn'], ['Collaboration', 'Google Docs/Drive, Microsoft Teams, Slack, Trello'], ['Knowledge sharing', 'wikis, forums, GitHub']])),
           ('Benefits and risks', '<div class="two-col"><div><b>➕</b>communication, marketing, learning, teamwork across distance</div><div><b>➖</b>privacy loss, fake news, cyberbullying, addiction, scams</div></div>'),
           ('Good practice', '<p>Privacy settings, think before posting, verify information, respect netiquette, use version history in shared documents.</p>')],
          [sort('Social network or collaboration tool?', ['Social network', 'Collaboration tool'], [('Instagram', 'Social network'), ('Google Docs', 'Collaboration tool'), ('TikTok', 'Social network'), ('Microsoft Teams', 'Collaboration tool'), ('Trello', 'Collaboration tool')]),
           mcq('Best platform to find a job and show your CV?', ['LinkedIn', 'TikTok', 'Snapchat'], 'LinkedIn'),
           tf('Version history lets you restore an earlier version of a shared document.', True)]),

    39: L('The internet offers many services. Use search engines skilfully and evaluate what you find.',
          [('Services', '<div class="chips"><span>WWW</span><span>Email</span><span>File transfer (FTP)</span><span>Cloud storage</span><span>Streaming</span><span>Online banking</span><span>E-learning</span></div>'),
           ('Search operators', table(['Operator', 'Example', 'Effect'], [['" "', '"climate change Cameroon"', 'exact phrase'], ['OR', 'Douala OR Yaoundé', 'either word'], ['−', 'jaguar −car', 'exclude a word'], ['site:', 'site:gov.cm exams', 'one website/domain'], ['filetype:', 'filetype:pdf syllabus', 'one file type']])),
           ('Evaluate sources', '<p>Authority (who?), accuracy (evidence?), currency (date?), objectivity (bias?), coverage.</p>')],
          [match('Match the search.', [('Only PDF files', 'filetype:pdf'), ('Only government sites of Cameroon', 'site:gov.cm'), ('The exact sentence', 'Quotation marks'), ('Remove results about cars', '−car')]),
           mcq('Which source is most reliable for exam timetables?', ['The official ministry website', 'An anonymous blog', 'A forwarded WhatsApp image'], 'The official ministry website'),
           tf('A more recent date is a sign of better currency.', True)]),

    40: L('The internet supports communication (email, messaging, VoIP, video) and teleworking from anywhere.',
          [('Tools', table(['Tool', 'Example'], [['Email', 'Gmail, Outlook'], ['Instant messaging', 'WhatsApp, Telegram'], ['VoIP', 'WhatsApp calls, Skype'], ['Video conferencing', 'Zoom, Google Meet, Teams'], ['Shared workspaces', 'Google Workspace, Microsoft 365']])),
           ('Teleworking', '<div class="two-col"><div><b>➕ for workers</b>no commute, flexible hours · <b>➕ employers</b> less office cost, wider talent</div><div><b>➖</b>isolation, distractions, needs reliable internet and power, security risks, hard to supervise</div></div>')],
          [sort('Advantage or disadvantage of teleworking?', ['Advantage', 'Disadvantage'], [('No time lost in traffic', 'Advantage'), ('Feeling isolated', 'Disadvantage'), ('Lower office rent', 'Advantage'), ('Depends on reliable internet', 'Disadvantage')]),
           mcq('VoIP means…', ['voice calls over the internet', 'video on a projector', 'a virus'], 'voice calls over the internet'),
           tf('Teleworkers should use a VPN to access company systems securely.', True)]),

    42: L('E-commerce, e-health and e-government deliver business, health and public services electronically.',
          [('E-commerce', table(['Type', 'Example'], [['B2C', 'online shop selling to customers'], ['B2B', 'supplier selling to shops'], ['C2C', 'individuals selling on Facebook Marketplace'], ['G2C', 'government services to citizens']])),
           ('E-health', '<p>Telemedicine consultations, electronic health records, SMS reminders, online pharmacies.</p>'),
           ('E-government', '<p>Online tax declaration, exam results online, ID and passport appointments, public procurement portals.</p>')],
          [match('Which e-service?', [('Buying a phone from an online shop', 'E-commerce (B2C)'), ('Doctor consultation by video', 'E-health'), ('Paying taxes online', 'E-government'), ('Selling your old bike to another person online', 'E-commerce (C2C)')]),
           mcq('A company buys stock from its supplier\'s portal. This is…', ['B2B', 'B2C', 'C2C'], 'B2B'),
           tf('Electronic health records let doctors see a patient\'s history quickly.', True)]),

    43: L('E-services bring speed and convenience, but face challenges of access, trust, security and skills.',
          [('Benefits', '<ul><li>24/7 access, no travel or queues</li><li>Lower costs, wider markets</li><li>Transparency, less corruption in public services</li><li>Mobile money makes payments easy</li></ul>'),
           ('Challenges', '<ul><li>Poor connectivity and power in rural areas</li><li>Fraud, scams and cybercrime</li><li>Low digital literacy</li><li>Data privacy concerns</li><li>Delivery logistics and trust</li></ul>')],
          [sort('Benefit or challenge?', ['Benefit', 'Challenge'], [('Pay bills at midnight from home', 'Benefit'), ('Unstable internet in villages', 'Challenge'), ('Fake online shops', 'Challenge'), ('Reach customers in other towns', 'Benefit'), ('Many people unsure how to use apps', 'Challenge')]),
           mcq('Which reduces fraud in online payments?', ['Two-factor authentication', 'Sharing your PIN', 'Public Wi-Fi'], 'Two-factor authentication'),
           tf('Mobile money has helped e-commerce grow in Cameroon.', True)]),

    44: L('Computer-assisted learning and e-learning use technology to teach, practise and assess.',
          [('CAL types', table(['Type', 'Example'], [['Drill and practice', 'repeated quiz questions'], ['Tutorial', 'step-by-step lessons'], ['Simulation', 'virtual lab experiments'], ['Educational games', 'learning through play'], ['Assessment', 'online tests with instant marking']])),
           ('E-learning', '<p>LMS (Moodle, Google Classroom), MOOCs (Coursera, edX), video lessons, AI tutors. <b>Synchronous</b> (live) vs <b>asynchronous</b> (any time).</p>'),
           ('Pros and cons', '<div class="two-col"><div><b>➕</b>learn at own pace, anywhere, instant feedback, rich media</div><div><b>➖</b>needs devices, data and power; less social contact; self-discipline</div></div>')],
          [match('Match the CAL type.', [('Virtual chemistry lab', 'Simulation'), ('100 multiplication questions with feedback', 'Drill and practice'), ('Step-by-step lesson with examples', 'Tutorial')]),
           sort('Synchronous or asynchronous?', ['Synchronous', 'Asynchronous'], [('Live Zoom class', 'Synchronous'), ('Recorded video lesson', 'Asynchronous'), ('Discussion forum', 'Asynchronous'), ('Live online quiz', 'Synchronous')]),
           tf('An interactive lesson platform like this one is a form of CAL.', True)]),

    46: L('HTML structures web pages with tags: headings, paragraphs, links, images, lists, tables and forms.',
          [('Page structure', code('<!DOCTYPE html>\n<html>\n<head>\n  <title>My School</title>\n</head>\n<body>\n  <h1>Welcome</h1>\n  <p>We are in <b>Bamenda</b>.</p>\n  <a href="contact.html">Contact us</a>\n  <img src="logo.png" alt="School logo">\n</body>\n</html>')),
           ('Common tags', table(['Tag', 'Use'], [['&lt;h1&gt;…&lt;h6&gt;', 'headings'], ['&lt;p&gt;', 'paragraph'], ['&lt;a href&gt;', 'link'], ['&lt;img src alt&gt;', 'image'], ['&lt;ul&gt; &lt;ol&gt; &lt;li&gt;', 'lists'], ['&lt;table&gt; &lt;tr&gt; &lt;td&gt;', 'tables'], ['&lt;form&gt; &lt;input&gt;', 'forms']]))],
          [match('Match the tag.', [('&lt;h1&gt;', 'Main heading'), ('&lt;a&gt;', 'Link'), ('&lt;img&gt;', 'Image'), ('&lt;li&gt;', 'List item')]),
           order('Order the basic page structure.', ['&lt;!DOCTYPE html&gt;', '&lt;html&gt;', '&lt;head&gt; with &lt;title&gt;', '&lt;body&gt; with content', '&lt;/html&gt;']),
           mcq('Which attribute gives the link destination?', ['href', 'src', 'alt'], 'href'),
           mcq('Why add alt to an image?', ['Text for screen readers and if the image fails', 'To make it bigger', 'To link it'], 'Text for screen readers and if the image fails')]),

    47: L('CSS styles HTML: colours, fonts, spacing and layout, using selectors and properties.',
          [('Syntax', code('h1 {\n  color: navy;\n  font-size: 32px;\n}\n.note { background: #ffeeba; padding: 10px; }\n#menu { display: flex; gap: 12px; }')),
           ('Selectors and placement', table(['Selector', 'Targets'], [['h1', 'all h1 elements'], ['.note', 'elements with class="note"'], ['#menu', 'the element with id="menu"']]) + '<p>Inline (style="…"), internal (&lt;style&gt;), external (&lt;link rel="stylesheet" href="style.css"&gt;) — external is best for many pages.</p>'),
           ('Box model', '<p>content → padding → border → margin. Width 200 + padding 2×10 + border 2×2 = <b>224 px</b> total (content-box).</p>')],
          [match('Match the selector.', [('.card', 'Elements with class "card"'), ('#logo', 'Element with id "logo"'), ('p', 'All paragraphs')]),
           fill('Width 300, padding 15 on each side, border 5 on each side.', 'Total width = {0} px', [['340']]),
           mcq('Which is best for styling a 20-page website?', ['An external stylesheet', 'Inline styles on every element', 'No CSS'], 'An external stylesheet'),
           order('Order the box model from inside out.', ['Content', 'Padding', 'Border', 'Margin'])]),

    48: L('JavaScript makes pages interactive: variables, functions, events and changing the page (DOM).',
          [('Example', code('<input id="mark"> <button onclick="check()">Check</button>\n<p id="result"></p>\n<script>\nfunction check() {\n  let m = Number(document.getElementById("mark").value);\n  let msg = (m >= 10) ? "Pass" : "Fail";\n  document.getElementById("result").textContent = msg;\n}\n</script>')),
           ('Key ideas', '<ul><li><b>Variables</b>: let, const</li><li><b>Functions</b> run code when called</li><li><b>Events</b>: onclick, oninput, onsubmit</li><li><b>DOM</b>: document.getElementById(...) to read/change elements</li><li>Use for form validation, calculators, quizzes</li></ul>')],
          [mcq('The user types 12 and clicks Check. The page shows…', ['Pass', 'Fail', '12'], 'Pass'),
           mcq('Which event runs when a button is clicked?', ['onclick', 'onload', 'onhover'], 'onclick'),
           fill('let a = 5; let b = a * 2 + 1; b =', '{0}', [['11']]),
           match('HTML, CSS or JavaScript?', [('Structure and content', 'HTML'), ('Colours and layout', 'CSS'), ('Behaviour and interactivity', 'JavaScript')])]),

    49: L('To publish a website: register a domain, choose hosting, upload files (or use a CMS), and secure it with HTTPS.',
          [('Steps', flow(['Register domain', 'Choose hosting', 'Point DNS', 'Upload files / install CMS', 'Add SSL (HTTPS)', 'Test and promote'])),
           ('Hosting types', table(['Type', 'Notes'], [['Shared', 'cheap, many sites on one server'], ['VPS', 'virtual private server, more control'], ['Dedicated', 'a whole server, expensive'], ['Cloud / static', 'scalable (e.g. Vercel, Netlify for static sites)']])),
           ('CMS', '<p>Content Management System: edit pages without coding — WordPress, Joomla, Drupal. Themes for design, plugins for features.</p>')],
          [order('Order the publishing steps.', ['Register a domain name', 'Choose a hosting plan', 'Point the domain\'s DNS to the host', 'Upload files or install a CMS', 'Enable HTTPS']),
           mcq('WordPress is a…', ['content management system', 'web browser', 'programming language'], 'content management system'),
           mcq('An SSL/TLS certificate enables…', ['HTTPS encryption', 'faster typing', 'email only'], 'HTTPS encryption'),
           match('Match the hosting.', [('Cheapest, shared resources', 'Shared hosting'), ('Whole physical server', 'Dedicated server'), ('Virtual server with root access', 'VPS')])]),

    51: L('Many business problems can be solved with IT. Identify the need, then match an IT solution.',
          [('Needs and solutions', table(['Business need', 'IT solution'], [['Track stock in a shop', 'inventory / POS system with barcodes'], ['Reach more customers', 'website, social media marketing, online shop'], ['Accept payments easily', 'mobile money / card payments'], ['Keep customer records', 'CRM or database'], ['Manage accounts', 'accounting software / spreadsheets'], ['Coordinate staff', 'WhatsApp groups, shared calendars']])),
           ('Starting an IT business', '<p>Ideas: web design, phone repair, cyber café, IT training, mobile apps. Use a <b>SWOT</b> analysis (Strengths, Weaknesses, Opportunities, Threats) and a simple business plan.</p>')],
          [match('Match the need to the IT solution.', [('Shop often runs out of popular items', 'Inventory system'), ('Customers want to pay without cash', 'Mobile money payments'), ('Bakery wants customers in other neighbourhoods', 'Social media marketing'), ('Forgetting which customers owe money', 'Customer database / CRM')]),
           match('SWOT.', [('Strong IT skills', 'Strength'), ('Little starting capital', 'Weakness'), ('Many shops have no website', 'Opportunity'), ('A competitor opens nearby', 'Threat')]),
           tf('A SWOT analysis looks at both internal and external factors.', True)]),

    52: L('A project is temporary work with a defined goal, constrained by scope, time and cost.',
          [('Definition', '<p>Temporary, unique, with start and end dates, a budget and a clear deliverable (e.g. "build the school website by March").</p>'),
           ('Triple constraint', '<p class="wt-key">Scope · Time · Cost → Quality</p><p>Change one and the others are affected.</p>'),
           ('Life cycle', flow(['Initiation', 'Planning', 'Execution', 'Monitoring & control', 'Closure']))],
          [order('Order the project life cycle.', ['Initiation', 'Planning', 'Execution', 'Monitoring and control', 'Closure']),
           sort('Project or routine operation?', ['Project', 'Operation'], [('Building a new computer lab', 'Project'), ('Daily cleaning of classrooms', 'Operation'), ('Organising this year\'s science fair', 'Project'), ('Paying monthly salaries', 'Operation')]),
           mcq('The client adds features but the deadline stays. What else must change?', ['Cost or resources (or quality suffers)', 'Nothing', 'The project name'], 'Cost or resources (or quality suffers)')]),

    53: L('Project management also covers stakeholders, roles, scope, risk and communication.',
          [('People', '<p><b>Sponsor</b> (funds), <b>project manager</b> (leads), <b>team</b>, <b>stakeholders</b> (anyone affected: users, principal, parents).</p>'),
           ('Key documents', table(['Document', 'Content'], [['Project charter', 'goal, sponsor, PM, high-level scope, budget'], ['Scope statement', 'what is and is not included'], ['Risk register', 'risks, likelihood, impact, response'], ['Communication plan', 'who gets what information, when']])),
           ('Risk responses', '<p>Avoid, reduce (mitigate), transfer (insurance), accept.</p>')],
          [match('Match the role.', [('Provides the money', 'Sponsor'), ('Plans and leads the work', 'Project manager'), ('Anyone affected by the project', 'Stakeholder')]),
           match('Match the risk response.', [('Buy insurance for equipment', 'Transfer'), ('Install a UPS against power cuts', 'Reduce (mitigate)'), ('Drop a risky feature', 'Avoid'), ('Accept small delays from rain', 'Accept')]),
           mcq('Which document formally starts a project?', ['Project charter', 'Gantt chart', 'Final report'], 'Project charter')]),

    54: L('A Work Breakdown Structure (WBS) breaks the project into deliverables and small work packages.',
          [('Example', code('1  School website\n1.1  Planning\n     1.1.1 Gather requirements\n     1.1.2 Plan site map\n1.2  Design\n     1.2.1 Wireframes\n     1.2.2 Choose colours and logo\n1.3  Build\n     1.3.1 Write HTML/CSS pages\n     1.3.2 Add contact form\n1.4  Test and launch')),
           ('Rules', '<ul><li>Decompose until tasks are small enough to estimate and assign</li><li>100% rule: the WBS includes all the work</li><li>Each package has an owner, duration and cost</li></ul>')],
          [mcq('In the WBS, "Wireframes" belongs to…', ['1.2 Design', '1.3 Build', '1.1 Planning'], '1.2 Design'),
           order('Order from biggest to smallest.', ['Project', 'Deliverable / phase', 'Work package']),
           tf('The 100% rule means the WBS includes all the work of the project.', True),
           fill('Three work packages cost 40 000, 25 000 and 35 000 FCFA. Total =', '{0}', [['100000', '100 000']])]),

    55: L('Gantt charts show tasks on a timeline; PERT estimates durations using optimistic, most likely and pessimistic times.',
          [('Gantt chart', GANTT + '<p>A (0–3), B (3–7), C (3–5), D (7–9). B and C run in parallel. The project takes 9 days.</p>'),
           ('PERT estimate', '<p class="wt-key">tₑ = (o + 4m + p) ÷ 6</p><p>o = 2, m = 4, p = 12 → (2 + 16 + 12) ÷ 6 = <b>5 days</b></p>')],
          [fill('In the Gantt chart, task B starts on day', '{0}', [['3']], visual=GANTT),
           fill('Total project duration (days)?', '{0}', [['9']]),
           fill('PERT: o = 3, m = 6, p = 15.', 'tₑ = {0}', [['7']], '(3 + 24 + 15) ÷ 6 = 7'),
           mcq('Which tasks overlap in time?', ['B and C', 'A and D', 'A and B'], 'B and C')]),

    56: L('The critical path is the longest path through the project; tasks on it have zero slack.',
          [('Example', table(['Task', 'Duration', 'Depends on'], [['A', '3', '—'], ['B', '4', 'A'], ['C', '2', 'A'], ['D', '2', 'B, C']]) + '<p>Paths: A-B-D = 9, A-C-D = 7 → critical path <b>A-B-D (9 days)</b>.</p>'),
           ('Slack (float)', '<p>Forward pass: earliest start (ES), earliest finish (EF). Backward pass: latest start (LS), latest finish (LF).</p><p class="wt-key">Slack = LS − ES</p><p>C: ES = 3, LS = 5 → slack = <b>2 days</b>.</p>'),
           ('Control', '<p>Track progress against the plan; act on delays to critical tasks first.</p>')],
          [fill('Paths: P-Q-T = 2 + 6 + 3 and P-R-T = 2 + 4 + 3.', 'Project length = {0}', [['11']]),
           fill('In that project, slack of R =', '{0}', [['2']]),
           mcq('A task with zero slack is…', ['on the critical path', 'not important', 'already finished'], 'on the critical path'),
           mcq('Task C (slack 2) is delayed by 1 day. The project…', ['is not delayed', 'is delayed by 1 day', 'is cancelled'], 'is not delayed')]),
}
